### ISSUE TITLE
No lineage information on dev

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1007]
**Describe the bug**
Lineage information is not available on dev. For example https://dev.renku.ch/projects/renku-qa/flights-tutorial/files/lineage/data/output/2019-01-flights-count.txt

**Link to project**
https://dev.renku.ch/projects/renku-qa/flights-tutorial

**Comment by rokroskar** [comment]
This has been fixed.
