### ISSUE TITLE
feat(svc): add models for service resources

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1027]
Service has no concept of model which can be saved to cache. For it currently we are using plain dicts and this is quite limiting. We would need a support for better general life cycle management of such resources (projects, files, jobs).

For example, internal ID's could be generated within a model, state mutation should happen on the object itself, object cleanup and error management should be self contained.

I've found [walrus](https://walrus.readthedocs.io/en/latest/models.html#creating-updating-and-deleting) library to be potentially quite a good choice for it. I propose we add it to our resource management to have things in more cleaner and testable way.

**Comment by rokroskar** [comment]
It can even function as a triple store! https://walrus.readthedocs.io/en/latest/graph.html 👍 

Walrus seems like it would be a reasonable choice for this - any cons?
