### ISSUE TITLE
Renku status hangs

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#1041]
**Describe the bug**
Running renku status just hangs and doesn't show anything.

**Link to project**
https://renkulab.io/gitlab/remko.nijzink/vomcases

**To Reproduce**
Just run '''renku status'''

**Expected behavior**
To show if the repository is up to date

**Screenshots and/or execution output**
If applicable, add screenshots and/or copy-pasted execution output to help explain your problem.

**Run environment (please complete the following information):**
 - renku-python version 0.8.3.dev23
 -  Python 3.6.8
 - local terminal 

**Additional context**
Can it be that the repository has become too big?

**Comment by rokroskar** [comment]
Hi @rcnijzink thanks for reporting this - it's a problem with the current renku graph building implementation taking a long time to run on a repository with a lot of files and commits. We are working on this in #967 and #966. These are becoming very high priority and we plan on working on them starting with this sprint.

**Comment by Panaetius** [comment]
Solved in https://github.com/SwissDataScienceCenter/renku-python/issues/2110
