### ISSUE TITLE
cli: renku dataset

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#1070]
## Describe the bug
Running renku dataset leads to the error below. It seems one of my datasets has a local path, which shouldn't be possible. 

## Details
**Renku version:** 0.8.3.dev23
**OS:** Linux (#201902061234 SMP Wed Feb 6 17:36:40 UTC 2019)
**Python:** 3.6.8

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/commands/client.py", line 103, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/dataset.py", line 53, in dataset_parent
    missing_dataset, missing_files = check_dataset_resources(client)
  File "[...]/renku/core/commands/checks/migration.py", line 100, in check_dataset_resources
    relative = path.parent.relative_to(client.renku_datasets_path)
  File "[...]/pathlib.py", line 874, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/home/remko/Documents/renku-projects/VOM_cases_renku_egu/vomcases/.renku/datasets/56fbea62-c6a5-4c63-9457-09dbaf8a3ac9' does not start with '.renku/datasets'
```

**Comment by mohammad-sdsc** [comment]
Thanks @rcnijzink for reporting this!

This issue has been partially addressed in a new feature but it is not merged yet.
AFAIK, it shows up in two cases:
1. You are running CLI commands in some directory other than the root of your project (you should run renku CLI commands while your CWD is `/home/remko/Documents/renku-projects/VOM_cases_renku_egu/vomcases`).
2. Dataset files are deleted/moved without using renku commands which means that dataset's metadata is not updated while the file does not exist on the disk.

Can you please verify that one of these two cases has not happened? If this project is available somewhere I can help you with the second case.

Regards,
Mohammad

**Comment by rcnijzink** [comment]
I think it should be the second case then, it's this project:
https://renkulab.io/gitlab/remko.nijzink/vomcases

**Comment by mohammad-sdsc** [comment]
It seems that `TBM_data` dataset files were deleted without using Renku `unlink` or `rm` command. Moreover, there is another issue with nested datasets which are used in this project. As I mentioned, the fix for these problem is not merged yet and you cannot use Renku to fix them right now.

To continue using Renku on this project you need to fix the issue manually. Running the following commands on the root of your project should do the work:
1. `rm .renku/datasets/56fbea62-c6a5-4c63-9457-09dbaf8a3ac9/metadata.yml .renku/refs/datasets/DINGO .renku/refs/datasets/ELVIS .renku/refs/datasets/MODIS .renku/refs/datasets/MaunaLoa .renku/refs/datasets/TBM_data .renku/refs/datasets/VOM_input .renku/refs/datasets/fPAR`
2. `git add -u`
3. `git commit -m 'remove corrupted files'`
4. `renku migrate datasets`

Please let me know if you had any issues.

**Comment by rcnijzink** [comment]
Thanks, that worked! There are still some other minor issues with my datasets still though, and I know this is probably because it is nested quite a bit indeed. And it also happens as I generally let my model write output to a dataset-folder, to have it as lfs.

But renku dataset gives now this:
```
ID                                    CREATED              SHORT_NAME               CREATORS                                           TAGS    VERSION
------------------------------------  -------------------  -----------------------  -------------------------------------------------  ------  ---------
f495c97f-80f1-41b7-8f01-275edad9ff44  2019-09-11 18:57:44  boreholes                R.Nijzink,R.Nijzink
6d46d407-4a74-423a-ac9a-051a83f03d0f  2019-09-30 16:11:49  vomsoilslitchfield       R.Nijzink
3846f574-0691-4461-be3b-0c41eed009c5  2019-07-02 09:36:01  Silo
0fe23a5f-c3ea-4484-9704-74464efeea8e  2019-10-28 19:23:25  DINGO_QC                 R.Nijzink
2ebe8c58-ec5d-402b-ab1c-e789ffc6d6ff  2019-03-26 14:04:59  MODIS                    R.Nijzink
4db9445c-d7cc-4cd1-b7d7-d3a0fdf8fcc9  2020-01-29 15:18:52  DINGO_SWS                R.Nijzink
803cc2d1-a409-443e-8efd-ea2664232358  2019-03-08 07:31:00  MaunaLoa                 R.Nijzink
3ba60c7a-0121-4140-b964-1664b5922a89  2019-04-02 11:56:41  fPAR                     R.Nijzink
2f46a8c5-c03b-48a5-a094-3d07e619b1cf  2019-07-08 08:58:02  ELVIS                    R.Nijzink
6cd647df-f502-46b8-8aa1-ba689a7b53b9  2019-09-30 16:10:56  vomsoilsadelaideriver    R.Nijzink
0197e029-4ca7-4212-958a-19e2fefd51ee  2019-10-28 14:55:19  vomoutput
4b707a6a-1ee9-44cd-a1a5-efffa0b781ec  2020-01-28 12:59:59  SavMIP                   R.Nijzink
ef4e2b7c-47ed-427b-b584-59c6c7f690c9  2019-09-30 16:12:01  vomsoilshowardsprings    R.Nijzink
2a321073-9338-4803-9b76-1843e6a34e02  2020-02-28 15:14:37  data_from_a_model_inter  W.Rhys,D.K.Martin,H.Vanessa,R.Youngryel,L.Longhui
95b143e5-30b4-47b6-a1ed-5d33e28af562  2019-03-08 07:29:51  VOM_input                R.Nijzink
3ada2727-8ef6-4c3e-8873-d33109970636  2019-03-21 08:02:34  DINGO
16218bfe-07de-4ce8-951c-eadab5208141  2019-09-30 16:11:32  vomsoilsdryriver         R.Nijzink
5e4418f4-b9e1-4473-b12f-0d9781a39bc7  2019-09-30 16:11:22  vomsoilsdalyuncleared    R.Nijzink
97ef95e4-9a10-4631-b1f2-4e3a846fb84b  2019-03-08 07:29:56  VOM_output               R.Nijzink
f1d92965-72fc-4e73-b686-58312c529520  2019-03-08 07:29:36  DINGO                    R.Nijzink
93655899-f18a-4b77-92c2-3449adf754a2  2019-03-08 07:29:40  Silo                     R.Nijzink
3622c366-7e82-4ba6-a974-271bc99e29e2  2020-03-02 09:40:37  SavMIP_extracted         R.Nijzink
9cc55e25-6f2a-4ceb-a61f-7846c8176704  2019-08-19 13:38:24  DINGO2                   R.Nijzink
e05010b4-8723-4dc1-9495-ce52c76aa531  2019-10-28 17:09:24  img                      R.Nijzink,R.Nijzink
eea48f86-6d9b-467b-a791-1e506d1e2e9c  2020-03-02 10:40:50  SavMIP_stats             R.Nijzink
50908d1b-e66e-46cf-ae30-371bb944920c  2019-09-30 16:11:41  vomsoilssturtplains      R.Nijzink
```

However, it somehow takes a few things together, I have a dataset VOM_soils, with there for each study site the soil profile. But these are all shown here as one single dataset (e.g. vomsoilssturtplains instead of VOM_soils). Several shortnames are also different from the actual dataset names, like vomoutput instead of VOM_output. These are all small issues, but do you have some recommendations on how to clean this up a bit? Point here is also that quite some files are used as inputs for  long model runs, that I also don't want to re-run, so can I clean it up without getting renku to think that outputs are out of date?

**Comment by mohammad-sdsc** [comment]
Good to hear that!
Actually, these changes are due to the migrations which are required for renku to work. One thing that we don't support anymore is nested datasets. That's why you see some names has changed. As far as I can see, there are only datasets' short_names that have changes. Datasets are NOT merged. For example, `VOM_soils/AdelaideRiver` and `VOM_soils/Litchfield` datasets are renamed to `vomsoilsadelaideriver` and `vomsoilslitchfield` respectively. These short names are autogenerated and unfortunately you cannot change them.
All these changes are to the dataset metadata files and the actual data files are intact by the migration. Therefore, you do not need to re-run your workflows because data files did not change. Please let me know if this is not the case.

**Comment by rokroskar** [comment]
Just one more point to add -

> And it also happens as I generally let my model write output to a dataset-folder, to have it as lfs.

Note that files are added to LFS individually, not on a folder-by-folder basis. So if you put files in there manually (i.e. without using a renku command) you _must_ also do `git lfs track` _before_ you commit the file if you want it sent to LFS.

**Comment by rcnijzink** [comment]
Ok, yes, thanks for clarifying these things! I only add scripts usually manually, all other things with renku, so it should be okay then.

**Comment by rokroskar** [comment]
@rcnijzink did the issue get solved? In that case, can we close this?

**Comment by rcnijzink** [comment]
Yes, this was solved!

**Comment by rokroskar** [comment]
Great, I will close this issue for now. Thanks!
