### ISSUE TITLE
feat: allow the user to specify metadata on dataset creation

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1075]
Renku users should be able to specify required and optional metadata at the moment of dataset creation. This is needed for the CLI as well as the UI.

**Comment by mohammad-sdsc** [comment]
Related: https://github.com/SwissDataScienceCenter/renku-python/issues/515

**Comment by rokroskar** [comment]
Ah good point - so is this even needed still?

**Comment by mohammad-sdsc** [comment]
Depends if we need more metadata or not. ATM, it accepts description, title, and list of creators (name and email).

**Comment by rokroskar** [comment]
Does the backend support the same? cc @jsam

**Comment by jsam** [comment]
Service does support on dataset creation setting this metadata (name, creators, description). For any additional fields we should build support in the core first.

**Comment by rokroskar** [comment]
@vfried do you require other metadata at the moment?

**Comment by vfried** [comment]
I need to check, at the moment we are only sending names without spaces and it would be good to be able to send names that have spaces. I will check if this was fixed or if it's still causing problems.

**Comment by rokroskar** [comment]
@vfried @mohammad-sdsc @jsam is there additional metadata that needs to be added on creation? 

Right now we have

```
renku dataset create --help
Usage: renku dataset create [OPTIONS] SHORT_NAME

  Create an empty dataset in the current repo.

Options:
  -t, --title TEXT        Title of the dataset.
  -d, --description TEXT  Dataset's description.
  -c, --creator TEXT      Creator's name, email, and affiliation. Accepted
                          format is 'Forename Surname <email> [affiliation]'.

  -k, --keyword TEXT      List of keywords or tags.
  -h, --help              Show this message and exit.
```

**Comment by vfried** [comment]
I still didn't started working on implementing this changes inside the UI, if what's available in the UI is the same as for the CLI (what's shown in the comment above) i would say that it's good for now.

**Comment by jsam** [comment]
Another followup, #1236.

**Comment by rokroskar** [comment]
Can this be closed @jsam @vfried @mohammad-sdsc ?

**Comment by mohammad-sdsc** [comment]
> Can this be closed @jsam @vfried @mohammad-sdsc ?

On CLI side nothing more is needed. As for the UI, I'd prefer to close this and create an issue there if it's hasn't done yet.

**Comment by rokroskar** [comment]
agreed @mohammad-sdsc! closing for now - @vfried if something else is needed from the backend, please reopen this or  create a new issue. Thanks!
