### ISSUE TITLE
Migration corrupts some metadata

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1101]
**Describe the bug**
When a repo is migrated, the project ID is set to `localhost` and `created` is set to the current time instead of the time of project creation. 

**Link to project**
https://dev.renku.ch/gitlab/rokroskar/scratch-project/commit/cc2f96501c0b7abb36e26409d2104ce3ff1b4add#cb93b202c18d2faa64802af90b75a81953f45724_217_221

**Comment by mohammad-sdsc** [comment]
This is fixed in the new migration. If you run `renku migrate` with renku on `master` this won't happen.

**Comment by mohammad-sdsc** [comment]
The source of problem was that `RENKU_DOMAIN` env variable was not set on the interactive env which seems to be a bug.

**Comment by rokroskar** [comment]
no it should not depend on the environment variable, it should read the host from the git remote.

**Comment by mohammad-sdsc** [comment]
This problem occurs only for the `_project` property of `DatasetFile` only which seems to me as an unnecessary property for it.

**Comment by mohammad-sdsc** [comment]
> no it should not depend on the environment variable, it should read the host from the git remote.

Provided that a client is set for the project which is not always the case.
