### ISSUE TITLE
fix: wrong URL when adding to datasets via service

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1103]
```
"file://../../../../uploads/15eb65fd-3914-496a-861a-d0b8c2264cd8/101992.gif.pdf" 
```

Should be:
```
"file://101992.gif.pdf" 
```

**Comment by rokroskar** [comment]
I think the purpose of the `url` field is to be able to identify where it came from - since there is no way of establishing the source automatically, should we even be setting it?

**Comment by jsam** [comment]
I have 1 question about this URL topic. I agree completely that one of the potential cases is that we use that field to tell where the file came from but I think that is a miss use from my perspective (that's why I said that we should introduce a `source` property for that or newer version of it 'sameAs'). URL property as it is defined in schema stands for currently accessible URL of an item. So it's much more general in that sense. 

So instead of removing it, we should set it correctly. So for example in the case of file upload via service, that field could be something like: 
```
url: https://dev.renku.ch/projects/contact/integration-test/blob/9aaf8d0df1c0dec1b387250a399279e5d87ed7fa/data/ad35952ea8234123a7db829fc3834186/datafile1.txt
```

In case we opt for deletion this could be a property we build on the fly via `{project._id/file._id}`, but this will lead to potential problems down the road. Therefore, I'm not 100% sure that we should remove it.

**Comment by rokroskar** [comment]
Yeah that's a good point! I agree it's a misuse of the term. I think we used it because there is no obvious `source` term - but maybe there is now? Would be worth looking into, thanks for pointing it out!

**Comment by mohammad-sdsc** [comment]
After discussing with @Panaetius we decided that:
1. Introduce `renku:source` attribute to track source of the files added to a dataset. There is no other term defined in `schema.org` that carries the same meaning. We already use `schema:isBasedOn` to store file sources added from Git repos but it is meant to be used for derivative work and not tracking sources.
2. Value of `source` attribute for local and external files will be set to their path relative to the project's root directory.
3. `schema:url` attribute for `DatasetFile` will be set to `https://<host>/projects/<user>/<project>/files/blob/<path/to/file>`
