### ISSUE TITLE
Update cached templates

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-python#1122]
**Problem**
Currently, templates are downloaded and installed locally with the `renku` command line, but they are never updated.

**Proposal** (updated)
* Do *not* embed the templates in the `renku` package, but instead download them just after installing or whenever using `renku init` the first time
* When using `renku init`, check if there is an update in the remote repository and suggest users to download the latest template version. Do this only when `--template-source` is not specified and possibly with a reasonable cooldown (no need to check it frequently if multiple projects are initiated one after the other).
* We need a `minimum renku version` variable in the templates manifest file to avoid updating to an incompatible template version.
* [verify] we should probably move the templates cache folder to another location, like `~/.renku/templates`, to avoid any permission related problem when updating. Any obvious drawback with this approach?

**Comment by rokroskar** [comment]
This sounds like a good idea! I'm not sure about the implementation details... but what you suggest sounds very reasonable.

**Comment by lorenzo-cavazzi** [comment]
I am wondering if adding to the `manifest` file a field named `minimum-renku-version` would help in never breaking old code by avoid getting incompatible versions

**Comment by mohammad-sdsc** [comment]
Related: https://github.com/SwissDataScienceCenter/renku-python/issues/1306

**Comment by Panaetius** [comment]
For now, we focus only on keeping the templates inside a renku-python release up to date. In the future, we can implement template/docker functionality similar to how the UI uses it on the CLI.

**Comment by Panaetius** [comment]
We decided against this
