### ISSUE TITLE
template-able file names

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#1146]
**Is your feature request related to a problem? Please describe.**
the R project template will be augmented to include the [project-name].Rproj file, but currently there's no way to template file names (just strings within files).

**Describe the solution you'd like**
Template-able file names!

**Describe alternatives you've considered**
some kind of config file that describes a mapping between placeholder filenames and the templated names

**Additional context**
This would also be useful for users who want to template other filenames(?)

**Comment by rokroskar** [comment]
@lorenzo-cavazzi is this something that is being addressed already in one of the project-init PRs?

**Comment by lorenzo-cavazzi** [comment]
Not really, only the file content is currently templatable. But this issue shouldn't be too difficult to tackle.

**Comment by rokroskar** [comment]
Ok I added it to the upcoming milestone then.
