### ISSUE TITLE
renku command for removing LFS objects

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1147]
**Is your feature request related to a problem? Please describe.**

git-LFS lacks a command for removing LFS objects from the local cache. It's possible to do this with various git plumbing commands, but it's not very user friendly. 

**Describe the solution you'd like**

We should implement a renku command that, given a path in the local tree, will run `cat <path> | git lfs clean >> <path>` followed by removing the object from `.git/lfs/cache`. 

Some discussion can be found in this issue: https://github.com/git-lfs/git-lfs/issues/1189

**Comment by rokroskar** [comment]
Agree to time-box this to 1 day for an investigation.

**Comment by emmjab** [comment]
related: https://github.com/SwissDataScienceCenter/renku-python/issues/1202
