### ISSUE TITLE
How to update without re-running code and models?

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#1170]
I have this repository:

https://renkulab.io/projects/remko.nijzink/budyko

Now I have 32 model set-ups that all use a soilprofile (in data/VOM_soils/virtual_points) as input. The script that generates these soilprofiles is src_py/write_soilprofile.py. After running these 32 model setups, I found there was a mistake in this script, that leads to wrong soilprofiles in 2 cases. However, when I correct src_py/write_soilprofile.py renku probably requires me to run all 32 cases again, and i want to avoid this for computation reasons, and there will be no difference for the other 30 runs.

So if the output of src_py/write_soilprofile.py is exactly the same, will renku update also try to re-run the model? Or will it recognize this and leave the model runs?  And if it does re-run the model, do you have some advice on how to deal with this and avoid that?

**Comment by rokroskar** [comment]
Hi @rcnijzink I'm not sure tbh - could you update first just the intermediate files (soilprofiles)? And only afterwards update the models? You could also try with `renku rerun <path>` to recompute a specific model output.

**Comment by rcnijzink** [comment]
Yes, I could definitely do that, I can just re-do it by myself of course. Point is that the model has a long run time (more than a day), so it is actually a bit of a waste of computational resources to re-run 30 model set-ups that will have the same outcomes in the end. So I basically do not want to run the 30 cases that have correct soilprofiles at all. One workaround is probably adding a new version of the write_soilprofile.py (e.g. write_soilprofile_corrected.py, so then there are two scripts in the repo), but was hoping there would be a more elegant solution for this.

**Comment by rokroskar** [comment]
yes sure I understand - that's why I suggested you just run `renku update` on the soilprofiles part and then on the whole pipeline. But it's not obvious to me that the result will be what you want.

**Comment by rcnijzink** [comment]
Ok, then that's how it is. Thanks anyway ;)
