### ISSUE TITLE
feat(service): add endpoint for editing datasets metadata

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1184]
Currently, core module supports editing metadata for `title`, `description` and `creators`. This functionality should be exposed through an endpoint.

Example request:
```
POST /datasets.edit

{
  'project_id': 'dsfdf',
  'short_name': 'dataset short name form',
  'title': 'specify title to which title change should be',
  'description': '-||-',
  'creators': [{'name': 'sam', 'email': 'sam@sdsc.ethz.ch', 'label': null, 'affiliation': '', 'alternate_name': null}],
  'commit_message': <optional>
}
```

Expected response:

```
{
  'result': {
    'edited': {'title': <new title>, 'description': <new description>, 'creators': <creators>},
    'warnings': ['any warning which core might express']
  }
}
```

**Comment by rokroskar** [comment]
What about `dataset-id` in the `POST` data?

**Comment by jsam** [comment]
Well, I'm following the core specification and how the API is set there. So if you want to work it with `dataset_ids` we should open a ticket and change the core API for that.

**Comment by rokroskar** [comment]
True I guess per project `short_name` will be unique 👍
