### ISSUE TITLE
renku dataset commands hang when 3rd party provider is down

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#1193]
**Describe the bug**
Ran `renku dataset import https://zenodo.org/record/3606669 --short-name my-data` to test a PR, and the command hung.

@mohammad-sdsc realized zenodo was down (I didn't think to check because there was another issue where renku commands were hanging because renku was checking if it needed to migrate versions).

**Expected behavior**
It would be nice to get an error message if renku can't connect to the 3rd party server, which could include the link to the site that the user could visit and potentially visually inspect.

**Comment by jsam** [comment]
#1172 should help to alleviate the hanging part once merged. We experienced similar behavior now couple of time.

**Comment by emmjab** [comment]
Thanks @jsam -- how are the configurable timeouts used? is there something i can test to confirm this works?

**Comment by Panaetius** [comment]
This was recently changed to be around 6 seconds. It'll try, retry after 0.5 seconds, retry after 1, then 2, then 3 seconds and then fail.
