### ISSUE TITLE
renku -S docs section

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#1201]
**Is your feature request related to a problem? Please describe.**
At the risk of accidentally providing users new opportunities to commit really large files into their repos, it might be nice to sometimes permit, for people who know what they're doing, maybe, the option to add files to a dataset without storing them in LFS.

What problem are we trying to solve?

*Use case 1: viewing files that are small enough to view*
I want to be able to view my dataset files in the file browser, so I & others can take a look without having to start an environment, with the LFS button checked, which might add in tons of extra data & take forever to start. If these files are super large, I know I won't be able to see them, and it would be ridiculous to try to render them (and equally ridiculous to commit them to the git repo not in LFS). So, I only expect to be able to view my files that are part of a dataset in the file browser when they're smaller than some reasonable threshold.

*Use case 2: unavoidable/desirable code files in datasets*
I want to import a dataset from a 3rd party platform, and that dataset contains code. Code files are kind of supposed to live in the git tree. I want to be able to share/view the contents of the file from the renkulab UI, and also I want to be able to run the code from that dataset on other data in other datasets, and i don't want to have to do anything special to `renku storage pull dataset/code.py` every time.

*Use case 3: ability to git diff changes to dataset files*
I want to view changes to my dataset files over time.

**why? why would we do this??**
Iterating towards using LFS as its meant to be used without confounding users more than we already are.

**Describe the solution you'd like**

OPTION 1:
`renku dataset add <my dataset> <my file> --no-lfs`
`renku dataset import <blah blah> --no-lfs`

OPTION 2:
`renku dataset add <my dataset> <my file> --try-no-lfs`
`renku dataset import <blah blah> --try-no-lfs`

The second option might be nicer -- if can be implemented to check the size of the total amount of files, and each file about to be added: 
* If above some threshold, print `above LFS threshhold of 100MB, adding to LFS`
* If below the threshold, print  `under LFS threshhold of 100MB, not adding to LFS`
* If the total amount of data in the import exceeds some other threshhold, print `total import size of XMB exceeds threshhold of 500MB, adding to LFS. To later exclude files from LFS, <follow these docs>`

**Describe alternatives you've considered**
This behavior could be default behavior, but i think we should test using it as an option first to see if it solves the problem we want to solve.

**Additional context**
Part of the fix LFS epic.

**Comment by emmjab** [comment]
Wait -- we already have `renku -S` -- maybe we should just better document this option as something available to users.

I keep forgetting about it; just came up when I was trying to test the bugfix for repos without LFS already installed.

**Comment by rokroskar** [comment]
Are your proposals in the description of the issue different from #919?

The `-S` option is not great because it's a global option and needs to be specified _before_ the actual renku command - this is afaik the only way to keep it top-level with the CLI interface we're using (`click`). Still, as it is now it isn't taking into account the file size at all.

**Comment by emmjab** [comment]
I guess this is basically a more detailed version of #919 😄 

#919 asks for:
* a default 100kb threshhold for putting files into LFS at all
* a way of configuring this threshold

I followed up on that issue to ask for:
* user feedback when files are added to LFS, so users are aware when this is happening (addressed in https://github.com/SwissDataScienceCenter/renku-python/pull/1199) 
* UI in notebook launching config for letting users choose which files from LFS will be lfs-pulled (not addressed yet?)

This issue asks for:
* keep the default that everything goes into LFS, and pass in an option to TRY not putting it into LFS (like the thresholds, but requiring an action from the user), or an option to specify that it won't go into LFS (like -S)
