### ISSUE TITLE
core: update dataset model attributes

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1206]
Currently we have some attributes on dataset model which could be improved.

1) `name` could be renamed to `title` (since that's how it is used)
2) `creator` could be renamed to more specific name `creators` (and we can keep the RDF compatibility only on serialization phase)

**Comment by mohammad-sdsc** [comment]
* Rename `short_name` to `name`
* Remove `creator` from `DatasetFile`

**Comment by mohammad-sdsc** [comment]
Rename `created` to `date_created`
