### ISSUE TITLE
chore: improve UX on project initialization

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1219]
Currently, I find `renku init` user experience quite clunky and very hard to read. It would be great if we could improve that UX so it would be a bit more readable.

Here is how it looks at the moment:
![image](https://user-images.githubusercontent.com/1253355/80374753-76099480-8897-11ea-8091-57a2cf7582ef.png)

I would expect less text in the choice - if the text is really needed for some, we could create docs on the web explaining each template or use external `README.md` for such purpose.

**Comment by rokroskar** [comment]
I agree, this is definitely too verbose atm - I would probably only want to see "Basic Python Project" etc. and provide an option to give details if necessary.
