### ISSUE TITLE
A workflow to fix broken repositories due to large files in Git history

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1250]
As a Renku CLI user, I want to have a workflow that guides me how to fix a broken repository that contains large files in its history.

**Describe the solution you'd like**
- A command that migrates files to Git LFS and rewrites the history (see `git lfs migrate import`)
- All Renku-related metadata that use a commit hash should be updated with new commit hashes.
- Remote repo should be force-pushed.

**Describe alternatives you've considered**
A document that shows how to do the above steps.

**Additional context**
Related: https://github.com/SwissDataScienceCenter/renku-python/issues/467

**Comment by Panaetius** [comment]
Limited to new metadata, old metadata not supported. 

Also add how to do this manually to our docs, so users with older versions of renku can also do it themselves.
