### ISSUE TITLE
service: add support to work on specific branch

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1260]
Support for this functionality has been build in the core, but the service support for this is still missing. 

This ticket is about finishing that support in the service.

**Comment by Panaetius** [comment]
Not needed right now (currently functionality is enough at the moment from the UI side), we can pick this up at a later point in time.

**Comment by Panaetius** [comment]
We should add this to allow proper working on protected branches.

Currently, doing `datasets.create` on a protected branch will create a new branch, but then there's no way of adding files to the dataset created in that branch. The UI should be able to specify what branch to work on so they can keep the same automatically created remote across requests.

**Comment by Panaetius** [comment]
This was done with porcelain commands
