### ISSUE TITLE
service: finish documenting service diagrams

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1261]
Some work has been done last sprint with documenting service diagrams without a placeholder ticket for it so I'm just creating one here.

Once documentation diagrams for service have been merged we can close this ticket.

**Comment by rokroskar** [comment]
https://github.com/SwissDataScienceCenter/renku/pull/1089 hasn't been merged yet?

**Comment by jsam** [comment]
@rokroskar I have no idea how this got closed. Wasn't intentional, thanks for catching it.

**Comment by rokroskar** [comment]
no worries!
