### ISSUE TITLE
Lineage does not work when renku used on Windows

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#1262]
Our user reported that there's no lineage for https://renkulab.io/projects/lucien.oberson/datalakes_testrepo/files/lineage/scripts/Level0_1A/01A00001_LexploreMeteostation_v2.py. What I found is that commit activities for which `renku run` were issued are not of the `wfprov:ProcessRun` type which I believe they should.

Some investigation proved that there's clearly a problem with running `renku` commands on Windows. I run exactly the same commands in the same order as they were run originally [here](https://renkulab.io/projects/lucien.oberson/datalakes_testrepo) on a [new datalakes_testrepo repository in renku-kuba](https://renku-kuba.dev.renku.ch/projects/jakub.chrobasik1/datalakes_testrepo) and [lineage for the mentioned file](https://renku-kuba.dev.renku.ch/projects/jakub.chrobasik1/datalakes_testrepo/files/lineage/scripts/Level0_1A/01A00001_LexploreMeteostation_v2.py) is rendered correctly.

**Comment by Panaetius** [comment]
Use WSL: https://github.com/SwissDataScienceCenter/renku-python#windows
