### ISSUE TITLE
core: execute migrations after cloning of the project

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1295]
`project_clone` API should implicit trigger all migrations if they are need on the repository. This will alleviate necessity to run `renku migrate` after `renku clone` and help service to run operations on old projects without managing migrations.

Scope:
  * Invoke migrations in the end of the `project_clone`
  * Ensure that service is compatible and able to execute operations on non-migrated projects

**Comment by rokroskar** [comment]
I don't think we should migrate anything implicitly. We should have an endpoint that checks the project's version and whether or not it needs a migration - and provide an endpoint to do that migration. The UI should ping the endpoint to check if a project needs migrating and not allow `renku` commands until the migration is done.

**Comment by jsam** [comment]
@rokroskar That was my initial thought as well. But on second thought I think it makes more sense to run a migration right after cloning the project, because cloning a project into a cache which is unusable for all other operations requires a user to execute one more operation (which is not needed). 

Not so long ago I remember there was also a discussion on removing the migrate command and having migration being executed always if it's needed (that's why I wrote the ticket like this - I can update).

**Comment by ciyer** [comment]
There are a couple of problems with automatically migrating.

1. The migration might fail, but I might have something to do on the project and not have time to fix the failing migration right now. This is probably solvable.
2. People might be working in parallel, and everyone might not be on the same version of renku, and even if they are, it will be necessary to coordinate the migration to avoid painful merge-conflict resolution.

**Comment by jsam** [comment]
I see. I'm talking from the API/service perspective mostly.

1. I see this as a pretty solvable issue. The change which I'm suggesting above would affect `renku clone` command which would clone the project and make it usable immediately. If a migration fails (which should not happen and we should probably build a testing matrix for those things to at least have a minimal safety net for this), it can simply just reset the git and have non-migrated repository. Both of those things could help to address this issue.

2. From service perspective all users are on the same renku version which is being used (target version is the same). I'm probably missing the point. Could you please elaborate?  Is there a third case where we use `project_clone`?

**Comment by ciyer** [comment]
I am working on a project locally; my co-worker uploads a file to the dataset from the UI. If I understand the proposal correctly, my co-worker's action will cause the project to get migrated to the latest version of renku, which could cause problems for me when I pull or push.

**Comment by jsam** [comment]
Well, how is that different then now? In the current situation if your co-worker has version 0.10.4 he will have to migrate the repo to add the file anyway and when it pushes you will have to migrate if you want to do any operations.

**Comment by ciyer** [comment]
The difference is now, my coworker could contact me and say, "I would like to add a file to a dataset, I am using renku 0.10.4, and it says I need to migrate the repo to do this. Is this ok, or will this disrupt your work right now." In the proposal, this would all happen without my coworkers knowledge and therefore without an opportunity for us to coordinate.

**Comment by jsam** [comment]
How would he know that the migration is needed in this case?

**Comment by jsam** [comment]
Thanks for clarifying. I'll change the ticket into endpoint then and then from the UI perspective we can have matching ticket for adding a migration button.

**Comment by ciyer** [comment]
> How would he know that the migration is needed in this case?

IIRC, when I try to execute `renku dataset add` right now it says that you must first run renku migrate.

**Comment by jsam** [comment]
We should probably add a response on the service to detect this migration case easier, otherwise ui needs to string match the error. 

I'll create new tickets for this then. Thanks!

**Comment by jsam** [comment]
Followups: #1301 , #1302
