### ISSUE TITLE
move template responsibility to renku-python

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1306]
# Proposal: renku-python should be the source of base templates

## Background

We have had tons of issues with the renku project templates stored in an external repository. There are circular dependencies that manifest at release time and the templates can't be properly tested from the codebase. 

## Proposal

We should make this repository the "source of truth" for the base templates and the templates repository should be read-only. The CI in this repository should push a new version of the templates since those can serve as a starting point for others who may want to create their own. 

## Compatibility

Nothing should change for the consumers of the template repo, so this change should not cause any incompatibilities with other components. 

## Implementation

1. create a template directory as a resource in the current renku-python codebase
2. make tests that check whether e.g. a new project using this template passes `renku doctor` and `renku migrate` checks. 
3. make a CI job that pushes the contents of this template directory to https://github.com/SwissDataScienceCenter/renku-project-template keeping the template in-sync with the version of renku-python

**Comment by lorenzo-cavazzi** [comment]
Ok, so basically the release of a new template will be bounded to the release of renku-python.
If this helps in simplifying things, then... great! :tada:  

I'm not generally a supporter of having different resources in the same repo, this will make `renku-ptyhon` the repo for the command line tool, the core service _and_ the templates. But I guess there is nothing bad with it and it's really only a personal preference :slightly_smiling_face: 

:+1: for keeping the read-only template as a separate reference/source.

**Comment by Panaetius** [comment]
This is no longer needed with the template/docker update changes, right?

**Comment by rokroskar** [comment]
pretty sure that's true... but I've actually lost track of how the templates are handled now when the renku package is installed - are they copied into the installation so that it's not needed to ping github? Or is accessing github required for initializing a project?

**Comment by Panaetius** [comment]
They are copied into the package.
