### ISSUE TITLE
LocalClient should provide better error messages

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#1309]
# Description

The LocalClient can be use to introspect on the Renku repository. It needs to be initialized in the root of the repository, but if this is violated, use of the client fails with cryptic, unhelpful error messages.

# Solution

My suggestion is that LocalClient should check if the path argument contains a `.git` folder. If not, it should either:

1. look up the folder hierarchy and find a `.git` folder which becomes the path
2. throw an exception complaining that the path is not the root of a git repository.

I think 1. would be a little nicer, but 2. is a perfectly acceptable solution for me.

See https://renkulab.io/projects/cramakri/kg-reflection/files/blob/notebooks/Client.ipynb.

**Comment by Panaetius** [comment]
We're working on Renku as a Library that should be the thing users use to introspect a Renku repo. LocalClient is an internal thing that users shouldn't use directly/be exposed to
