### ISSUE TITLE
Unable to override input/output detection in renku run command

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#1321]
**Describe the bug**
The `renku run` command offers several ways of augmenting the inputs and outputs detected (explained here: https://renku-python.readthedocs.io/en/latest/commands.html#module-renku.cli.run), but these are only *in addition* to the what the CLI identifies. In some cases, though, the user may wish to *override* what the CLI has identified, and this is not possible. As a result some workflows cannot be executed with `renku run`.

**Link to project**

https://dev.renku.ch/projects/cramakri/output-detection-test

**To Reproduce**

[The above project](https://dev.renku.ch/projects/cramakri/output-detection-test) contains a notebook that has the following parameters:

- a data directory
- paths relative to the data directory for inputs

When run, the notebook writes a new output file to the data directory, where the inputs are also located.

Because the renku-cli identifies the data directory as an input, it thinks there is a circular dependency, even if the inputs and outputs are explicitly specified on the CLI or using the `.renku/temp/[inputs.txt, outputs.txt]` mechanism. See the project and the readme for details.

**Expected behavior**
I would expect there to be some way of bypassing the renku-cli's input/output detection logic. I think, it should work as follows:

if `--input` flags are provided, then the input detection logic should be bypassed; if `--output` flags are provided, then the output detection logic should be bypassed. Similarly, if a `.renku/tmp/inputs.txt` or `.renku/tmp/outputs.txt` file is provided, then the input, respectively output detection logic should be bypassed. There should be a flags `--append-inputs` and `--append-outputs` that can be provided to preserve the current behavior.

**Run environment (please complete the following information):**
 - renku-python version: renku0.10.4-0.6.3
 - Python version: python 3
 - renkulab
 - Chrome and Safari, Jupyterlab

**Additional context**

**Comment by Panaetius** [comment]
Should discuss design with @emmjab  and @ciyer  also with keeping the dataset as input issue in mind

**Comment by emmjab** [comment]
If I reach into my memory, this came from a user issue somewhere, right? Can we link it here?

**Comment by ciyer** [comment]
> If I reach into my memory, this came from a user issue somewhere, right? Can we link it here?

https://renku.discourse.group/t/passing-a-list-of-input-files-through-papermill/136/4
