### ISSUE TITLE
renku init behavior

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#1332]
**Is your improvement request related to a use case or a component design? Please describe.**
Sometimes users hesitate to start working with renku because they don't know what `renku init --force` will do to their repository.

In checking what we have in the docs, we don't outline the behavior anywhere, just explain that you can use this command if you have already initialized a git repository: https://renku-python.readthedocs.io/en/latest/commands.html?highlight=init#module-renku.cli.init

From testing things out, I've noticed the following from the current behavior:
`renku init --force` on existing repository:
- creates a branch with the pre-renku state (but doesn't tell you it's doing this)

```
 % renku init --force
  INDEX  ID              DESCRIPTION                                                                                                                     PARAMETERS
-------  --------------  ------------------------------------------------------------------------------------------------------------------------------  ------------------------------------------------------------------------
      1  python-minimal  Basic Python Project: The simplest Python-based renku project with a basic directory structure and necessary supporting files.  description: short description added at the beginning of the readme file
      2  R-minimal       Basic R Project: The simplest R-based renku project with a basic directory structure and necessary supporting files.            description: short description added at the beginning of the readme file
      3  minimal         Minimal Renku: The simplest renku project template with files for renku CLI and launching projects on renkulab.
Please choose a template by typing the index: 1
Initializing new Renku repository... OK

% git branch
* master
  pre_renku_init_e8d8bbe
```

- overwrites all pre-existing files with template content

- this includes the `.gitignore` --> so previously ignored files (e.g. data not tracked with git or git lfs) get committed into the repository if they're not in the template's `.gitignore` file.

I think as a first pass solution we can: 

* write docs for what the current behavior is
* include a message at the end of `renku init --force` that shows the other branch, in case users want to re-add their old README, Dockerfile, etc. content.

Maybe later:
* add more renku init from template UX -> e.g. we have `renku init -l` to list the templates; maybe we can add `renku init -l 1 --show-files` to see the list of the files that will be added
* have some kind of merge behavior for files that exist in the former repo and the template

**Comment by rokroskar** [comment]
I guess we should first fix the thing that is obviously broken (overwriting the `.gitignore` and potentially breaking the repo) - could we just append the two? Doesn't seem like that would hurt anything.

**Comment by emmjab** [comment]
Ah yeah -- I support append (or pre-pend of renku template content, maybe to make it more obvious that we added something if they `less` the file) for all of the template files and encouraging people to `git diff` at the end to see what we added. 

Only thing is if both they and us add (not the best example but:) `.ipynb_checkpoints` or something to the `.gitignore` and then they take theirs away but don't realize they need to take ours away then the file is still ignored. But i think it's low-risk.

**Comment by ciyer** [comment]
Alternatively, renku init maybe shouldn't make a commit in the force case because it makes it bit more work to find out what renku init did.

**Comment by ciyer** [comment]
The behavior of overwriting the README is wrong. I cannot imagine why anyone would want their existing REAMDE overwritten by the dummy readme of renku init. The README should be left unmodified.

**Comment by nperraud** [comment]
I believe this is a high priority issue. I just lost an hour because of this behavior. Especially the .gitignore part.
