### ISSUE TITLE
feat(service): add ability to work on non-cache based projects

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1334]
Currently, all commands which are exposed through service operate only on the projects which are in existing cache. This is not always necessary. 

For example: 

1) daemon mode could execute operations if the user cloned a project somewhere in the file system (this should support both read and write operations in daemon mode)

2) cloud mode could execute all read operations by looking into the metadata files which could be provided via URL (this should support only read operations, while write operations still require project to be cloned into a service cache)

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/1659
