### ISSUE TITLE
cli: renku dataset

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#1336]
## Describe the bug
Running renku dataset gives an error, and I think it is similar as this issue https://renkulab.io/projects/remko.nijzink/budyko

However, this dataset is not removed and should still work. It is also not nested or so, so I am not sure what is causing it. I can fix it in the way as mentioned in the other issue, but then this dataset is not listed anymore. I also want to keep this metadata if possible. 

## Details

**Renku version:** 0.8.3.dev23
**OS:** Linux (#201902061234 SMP Wed Feb 6 17:36:40 UTC 2019)
**Python:** 3.6.9

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/commands/client.py", line 103, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/core/commands/dataset.py", line 53, in dataset_parent
    missing_dataset, missing_files = check_dataset_resources(client)
  File "[...]/renku/core/commands/checks/migration.py", line 100, in check_dataset_resources
    relative = path.parent.relative_to(client.renku_datasets_path)
  File "[...]/pathlib.py", line 874, in relative_to
    .format(str(self), str(formatted)))
ValueError: '/home/remko/Documents/renku-projects/budyko/.renku/datasets/a7858ff4-562e-4ce8-87ea-3822e0737406' does not start with '.renku/datasets'
```

## Additional context
Related to https://renkulab.io/projects/remko.nijzink/budyko

**Comment by rokroskar** [comment]
Could you try updating to renku `0.10.4` and migrating the metadata?

**Comment by rcnijzink** [comment]
I think this was maybe also related to git-lfs, I can now run renku dataset again without problems. Renku migrate also says that there are no migrations required.

**Comment by rokroskar** [comment]
With a newer version of renku there should be migrations required. Feel free to close this if it seems resolved!
