### ISSUE TITLE
renku run fails when using pipes in commands

### ISSUE THREAD

**Issue by robinengler** [SwissDataScienceCenter/renku-python#1348]
Hi renku team,
I tried a couple of very simple bash commands with renku to test it. But it seems that each time a command has a bash pipe in it, renku run fails and complains about the directory being "dirty" when clearly it is not the case.

Here is an example:
```
# first we create a new directory to store the output:
mkdir data/outputs && git add "data/outputs/" && git commit -m "created outputs directory."
```

```
# make sure the repo is clean (no uncommited changes)
git status
On branch master
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)

nothing to commit, working tree clean
```

```
# Try to run a simple bash command with renku run:
renku run cat data/testDataset/continentSize.txt | sort -rn -k2 > data/outputs/continentSize_sorted_again.txt
Error: The repository is dirty. Please use the "git" command to clean it.

On branch master
Your branch is ahead of 'origin/master' by 4 commits.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        data/outputs/

nothing added to commit but untracked files present (use "git add" to track)

Once you have added the untracked files, commit them with "git commit".
```

If I now try an almost identical command, but without a pipe in it, it works as expected.
```
# almost same command without pipe:
renku run sort -nr -k2 data/testDataset/continentSize.txt > data/outputs/continentSize_sorted_again.txt
# ^ this works.
```

I tried a couple of other commands, and each time there is a pipe in it, it fails with the same message saying "Error: The repository is dirty." when it fact it's clean.

Here is a very simple reproducible example showing the problem:
```
renku run echo "foo bar" | sed 's@bar@foo@' > newFile.txt
```

Am I doing something wrong in my commands, or is this behaviour expected ?
Thanks,
Robin

P.S. From my limited testing, brackets in commands also have deleterious effects on renku run: the two commands below fail (with different errors).
```
renku run ( echo "foo bar" ) > newFile.txt
renku run cat <(echo "foo bar") > newFile.txt
```

**Comment by Panaetius** [comment]
Closed due to inactivity and since we don't plan on supporting pipes (and there's no clear direction on how we could support pipes)
