### ISSUE TITLE
renku dataset update doesn't see new files

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#1362]
**Describe the bug**
1. create project A & dataset A
2. create project B & import dataset A
3. add a file to dataset A in project A & git push
4. in project B run dataset update A => new file is not detected

Tried also for step 2 and on: 
2. create dataset A1, add (instead of import) data from project A as .git with --source path/to/data/folder
3. add file to dataset A1 in project A & git push
4. in project B run dataset update A1 => new file is not detected

Other notes: project A is public, project B is private.

**Link to project**
Can provide on request.

**Expected behavior**
Expected new file to be added to project B.

**Run environment (please complete the following information):**
- python interactive environments on renkulab

**Comment by emmjab** [comment]
This is not a bug, apparently! It's a new feature coming soon! I think this one? https://github.com/SwissDataScienceCenter/renku-python/pull/1331

**Comment by Panaetius** [comment]
Verify this works once we make a release with the new feature
