### ISSUE TITLE
Simplify interaction with service and remove necessity for clients to deal with cache management

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#1396]
[This is a template for Renku's change proposal process.]

# Proposal: Simplify project migration

Author(s): renku-ui team

Last updated: 2020-07-22

## Abstract

The current sequence of calls necessary to upgrade a project to a newer version of Renku is complex, error prone, and exposes unnecessary implementation details.

## Background

The current sequence of calls to migrate a project is as follows: 

* call `cache.project_list` to list projects in cache
* see if project is in cache, if not, call `cache.project_clone` to clone project
* get the `project_id` from the project in the cache
* call `cache.migrations_check` to check if the project needs to be migrated 
* if so, call `cache.migrate` to migrate the project

## Proposal

Desired sequence

* call `project.check_migration` with the GitLab project identifier (namespace/project slug) to check if the project needs to be migrated
* if so, call `project.migrate` to migrate the project

## Rationale

The desired sequence is easier for clients to follow and gives greater freedom of implementation to the service. If, for example, it becomes possible to check if the project needs to be migrated without cloning it, then the endpoint can be rewritten this way without any impact on the UI.

## Implementation

[A description of the steps in the implementation, who will do them, and when.
This should include a discussion of how the work fits into release cycle.]

## Open issues (if applicable)

[A discussion of issues relating to this proposal for which the author does not
know the solution. This section may be omitted if there are none.]

**Comment by rokroskar** [comment]
Why would you even need to call `project.check_migration`? The client should just call `project.migrate` and the service should determine if the project needs to be migrated and send the appropriate response.

**Comment by lorenzo-cavazzi** [comment]
The user may be browsing the project but not willing to update it. With the `check_migration` endpoint, we can verify the status and show the `Update Project` button when needed.

**Comment by jsam** [comment]
This ticket is related to #1334. Once that one is implemented you no longer will need to go through all this steps, but just simply do the request towards `cache.migrations_check` or `projects.migrations_check` (if you would like us to rename the endpoint) and you should get the requested information back.

**Comment by Panaetius** [comment]
We should use this issue to come up with a higher-level API where the core service manages the cache internally and clients don't need to worry about it.

e.g.
- on a request, we use (git_url, branch, user_id) tuple as the ID in the cache to check if a project is there
  * if it is not, we clone it and add it to the cache
  * if it is, we do a git pull to make sure the cache is up to date
- After this, actions execute as before on the cached project
- if we can't push due to the remote being a protected branch, we should add the new remote branch to the cache already so it's there for follow-up requests (instead of leading to a new clone)

**Comment by vfried** [comment]
Ralf, I really like your proposal.

Will this work with commits as well?

**Comment by lorenzo-cavazzi** [comment]
It would be great if `branch` could be any valid reference (i.e. branches, commits or tags), as in the `templates` APIs.
Maybe switching the name to `ref` or `reference` would be more descriptive in that case.

**Comment by Panaetius** [comment]
Will be implemented in https://github.com/SwissDataScienceCenter/renku-python/issues/1870
