### ISSUE TITLE
Single WorkflowRun without ProcessRun for updates/reruns

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1401]
On a (simple) `renku update`, our class structure looks something like this:

```
WorkflowRun ---association/plan--> Run
|                                   |
|                                   |
wasPartOfWfRun                   hasSubprocess
|                                   |
v                                   v
ProcessRun ---association/plan-->  Run
```

Since `WorkflowRun` and `ProcessRun` are there to track provenance, and `Run` is there to serve as a template/recipe for workflows, it does not make sense in this example to has the `WorkflowRun` wrap a `ProcessRun` for each subprocess in the template.

For provenance, we only really care what the inputs and especially the outputs of the `renku update` were, we don't need to have provenance for all the intermediary steps, since this all happens in a single commit anyways.

So to simplify things and make the distinction of provenance vs recipe/template more clear and meaningful, I'd propose to just do 

```
WorkflowRun ---association/plan--> Run
                                    |
                                    |
                             hasSubprocess
                                    |
                                    v
                                   Run
```

for `renku update`.

For `renku run` it'd be:

```
ProcessRun ---association/plan--> Run
```

This is enough to track provenance, still has all the information to track what happened, makes it easy to distinguish `renku run` and `renku update` (ProcessRun -> `renku run`, `WorkflowRun` -> `renku update/rerun`), then we don't need to check if a ProcessRun was part of a WorkflowRun and treat it differently and all these things.

It'd also simplify graph queries and presentation in the UI.

**Comment by rokroskar** [comment]
This makes sense to me - anything that makes the `WorkflowRun` more readable is a +1 in my mind.

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/1875
