### ISSUE TITLE
feat(service): move user identification completely to JWT

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1414]
Service currently uses several headers to determine users identity, and all headers are proxied from the gateway which leads to some unexpected encoding issues. This issue has been temporarily fixed, so the headers are now encoded into base64 and then decoded (if sent to the service as such) on the service.

To come up with more stable solution, we should move all those identity headers into a JWT and extract them from there. This issue should be synced with the gateway maintainers, since there are some open questions which we should flush out, like:

1) Can we trust the gateway for JWT verification?
2) Should JWT be used as Authorization header or do we want to move it into other possible locations like: `query`, `param`, custom `header`?
3) Should Gitlab token still be outside of the token and used as `Authorization`?

This ticket needs further design.

**Comment by rokroskar** [comment]
cc @ableuler @lorenzo-cavazzi

**Comment by jsam** [comment]
So I did a bit of research in the last parts and started with light refactoring which will enable us most of this.

1. I believe that the gateway should do the authentication and authorization and identification should only be part of all microservices which are behind the gateway. This means all of the services can trust the gateway to do all token verification which is needed.

2. We can use it as `Authorization` header, as long as we can handle Gitlab authentication token separately.

3. The reason why I believe the JWT token should not contain any sensitive access information from 3rd party systems is purely from a security perspective.

**Comment by ableuler** [comment]
I fully agree with @jsam 's findings here. The logical conclusion for me would be to include the keycloak `id_token` in the request. This does not expire and can't really be used for authenticating a request, but it allows the core service to identify a user and I guess that's what we want. I'd prefer to not use the `Authorization` header for this though as it suggests something about the content that it is not. Why not a custom request header?

**Comment by jsam** [comment]
Just one small note on this topic. With this change (and with remote repository operation change) we have the need to support anonymous sessions on 2 endpoints for the service. 

Those endpoints are:
1) list dataset files
2) list datasets

Not sure if there is a change needed on a gateway side to support this, so just pointing it out.
