### ISSUE TITLE
fix(core): project metadata updated/schema:dateUpdated field not getting set on update

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1418]
I've tried to address this problem in #1372 but due to quite challenging command lifecycle we have, this is turning out to be a bigger challenge than I expected. This ticket is about updating that field in project metadata every time renku project is meaningfully changed by renku commands.

**Comment by Panaetius** [comment]
Check with Kuba/UI if this is needed, otherwise remove instead of fixing

**Comment by Panaetius** [comment]
Removed in #1386 as this property is not used anywhere and it's not really useful to know when the metadata of a project was changed (rather, last commit on a project is interesting for UI purposes)
