### ISSUE TITLE
Reduce number of executed actions for pull requests

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1441]
When creating/modifying a PR, we run all tests in renku-python for three versions of python: 3.6, 3.7, and 3.8. This requires a large amount of resources and so far we did not have any incompatibility issues. A proposal is to test with python 3.6 on PRs to speed up the development and check against all three versions only on merges to `master`.

**Comment by Panaetius** [comment]
The only incompatibility issue I'm aware of is different ordering of dictionary entries on different python versions, which led to one or two issues in the past (e.g. processing A before B works but B before A doesn't), but that's not pressing enough to not do the suggested change. Running all on master should suffice for these rare cases.

We should test on python 3.7 on PRs, as that is what the default image on renkulab currently uses.
