### ISSUE TITLE
implement a `log` service endpoint 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1442]
# Proposal 

The renku core service should expose a `/log` endpoint that would take a project id and commit range and optionally the format. It should return the graph in the specified format. 

## Rationale

At the moment, the graph service triples-generator installs a version of renku-python and runs `renku log` for each new commit of projects it's monitoring. This is leading to dependency incompatibility issues, complicates deployments and requires the triples-generator service to implement a lot of ad-hoc logic to deal with some peculiarities of the KG building process. Instead, this should be done by the core service, since it's already using this code for other tasks. 

With the current changes in renku-python requiring migration of workflows etc. the generation of triples in the graph service is becoming incredibly slow. We can optimize this quite a bit if we do it "natively" in the python-based service instead. 

## Compatibility

Not much should change for the graph services - the TG should continue to receive events from GitLab and process them, but instead of shelling out to run `renku log` it will send the same information (project, commit range) to the service endpoint. (cc @SwissDataScienceCenter/renku-graph-maintainers )

It's likely that we will need a new/different/adapted middleware in the gateway for this endpoint. Since the request will no longer be coming from the UI there won't be a cookie - but the graph services already have knowledge of some user credentials so it should be possible to use those in this case. 

## Open issues (if applicable)

The addition of this endpoint will greatly increase the load on the core service. We will probably want to make horizontally-(auto)scalable pods of workers for this queue/endpoint in order to respond to load spikes. Since they will only be reading the repository and not performing any writes, it would be possible to avoid using the cache to make scaling easier (we cannot have multi-attach volumes with shared caches at the moment).

**Comment by jachro** [comment]
I quite like the idea as I see things becoming simpler and better structured in terms of responsibility. However, there are few things we’d need to consider/change before we do the switch:
1. Compatibility between renku python on the Core and TG - as of now, TG is quite tightly coupled to a certain version of renku-python as TG does not simply take the output of renku log and sticks in the Triples Store but curates it (e.g. adds info about project hierarchy, decouples Person object, adds additional data for dataset queries). For these TG has to know exactly what version of CLI is used as it has to know how to work and modify the data; Maybe assuring the versions compatibility on the deployment process is good enough?
2. Migrations - at the moment TG can work with projects in any version as it runs the migration by itself and does not push the changes back to the repo. Do we think migrations should happen automatically without explicit user intervention? Or maybe we’d like to expose an endpoint on the Core which could take CLI version as an input when generating triples and effectively do `renku migrate` and `renku log` using that version? Would make this single endpoint a bit inconsistent with the rest which simply fails when a project is not migrated?
3. Performance - definitely the auto-scaling feature is worth exploring and could be a nice way to go. For the time being, we could try to manage the number of Core instances manually. Currently, all scales automatically with every instance of TG we add or take. There were few empiric exercises done to come up with some figures that make things working relatively well (I think here about the number of concurrent processes, GitLab API throttling). A possible easy option could be also throttling requests to the Core on the TG instances. Another thing to remember is that Core service is serving interactive user requests and the current TG set-up could simply drain Core service completely and make UI a bit unusable. What we could maybe do is to have two sets of Core services one for the UI and one for TG.
4. Recovery from failures - there are certain rules on TG to classify specific errors happening during git and renku calls. These rules put events to either RECOVERABLE (retry-able) or NON_RECOVERABLE buckets; Do we want to move them these rules to the Core and agree on response types so TG can do the classification based on that? Does it make sense for general purpose Core endpoint for `renku log` to run such rules? Or maybe the new endpoint would simply pass all the failures as they are from git and renku calls back to us? Would that makes sense that the endpoint returns back an error about an internal call to `git clone` to the caller of the log endpoint? It doesn't sound like a good practice.

As I said we quite like the idea as it would make our life easy but the triples generation process is more and more in the heart of Renku so we have to assure at least the same level of robustness we've got now. I really like we go that way but I don't think this is a trivial switch and we have to plan carefully.

**Comment by rokroskar** [comment]
Thanks @jachro - your points make a lot of sense. Some quick thoughts:

1. ideally, we could implement the graph model in a way that would require less curation of triples that are produced by `renku log`. On the other hand, some KG curation/cleanup is inevitable and we'll require this more and more (e.g. for removing orphan nodes). For this, though, I think the responsibility should not be on the triples generation process but instead in a dedicated service that has a clear mandate to keep the KG nice and tidy. It would be much clearer then also what exactly is happening - right now this process is very hidden and quite a big (important) black box from the outside. If it were a separate service it would be much easier to instrument and monitor for potential issues. In terms of compatibility we should not work with renku-python version compatibility but with the shacl definitions instead. The version of the service or renku-python may need to get updated and changed and we shouldn't need to always repackage and redeploy the entire graph stack. For this, I would make the services do a simple KG shacl compatibility check at startup. 

2. we can continue handling migrations similarly to what is currently done in the TG. However, with the migrations becoming increasingly user-friendly I think this will be less and less of an issue. 

3. yes, completely agree about not wanting to drain the core service that is serving the UI. This is why I suggest that we create a separate deployment for the graph generation with its own pool of workers. 

4. I think the error tracking/retry logic you have now in the TG should stay. The log endpoint could adopt the same terminology and categorization without returning the details of the failure. I think it's generally useful to tell a generic client "we encountered an error, but we think it might work if you try again later" rather than simply failing. Why don't you think that's a good practice?

**Comment by jachro** [comment]
So:

1. Once we take out the responsibility of generating triples from the TG, then TG becomes the service you mentioned. Or, from a different side, I think you could misunderstand the nature of the curation process. Effectively, the curation process operates on JSON-LD rather than triples in the Triples Store. The idea here is that the Store gets valid data structure instead of a raw JSON which gets fixed in some post-insert process. I think we have to do our best to assure the Store is in a valid state all the time otherwise we could end up in a situation when at least some of the queries do not work.
4. We believe the categorization rules belong to more to TG than the Core as they very triple generation centric. The worry we have is that the TG rules (responsibility to assure the Triples Store is in the best shape) leak out to the Core and adding/changing them will require changes to the Core.

**Comment by rokroskar** [comment]
OK so basically we're back to my initial proposal which was to just remove the shell out to `renku log` from the TG and keep everything else the same - no?

**Comment by jachro** [comment]
I think you are right. If we'd simply create an endpoint on the Core doing `renku log` and eventually `renku migrate` (only if needed without pushing the migration commits back to the project repo) we should be fine. So looking from the perspective of the points I listed above we could maybe do this:
1. If we'd maybe expose one more endpoint on the core (maybe even `GET /status` could be ok for that) which returns info about the current version of Renku CLI we could use that info to act properly and eventually trigger re-provisioning if the version is changed.
2. It'd be covered if the new, let's say `GET log` endpoint, does the migration if needed.
3. As mentioned two sets of dedicated workers could do the job. Definitely seems to be a good starting point.
4. After some thinking, I reckon your idea about moving the failures classification rules we've got now on TG side to the new log endpoint could be a way to go. We can extract these rules and add them to some relevant issue. At that moment we can agree on the details how the endpoint will be reporting that info back to us.

Would that all make sense?

**Comment by rokroskar** [comment]
This makes sense to me - I guess the only sticky point are the failure "bins" but I think those are generic enough that they are useful for any client using this API not just the TG. 

@jsam any thoughts on the above?

**Comment by jsam** [comment]
@rokroskar Yes, I wrote some thoughts now in two places - so let me try to summarize. 

I agree and it does make a lot of sense, however, I do believe that before we tackle this we should sort out underlying stuff to make it happen (see comment @ #924). I believe that for all read operations on the core, we should not have a hard requirement that we bring the project to the latest version (and commit the migrations). This means that `renku log` endpoint should work on all previous versions, and the core module should be flexible enough to support this.

@jachro Yes.

1) That information is already there on the migrations check endpoint, we can move it on its own endpoint as well.
2) Yes, however, I believe we should refactor migrations before we tackle this.
3) Absolutely.
4) Seem's like a good approach but I'm not understanding the full scope of this, so can't say more.

**Comment by jachro** [comment]
I've just walked through the current triples generation process and compiled a list of relevant cases with recovery strategies (at the end it doesn't look that bad - sorry if I sounded scary in my previous comments ;)

| Step | Failure | Recovery |
|------|---------|----------|
| Preparing the clone | No user access token available | Event sent back to the pool |
| git clone | Command fails with message containing "SSL_ERROR_SYSCALL" or "the remote end hung up unexpectedly" | Event marked as Recoverable |
| Checking the commit | Commit message contains "renku migrate" | Event marked as Skipped |
| renku log | Command fails with message containing "Not enough memory" | Event marked as Recoverable |
| renku log | Operation takes more than 1 hour | Event marked as Non Recoverable |
| any | any | Event marked as Non Recoverable |

I believe these shouldn't be that difficult to implement on the new endpoint. We simply have to agree on the way these will be reported back to us.

The rules were collected as part of https://github.com/SwissDataScienceCenter/renku-graph/issues/364

**Comment by jachro** [comment]
In regards to the flow, would it be possible that triples-generator calls a relevant endpoint on the Core service passing payload containing more or less these properties:
```json
{
  "project-path": "namespace/.../project-name",
  "commit-id": "a25b6a5806cfe14eae093d783c29e62fcd08b9a1",
  "schema-version": "5",
  "callback-url": "http://renku-triples-generator:9002/triples/<project-path>/<commit-id>" // a complete URL will be passed to the Core service so it doesn't have to resolve any placeholders
}
```

On the triples-generator side, a new endpoint will be added (see `callback-url` in the example above) so the Core can send the triples when they are ready:
* success case:
```json
{
  "status": "success",
  "payload": "json-ld as string"
}
```
* recoverable failure case:
```json
{
  "status": "recoverable_failure",
  "message": "reason for failure"
}
```
* non-recoverable failure case:
```json
{
  "status": "non_recoverable_failure",
  "message": "reason for failure"
}
```
