### ISSUE TITLE
tests: simulate user behaviour to check renku run/update

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#151]
Starting idea:

- [ ] create a fixture that generates Renga repository based on "realistic" user behaviour
- [ ] generate a sequence of file changes and `renga update` commands

---
https://github.com/SwissDataScienceCenter/renga/issues/146

**Comment by rokroskar** [comment]
@jirikuncar is it still the plan to implement this?

**Comment by jirikuncar** [comment]
Yes, when the time allows.

**Comment by rokroskar** [comment]
Closing - not clear what was meant/needed here anymore.
