### ISSUE TITLE
Explicit management of workflow templates

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1553]
As a Renku user, I want to manage workflows explicitly in a Renku project to have more control of what is being executed or updated.

**Context**
Each `renku run` command creates a workflow step along with its execution information and stores them in the project's linage. Since workflow steps are embedded in the linage, they remain forever in the project and there is no straightforward way of removing or modifying them. Moreover, to visualize the workflows, users need to look at linage of files and directories which might not show all the workflow-related information at once.

**Describe the solution you'd like**
In https://github.com/SwissDataScienceCenter/renku-python/issues/1037, we separated workflow executions from workflow templates; this story is moving one step further to decouple templates from lineage and to enable modifying/deleting those templates. We can store these templates in a separate data structure (a Dependency Graph) which then allows to modify them without losing/modifying the lineage. `renku update` command should use this graph to decide which steps to execute instead of building a lineage graph. 

**Acceptance Criteria**
* Each workflow step must be abstract without providing specific versions for inputs and outputs
* Arguments values must be part of the execution; template only stores argument names and their default values (values at time of creation)
* Each workflow should have a unique human/CLI-friendly name for easier reference. A default name should be generated when user does not provide one and for the existing workflows.
* Users should be able to view/delete/rename workflow steps.
* Deleting workflow steps must not change lineage for existing executions of those steps.

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/1875
