### ISSUE TITLE
Requests to knowledge-graph to be going through the Gateway

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#1555]
As a Renku maintainer, I'd like all the REST requests to the knowledge-graph API to be going through the Gateway rather than directly hitting knowledge-graph service. The reason for that is once the https://github.com/SwissDataScienceCenter/renku/issues/1533 is done, knowledge-graph API would require authorisation for all non-public projects so CLI wouldn't be able to fetch dataset information from the service if no access token is present.

Could someone please link the CLI authorisation issue here?

**Comment by lorenzo-cavazzi** [comment]
Renku-gateway now supports this. You can route all your requests for the knowledge-graph through the `/api/kg` route.

**Comment by Panaetius** [comment]
This was implemented with `renku login`
