### ISSUE TITLE
Avoid walking the whole git history to generate provenance graph

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#1558]
Renku workflow and dataset metadata files have all the required information to display linage for user data and code files that are used/generated by Renku. Traversing git commit history is not required if we are interested only in lineage for those files.

**Notes**
* Parts of Renku metadata won't show up in lineage (e.g. initial sets of files in a project)
* Changes that users make in the data files won't show up in lineage unless they are used in workflows or added to datasets

**Comment by Panaetius** [comment]
@mohammad-sdsc this can be closed, right?

**Comment by mohammad-sdsc** [comment]
Right.
