### ISSUE TITLE
Migration problem on old project

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1583]
Migrating https://renkulab.io/gitlab/Red-Team/dogs results in invalid metadata.

- doing a plain `renku log --format json-ld` fails due to an error in datasets
- Migration of `.renku/workflow/72baed44d9c641b986532ff1cb0b4bc6_papermill.cwl` yields a project node that has two creators, due to flattening. This is likely due to the project using submodules (Rok created the parent project and Luis created the submodule project, and we see both as creator on the project node)

**Comment by rokroskar** [comment]
Oh wow! that is ancient!

**Comment by Panaetius** [comment]
Submodules create these kinds of problem in general (like duplicate `created` dates etc.). It is safe to say that we currently do not support submodules if the submodule is also a renku project.

The bigger question here is, if we should support that? I don't think it'd be trivial to handle with the way `LocalClient` works
