### ISSUE TITLE
cleanup IT repo

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1613]
https://dev.renku.ch/gitlab/renku-qa/core-integration-test has tons of branches due to integration tests running. 
This slows down KG re-provisioning on DEV when testing. It'd be nice if we could cleanup the branches automatically after the test or on a regular basis (Every Sunday?).

**Comment by jsam** [comment]
I'll add this to the next milestone and assign it to myself. The cleanup job has been added here: https://dev.renku.ch/gitlab/renku-qa/core-integration-test/-/commit/2a82355b283ea17279144d15c3c76b80d8f727b9, but I would like to keep an eye on it for the next couple of weeks to see if there will be any additional problems with it. I can close this ticket once I can vouch that there are no problems.

**Comment by jsam** [comment]
Ok, I reworked a bit the job so each invocation of the job would delete branches in batches making the whole thing much faster. The job is scheduled every day at 0200AM. I haven't noticed any big problems with this, but if we need to run the job multiple times a day we could add an additional schedule.

Job example: https://dev.renku.ch/gitlab/renku-qa/core-integration-test/-/jobs/117943

I'm closing this ticket, if we notice any additional problems we can reopen this ticket.
