### ISSUE TITLE
Standardize error responses from core service

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-python#1616]
The error response we get when invoking the core service APIs with invalid parameters has different formats for the `reason` field, making it hard to give appropriate feedback to the user.

An example is the `templates.read_manifest`. The base response structure is
```
{
  error: {
    code: <int>
    reason: <?>
  }
}
```

The `reason` type and format vary based on the `url` parameter provided
* "https://github.com": `reason: "\"https://github is not a valid Git remote."`
* "https://github.com/SwissDataScienceCenter": `reason: {"owner":["Field may not be null."]}`
* "https://test.com/test2/test3": `reason: "git error: stderr: 'Cloning into '/svc/cache/projects/a0b2f901-db6b-4edb-9bba-f96eb76db313/test2/test3'... warning: redirecting to https://www.test.com/test2/test3/ fatal: https://www.test.com/test2/test3/info/refs not valid: is this a git repository? '"`

The inconsistency here is in the type of the response (object vs string) and in the content (custom message vs git message vs renku internals message). The type should be easy to address, while the content may not be that straightforward.

I believe receiving errors about the renku internals is not useful and confusing (second response, I don't know what an `owner` is).
Having a user friendly message (as in the first response) would be the ideal solution (there is an extra `\"` though). As a fallback, the git error is ok (as in 3rd response).
Nice to have: distinguish between human readable error message and inherited error message. The inherited should always be available and go to `message`, while the human readable goes to `reason`.

**Comment by jsam** [comment]
Thank @lorenzo-cavazzi for reporting the issue. I'll look into this next sprint and improve those cases you mentioned, if there are some additional cases you think of, please do let me know.
