### ISSUE TITLE
renku dataset add hangs on large number of files

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-python#1632]
**Describe the bug**
`renku dataset add mydata path` hangs indefinitely if the total number of characters of all the filenames (in the path) concatenated is more than what renku can handle.

**To Reproduce**
1. You must have a data folder containing many files - pathnames, and file sizes don't matter but total length of all pathnames concatenated must be more than 65k.
2. Cd to renku project
3. Create a renku dataset
4. Add the data folder to the dataset
5. Renku hangs

**Expected behavior**
At a minimum I would expect at least an error and the command should stop right away. Ideally, it should be able to handle this use case and add the files without hanging.

**Screenshots and/or execution output**
> $ pstree -u eric -p
screen(20692)───bash(20693)───renku(25097)─┬─git(25144)
                                           └─git(25218)───git-lfs(25219)─┬─{git-lfs}(25220)
                                                                         ├─{git-lfs}(25221)
                                                                         ├─{git-lfs}(25222)
                                                                         ├─{git-lfs}(25223)
                                                                         ├─{git-lfs}(25227)
                                                                         ├─{git-lfs}(25228)
                                                                         ├─{git-lfs}(26118)
                                                                         └─{git-lfs}(26119

> $ ps -Lmfu eric
UID        PID  PPID   LWP  C NLWP STIME TTY          TIME CMD
eric     20692     1     -  0    1 Oct17 ?        00:00:05 SCREEN -R -t moby -S moby -O
eric         -     - 20692  0    - Oct17 -        00:00:05 -
eric     20693 20692     -  0    1 Oct17 pts/3    00:00:04 /bin/bash
eric         -     - 20693  0    - Oct17 -        00:00:04 -
eric     25097 20693     -  0    1 01:58 pts/3    00:00:43 /home/eric/.local/pipx/venvs/renku/bin/python /home/eric/.local/bin/renku dataset add moby-dat1 ./da
eric         -     - 25097  0    - 01:58 -        00:00:43 -
eric     25144 25097     -  0    1 01:58 pts/3    00:00:00 git cat-file --batch-check
eric         -     - 25144  0    - 01:58 -        00:00:00 -
eric     25218 25097     -  0    1 01:59 pts/3    00:00:00 git lfs track -- ./data/aaaa.csv ./data/aaab.csv ...
eric         -     - 25218  0    - 01:59 -        00:00:00 -
eric     25219 25218     -  0    9 01:59 pts/3    00:00:08 /usr/bin/git-lfs track -- ./data/aaaa.csv ./data/aaab.csv ...
eric         -     - 25219  0    - 01:59 -        00:00:00 -
eric         -     - 25220  0    - 01:59 -        00:00:00 -
eric         -     - 25221  0    - 01:59 -        00:00:03 -
eric         -     - 25222  0    - 01:59 -        00:00:00 -
eric         -     - 25223  0    - 01:59 -        00:00:01 -
eric         -     - 25227  0    - 01:59 -        00:00:01 -
eric         -     - 25228  0    - 01:59 -        00:00:00 -
eric         -     - 26118  0    - 03:43 -        00:00:00 -
eric         -     - 26119  0    - 03:43 -        00:00:00 -

> $ sudo strace -p 25220
strace: Process 25220 attached
restart_syscall(<... resuming interrupted futex ...>

> $ strace: Process 25221 attached
futex(0xc420032910, FUTEX_WAIT, 0, NULL

> $ strace: Process 25222 attached
futex(0xd55b80, FUTEX_WAIT, 0, NUL

> $ strace: Process 25223 attached
write(1, "Tracking \"data/aaaa.csv "...

> $ strace: Process 25227 attached
futex(0xc420314510, FUTEX_WAIT, 0, NULL

> $ getconf ARG_MAX
2097152

**Run environment (please complete the following information):**
 - renku-python version 0.11.5
 - Python version 3.8
 - local terminal 
 - ubuntu

**Additional context**
From pstree/ps/strace/gdb it looks like it's hanging on the git lfs track command with a long command line containing all the file names. I tried on 26 folders, and it only happens for folders where all the file names concatenated exceed 65k.

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/1945
