### ISSUE TITLE
Overwrite default commit when adding files in bunch to renku 

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-python#1633]
**Is your feature request related to a problem? Please describe.**
`renku dataset add` on a folder automatically commits the updated dataset, with a commit message that list all the files in the folder. We don't have the option to edit the commit.

If the folder contains many files, the commit message can be very long and break the image build with an `argument line too long` error.

I also suspect that it slows down the jupyterlab interface, in particular its git plugin.

**Describe the solution you'd like**
I'd like a `-m` option that allows me to overwrite the default commit message.

If the option exists, it should be documented in the `renku dataset add --help`.

**Describe alternatives you've considered**

* Renku should by default complain and ask me if I want to edit the commit if it exceeds a reasonable size unless I specify a _batch_ mode option.

* If we really want to keep the long commit message, we could append the longer message to our own log file and cross-reference it with the git logs (e.g. using commit IDs). At least that would isolate those long messages from the git log, so that they don't break the build or cause other issues.

**Additional context**

At the moment I must either add the file one at the time, which is very slow, or tune the command in order to add the files in larger batch while respecting a reasonable commit size, or rebase/amend and reword the commit messages.

**Comment by mohammad-sdsc** [comment]
Make sure that this gets fixed everywhere in the code that we add data to git.

**Comment by Panaetius** [comment]
on a side note, if you do `renku dataset add folder` instead of `renku dataset add folder/*`, you don't have this problem, you get a commit message like ` renku dataset add test_set folder/`
