### ISSUE TITLE
bug: file structure lost when importing dataset

### ISSUE THREAD

**Issue by TaoSunVoyage** [SwissDataScienceCenter/renku-python#1634]
**Describe the bug**

The file structure is lost when I import dataset from another repo.

**Link to project**

Private repos.

**To Reproduce**

There are two repos, _Repo_A_ for managing the dataset, _Repo_B_ for processing the dataset.

What I have in _Repo_A_:
```
data/MY_DATASET
`-- SUB_FOLDER
    |-- file_1
    |-- file_2
    `-- ...
```

How I add data into the dataset in _Repo_A_:
```bash
renku dataset add MY_DATASET data/MY_DATASET/SUB_FOLDER/*
```

How I import data in _Repo_B_:
```bash
renku dataset import RENKU_DATASET_URL
```

What I get in _Repo_B_:
```
data/MY_DATASET
|-- file_1
|-- file_2
`-- ...
```

**Expected behavior**
I would like to see in _Repo_B_ the same file structure as in _Repo_A_:
```
data/MY_DATASET
`-- SUB_FOLDER
    |-- file_1
    |-- file_2
    `-- ...
```

**Screenshots and/or execution output**
See above

**Run environment (please complete the following information):**
 - renku-python 0.10.4
 - Python 3.7.6
 - renkulab.io
 - Jupyterlab & Firefox

**Additional context**
--

**Comment by mohammad-sdsc** [comment]
I believe this is already fixed in https://github.com/SwissDataScienceCenter/renku-python/pull/1576. Just check to be sure.

**Comment by Panaetius** [comment]
Just tested with 1.0.2 and everything works as expected, closing this issue.
