### ISSUE TITLE
feat(core): project_clone v2

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1647]
Currently, we have several ways with which we are cloning a project and some of the approaches don't have support for internal/private projects. The reason being is that not all project clones we do (in the core on the provider level and in the service) are not always using the `project_clone` core method. The current version is a bit limiting for all the cases we need and the way it handles the clone itself could be improved so we increase the safety of token management.

This ticket is about incubating the project_clone command with this new builder structure and new logic. The new logic comes from the new way of handling project clones in the interactive environments and it is equal to the following:

```
mkdir myproject && cd myproject
git init
echo https://oauth:{IT_TOKEN}@dev.renku.ch/gitlab/renku-qa/core-integration-test.git > .git/credentials
git set remote origin https://dev.renku.ch/gitlab/renku-qa/core-integration-test.git
git pull origin master
```

This way, the remote is clean (without a token) and we can ensure that any git exception which can bubble up does not have the token itself. Once the new `project_clone` is incubated, we should open a follow-up ticket to replace the current behavior in all places: 
   1) Renku Provider (currently does not fully handle internal/private project) - #1113 should be possible after implementing this ticket
   2) `user_project_clone` on the service
   3) `project_clone` v1

**Comment by Panaetius** [comment]
Supersseded by porcelain changes
