### ISSUE TITLE
Makefile should respect PLATFORM_VERSION

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#168]
the main renku `Makefile` uses `PLATFORM_VERSION` as the image tag -- we should respect this in this `Makefile` for consistency when the renku `Makefile` is used to build images for the whole platform.

**Comment by jirikuncar** [comment]
A consistency is important, but we should probably look for some better name that would suit both `renku` and `renku-python` repositories.

1. simple `VERSION` may conflict with other packages;
2. `DOCKER_LABEL` is descriptive, but maybe `DOCKER_TAG` could work even better;
3. `RENKU_VERSION` is related to the package name;
4. `PLATFORM_VERSION` is very generic.

**Comment by rokroskar** [comment]
I think of these, `DOCKER_TAG` might be the most obvious and require least explanation?

**Comment by rokroskar** [comment]
this is made obsolete by https://github.com/SwissDataScienceCenter/renku/pull/382
