### ISSUE TITLE
renku save does not commit / push a staged file

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1692]
I'm actually not sure if this is a feature or a bug, but I would expect this to result in my changes being pushed to the remote:

```
# in a renku project
echo "pandas" >> requirements.txt
git add requirements.txt
renku save
```

Instead it results in 

```
There were no changes to save.
```

**Comment by Panaetius** [comment]
What would your desired behavior be?

`renku save` has a `paths` argument, so in cour case, you should do `renku save requirements.txt`.

What should happen when 
```
$ git add somefile
$ renku save anotherfile
```
?

I think that it should throw an error that there are staged changes already that are not included in the `renku save` command. And to either pass that path to `renku save` as well or how to unstage the file.

If it is called without a path, it should just commit and push as if the file was not staged (following the semantics of "`renku save` saves everything")

**Comment by rokroskar** [comment]
yes exactly - I think what's confusing now is that it saves everything except for when I have something staged. If I provide more details to the command and those details don't make sense it should complain.
