### ISSUE TITLE
feat(core): allow users to associate an image with a dataset

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1707]
The UI would like to be able to show an image in dataset listings/details, helping to make the dataset UI more visually pleasing and usable.

We can use https://schema.org/image to store this.

An open question is how to store this. Ideally we'd store it as an URL to the image in the repository, but that might need some path rewriting to display properly in the UI.

We should discuss which format makes the most sense for both teams, and how a user would set and/or change this, both through the cli and through the core service.

**Comment by Panaetius** [comment]
Check if Zenodo/Dataverse support this and how they use it.

Check with the UI how they could access this file for display.

**Comment by Panaetius** [comment]
Design Discussion Writeup:

We enhance dataset metadata with a `schema:image` field that contains a URI to an image.

This can be a plain URI to a stock image, external image or the IRI of a file inside the dataset.

Right now, IRIs for dataset files look like `https://dev.renku.ch/blob/f3dc02a1b57e8702e13880e0f388c2bcab6bd291/data/parrot-king/The_Parrot_King__Audubon.pdf`, which unfortunately is not resolvable (We have plans to make those resolvable in the future), but this means right now we would use a URI like https://dev.renku.ch/projects/cramakri/dataset-test-project/files/blob/data/parrot-king/The_Parrot_King__Audubon.pdf which is resolvable (Just with actual images, of course, not pdf's 😄 ), with either special headers or appending `?raw` to the URI to just get the content of the file. That way it can be easily displayed in the UI.

On the renku-python side: 
- Add an endpoint to set/change `schema:image` in the dataset to such an URL (or list of URLs, to support multiple images associated with a dataset, with the first one being what gets shown in the search results).
- Change the URL in the dataset metadata if a dataset file gets changed/deleted, if that file is used as an image. This should allow using dataset files generated by workflows in the future.
- Potentially also support uploading an image by combining `datasets.add_files` with this new endpoint to streamline the process.
- Make sure the image doesn't exceed a certain size (100kb, something like that) and maybe also resolution (128x128 or 256x256 or 512x512?).

On the UI:
- Display this URL from KG data, on search results and dataset details page.
- Add a UI to: (1) Pick a stock image, (2) select (or upload? see above re combined endpoint) a dataset file as image, (3) add an arbitrary URL to some external image.

What's still open for discussion is, if this is only a UI thing or if a user can also set this via the CLI, when working in a local project for instance. If we opt to do this, we'd additionally need:

On renku-python:
- The command to set/change this in the CLI.

On the KG/renku-python:
- changing this URL on triples generation to the correct URL for the respective instance of renku (e.g. https://localhost/projects/cramakri/dataset-test-project/files/blob/data/parrot-king/image.png to https://dev.renku.ch/projects/cramakri/dataset-test-project/files/blob/data/parrot-king/image.png).

**Comment by ciyer** [comment]
I think it is enough if you add to the dataset metadata a `schema:image` field that holds a URL. 

* You do not need to validate it or check its size or anything
* I do not think we need a new endpoint -- we can just add this feature to the existing endpoints for creating and modifying datasets
* You do not need to change the URL if the file gets changed. The user is responsible for ensuring that the URL is valid, and the UI will display a specific image if the URL does not resolve.

**Comment by Panaetius** [comment]
Kickoff Results:

`datasets.create` and `datasets.edit` can pass along a new parameter
```
"images": [
    {
        "content_url": "...absolute or relative url...",
        "file_id": "...id of a cache.file_upload...",
        "position": integer
  }
]
```
with either `content_url` or `file_id` being set.
and they get back this new property in `datasets.list` like
```
"images": [
    {
        "content_url": "...absolute or relative url...",
        "position": integer
  }
]
```

In the case of an absolute URL, the core service just passes this along.
In the case of a relative url (path inside the repo) or if file_id is set, the file(s) is copied to `.renku/datasets/<UUID>/images/` and the `content_url` set to this new relative path.

In the JSON-LD metadata, this takes the form of
```
"http://schema.org/image": [
    {
         "@id": "<dataset_id>/images/<relative_path>",
         "@type": "http://schema.org/ImageObject",
         "http://schema.org/position": integer,
         "http://schema.org/contentUrl": "relative or absolute url"
    }
]
```

When importing a dataset, the `.renku/datasets/<UUID>/images/` entries for the dataset are copied as well to keep things consistent.

If the relative path points to a file on lfs, that file is pulled before being copied to the `.renku/datasets/...` folder so it does not end up in LFS.

When exporting a dataset with the image property set to a relative path, we warn the user that this won't be exported -> https://github.com/SwissDataScienceCenter/renku-python/issues/1840

If we see performance with this approach being bad, we should move ahead with https://github.com/SwissDataScienceCenter/renku-python/issues/1841 

Adding/reordering/removing dataset images creates a new version of the dataset with a new id, following regular dataset immutability semantics.

**Comment by vfried** [comment]
Shall we create an issue for the import? 

"When importing a dataset, the .renku/datasets/<UUID>/images/ entries for the dataset are copied as well to keep things consistent."

**Comment by vfried** [comment]
All looks good to me. I like the idea of using the ImageObject since it will give us the possibility of adding new fields to the image in the future, like description or thumbnail.

**Comment by vfried** [comment]
We should create issues in the KG repository so that we get this field when accessing datasets through it

**Comment by Panaetius** [comment]
> Shall we create an issue for the import?
> 
> "When importing a dataset, the .renku/datasets//images/ entries for the dataset are copied as well to keep things consistent."

I think I can do this as part of this ticket (And I'd rather not delay it to some future point so we don't end up with broken imports in the meantime)

**Comment by ciyer** [comment]
This looks good to me as well. I concur with Virginia's opinion -- using ImageObject is a good way to go.
