### ISSUE TITLE
parallelize tests using self-hosted runners instead of pytest-xdist

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1713]
pytest-xdist is very unreliable for our tests. Instead, we should split up our test jobs more and add more self-hosted runners, and use those to run tests in parallel (but single-threaded on each runner).

So we need more jobs like `test-linux-cli`, `test-linux-core`, `test-linux-service` by plitting those up further.

How to use self-hosted runners can bee seen in https://github.com/SwissDataScienceCenter/renku-python/pull/1446

Self-hosted runners are in the `Github Actions` namespace on switch-zh-dev cluster, it can be scaled up using the https://github.com/SwissDataScienceCenter/self-hosted-runner-chart/tree/master/sdsc-github-action-runner chart.

This does not work for MacOS, since we don't have macos runners. We should switch macos tests from being parallel to prevent failures there. We could also only test on python 3.7 on master/tag to speed up things?

**Comment by rokroskar** [comment]
Can the runner be auto-scaled?

**Comment by Panaetius** [comment]
i don't see why not but we'd need to add support for it

**Comment by rokroskar** [comment]
I guess my question was: is there anything unique in each instance of the runner? If not, adding autoscaling is trivial

**Comment by Panaetius** [comment]
No there's nothing unique, it's just a plain container https://github.com/SwissDataScienceCenter/self-hosted-runner-chart/blob/master/sdsc-github-action-runner/templates/deployment.yaml#L17

Id's and things are auto-generated on startup inside the container.
