### ISSUE TITLE
support renku clone over SSH

### ISSUE THREAD

**Issue by rollicks-c** [SwissDataScienceCenter/renku-python#1715]
**feature (problem related)**
If you join renku using a auth provider such as SWITCH edu-ID or GitHub, you most probably won't have set a password in your renku gitlab account. If you then try to clone a renku project using `renku clone` you'll receive a generic exception with a long stack trace.

**Describe the solution you'd like**
I think the failed `renku clone` command should provide a clean error message, similar to the one you get by using "git glone".
Irregardless of this, I think the default way to access git repositories should be SSH not HTTPS. Unfortunately the `renku clone` command seems not to support git clone via SSH. 

**Describe alternatives you've considered**
The current workaround is to not use renku cli and just use git clone, followed by the lfs setup / checkout.
However, this somehow vitiate the purpose of the renku cli to simply these steps for untrained users.

**Comment by ableuler** [comment]
Thanks @tcchrist for this suggestion!

**Comment by rollicks-c** [comment]
Thanks for addressing this issue so quickly. Looking forward to the adjustments.

**Comment by mohammad-sdsc** [comment]
Thanks @rollicks-c for this bug report!

Renku is using git under the hood to clone a repository. If you can clone a repo using its ssh address and git, you should be able to do the same using renku. Can you please provide us with the full command and error message when trying to clone using renku and git?

We've modified this command to print a cleaner error message (which comes from Git): https://github.com/SwissDataScienceCenter/renku-python/pull/1738.

**Comment by rollicks-c** [comment]
Hi Mohammad

Thank you for the information.
The cleaner error message is already on the way - sweet, thanks.

About renku clone over ssh:
I seem to have had an issue with LFS somehow. Anyway, with the latest version of renku and a clean workspace I can no longer re-produce this. Seems to work fine. 
Sorry for the confusion and thx for the help.
