### ISSUE TITLE
make template update check if there was actually a change to the template

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1719]
In the current implementation of template update, we only check if the git commit in the template repo or the version in renku python that the template originated from has changed.

But if we create a project with `python-minimal` and then change `r-minimal`, this would register as a change in commits, even though the actual template didn't change (only the repo changed). 

We should check if there was a change to the template entry in manifest.yaml or if there was a change to a file in the template directory if the commit changed and only return `template_update_possible: True` in those cases.

This gets a bit tricky if the original commit was deleted, in these cases we might just do an update anyways.

Then we should make sure the template version gets updated even if there is no changed file.

**Comment by rokroskar** [comment]
don't we store the checksum?

**Comment by Panaetius** [comment]
Yes we do. We could compare the local checksum with the current remote checksum to see if there was a change. But we'd also need to check for additions/deletions. A git diff for everything in the respective template folder would probably be easier.
