### ISSUE TITLE
return template url in service on template migration

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1729]
As requested by the UI team https://github.com/SwissDataScienceCenter/renku-ui/pull/1068#discussion_r524379534 we should return the template repository url, template reference and template id in the cache.migrations_check and /cache.migrate endpoints.

**Comment by Panaetius** [comment]
Also return the current version in the Dockerfile or `None` if it's not available.

**Comment by ciyer** [comment]
We will also need a link to somewhere containing a description of changes in the dockerfile. 

In the case of the template repository, we expect these to be in the README of the repository. Where will they be in the dockerfile?

**Comment by Panaetius** [comment]
We just update the renku version in the dockerfile. otherwise the dockerfile only gets changed as part of the template. Right now there's no place to have a changelog that gets served (we could do a git diff, though that's probably not helpful). Maybe showing the commit messages in lieu of a changelog?

The place to put that would probably be in the manifest.yml (Since a repo can have multiple templates and the readme doesn't differentiate between them nor does it have a fixed format), although a separate file might be better suited (to not clutter the manifest.yml).

Right now we just offer the template for update on any commit to the template repo, which I think is not well suited to having a changelog. A changelog would rather lend itself if there is a release cycle where an explicit release is made and the changelog is curated. 

I didn't want to overcomplicate things and I think in quite a lot of cases, the template creator doesn't actually care about this (We care about it for renku templates, but for templates made for e.g. teaching a class, I doubt it matters). So having this as an optional feature on top of the current implementation, that a template creator can opt into, would make sense to me.

**Comment by ciyer** [comment]
I see. So, in the case where:

* a new version of renku-python is available
* the metadata is compatible with the existing version used in the project

A migration is available that just updates the version of renku-python. In that case, I think, someone trying to decide if they wanted to migrate the Dockerfile would probably want to see the changelog of renku-python.

**Comment by Panaetius** [comment]
a changelog of renku-python should be possible, since there we have a consistent format. we need to do https://github.com/SwissDataScienceCenter/renku-python/issues/1743 first for this to work cleanly.

**Comment by ciyer** [comment]
> a changelog of renku-python should be possible, since there we have a consistent format. we need to do #1743 first for this to work cleanly.

Just to make sure we are on the same page: we *do not* need you to send us the renku-python changelog. I just wanted you to confirm that the renku-python changelog would be the most relevant information for someone trying to decide if they wanted to migrate the Dockerfile.

If that's the case, we would need the information necessary to construct a link to the changelog. I think the version tag would be enough -- we would direct an interested user to https://github.com/SwissDataScienceCenter/renku-python/releases/tag/[tag]
