### ISSUE TITLE
Switch workflow commands to use new graph structure

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1734]
Add workflow commands (run/rerun/update/status/show)  under `renku graph workflow` that behave the same as the old commands but use the new metadata under the hood.

**Comment by Panaetius** [comment]
`rerun`/`show`, the rest is already implemented.

**Comment by Panaetius** [comment]
We should design UX for workflows and how users should use them before specifying commands.

**Comment by mohammad-sdsc** [comment]
A summary for discussion is written here: https://sdsc.atlassian.net/wiki/spaces/RENKU/pages/1230766103/Workflow+Commands+UX

**Comment by Panaetius** [comment]
tracked in https://github.com/SwissDataScienceCenter/renku-python/issues/1875
