### ISSUE TITLE
Add JSON schema validation for helm chart

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1755]
We should add a validation schema for our helm chart: https://helm.sh/docs/topics/charts/#schema-files

This allows us to enforce the structure of the values file needed, along with constraints that make sense (for instance min length of 32 for `jwtTokenSecret`)

**Comment by rokroskar** [comment]
should we move this issue to the top-level repo?

**Comment by Panaetius** [comment]
I'm not sure how this works in helm3? do child charts schemas get applied at the child level or does the schema need to be at the top level? In the former case it makes more sense to me for each child chart to have its own schema, living closer to where the values are actually used.
