### ISSUE TITLE
support kubernetes debugging of core service

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1759]
We should set up the core service to allow debugging using VSCode, as mentioned in https://github.com/Azure/vscode-kubernetes-tools/blob/master/debug-on-kubernetes.md#5-python-debug-prerequisites on dev/CI deployments (And prod?)

This allows faster response to difficult to reproduce issues on the service.

**Comment by rokroskar** [comment]
Yes, please. +100
