### ISSUE TITLE
dirty repo check should be done before running a command

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#176]
using `renku run` in a dirty repo results in the command executing and potentially producing outputs, but the results are not committed because the repository is dirty. E.g.

```
$ touch bla
$ renku run wc somefile > wc.out
Error: The repository is dirty. Please use the "git" command to clean it.

On branch master
Untracked files:
  (use "git add <file>..." to include in what will be committed)

	bla
	wc.out

nothing added to commit but untracked files present (use "git add" to track)

Once you have added the untracked files, commit them with "git commit".
```

We should check whether a result can be committed before executing the command.

**Comment by jirikuncar** [comment]
The `wc.out` file is created by shell. We need to distinguish between:

a) file has been already in Git tree, in that case we should revert it;
b) it's a new file, hence it should be deleted.
