### ISSUE TITLE
add command action to deploy PRs with different components

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1762]
We should add a PR comment dispatch to deploy a PR to dev.renku.ch on request, using https://github.com/marketplace/actions/slash-command-dispatch#slash_command-context

It should allow specifying version of components to deploy, to make testing easier, e.g. `/deploy renku-ui.image.tag=deadbeef0 renku-gateway.image.tag=abcdefg12345 jupyterhub.proxy.token=badc0ffee0ddfood`, with values corresponding to the `values.yaml` of renku.

**Comment by rokroskar** [comment]
I believe this is a duplicate of some part of https://github.com/SwissDataScienceCenter/renku/issues/1631

**Comment by Panaetius** [comment]
well, it doesn't really matter where we do it first :)

It'd need code to deploy all relevant components from a specific git revision plus repo-specific config that tells it what the "local" component is (e.g. `renku-python PR 123` when run on a PR on renku-python)

**Comment by rokroskar** [comment]
Right, I just mean it's going to be an action used by all the sub-repos so it might as well live in the main repo.

**Comment by Panaetius** [comment]
:+1: closing in favor of that one
