### ISSUE TITLE
provide option to use part of subdirectory tree on data import

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#182]
If this is the original data directory structure: 

```
/data
    └── dir1
          └── dir2
                └── dir3
                       └── file1
                       └── file2
```

The user may want to say something like

``` 
renku dataset mydataset add --relative-to /data/dir1/dir2 /data/dir1/dir2/dir3/file1
```

and get in their renku project this structure:

```
/renku-proj
    └── data
         └── mydataset
               └── dir3
                    └── file1
```

cc/ @mitch-volpi

**Comment by mitch-volpi** [comment]
Or even specifying the path in which the data will be imported, e.g. 

`` renku dataset mydataset add --import-in /data/dir3 /data/dir1/dir2/dir3/file1 
``

with the same original data and renku data folder structures as @rokroskar comment above. This way you can modify folder structures depending on your renku project, independently from data folders of already existing projects. 

I guess that possible ``--relative-to`` or ``--import-in`` overlap a lot, but depending on the folder structures one option might be more convenient than the other.
