### ISSUE TITLE
test: improve testing fixtures

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1877]
To split up dependencies of our testing modules, we should cleanup and improve our testing fixtures. Currently, all of our testing fixtures are a part of `conftest.py`, and quite a few of them don't have local imports of dependencies which have been moved to extras. 

I propose that we keep global fixtures in `conftest.py` and move all the rest into the corresponding module it's testing. Global fixtures are the ones which are used in all 3 components, while the fixtures which are only related to `cli`, `core` or `service` we move into those testing modules through the use of `@pytest.mark.usefixtures`.

This should help with keeping things more clean and we should gain separation of concerns on the module level. Meaning that on the CI we don't have to install all dependencies anymore, but we can have `cli` tests install only dependencies which it needs and `service` tests install `.[service]` and on integration `.[all]`. 

edit: 
Once we do this cleanup, we should update our CI runners accordingly so we cover cases which might occur due to extras depending commands, ie. `service`.

**Comment by rokroskar** [comment]
integration tests don't usually need the service, right? So they should still just install the base dependencies.

**Comment by jsam** [comment]
Service also have integration tests. Those tests are double marked both with `integration` and `service`.

**Comment by Panaetius** [comment]
Also check that the tests/ subfolders are properly split and there's no e.g. cli tests in `test/core`.
