### ISSUE TITLE
fix remote_branch and ref support in service

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1883]
On `cache.project_clone`, the `ref` parameter is on `ProjectCloneContext`, not on `ProjectCloneRequest` a client can't actually specify a ref to clone and it only works on master.

Somewhat related, `remote_branch` is not returned on `cache.migrate` if the branch is protected, making it impossible to know what branch the changes ended up in. We should also check that all other write operations return `remote_branch` properly.

**Comment by vfried** [comment]
Thanks for the quick fix @jsam!!!
