### ISSUE TITLE
service: improve management of cached repositories

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#1889]
Service currently supports `project.clone` on specific branch and from there user can work on that branch only. This part is not tested fully and requires better testing coverage. Beyond that, for big repositories it's not efficient to re-clone them every time.  To support them better we should add additional operations which would enable us "smarter" way of handling such repositories.

Operations which we should add are:
  * `/project.checkout`
  * `/project.reset`
  * `/project.status`

With the new operations, we should also move existing operations related to projects out of the `cache` module and add them to separate `project` module.

This epic should be umbrella for tickets related to:
  * Improved testing of current supported work across branches
  * Add operations which extend this flow
  * Refactors needed to make the flow consistent

**Comment by Panaetius** [comment]
Not really needed anymore with new porcelain changes
