### ISSUE TITLE
Cannot update papermill artifact notebook

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#195]
# Summary

Renku update fails with an exception:
```
schema_salad.validate.ValidationException: .renku/workflow/fa22570fc5b148788d864607dcf54903.cwl:1:1: Object
                                                          `.renku/workflow/fa22570fc5b148788d864607dcf54903.cwl`
                                                          is not valid because
                                                            tried `Workflow` but
                                                              * missing required field `inputs`
                                                              * missing required field `outputs`
                                                              * missing required field `steps`
```

# Steps to recreate

Download and extract [update-test.zip](https://github.com/SwissDataScienceCenter/renku-python/files/2093380/update-test.zip).

Do the following in the update test folder:

```
renku init .
renku run papermill 01_notebook.ipynb 01_notebook_run.ipynb -p output_pickle_file output.pkl
renku run papermill 02_notebook.ipynb 02_notebook_run.ipynb -p input_pickle_file output.pkl -p output_csv summary.csv
```

Now, change something in 01_notebook.ipynb (e.g., the size of the random array).

```
git add 01_notebook.ipynb
git commit -m"Updated notebook."
renku status
```
You will see that several files are out of sync.
```
renku update output.pkl
```
01_notebook_run.ipynb is still out of sync.
```
renku update 01_notebook_run.ipynb
```
This fails with an error like the above.

**Comment by jirikuncar** [comment]
@ciyer we can address this issue in several places:

1. `renku status` should give better hint that the file argument is optional;
2. `renku update PATH` should warn if you are not updating siblings of the `PATH`;
3. `renku update --siblings PATH` could solve your use-case.

**Comment by ciyer** [comment]
I think this is a good solution.
