### ISSUE TITLE
renku-core returns error when changing description of a dataset

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#1961]
**Describe the bug**
Changing the description of a dataset fails.

The UI receives the following response: `{"error": {"code": -32603, "reason": "internal error"}}`
In the server logs, I only see `http /renku/datasets.edit? 200 OK`

**Link to project**

https://dev.renku.ch/projects/dsex/parallel/project-a/datasets/pareto4

**To Reproduce**
1. Go to https://dev.renku.ch/projects/dsex/parallel/project-a/datasets/pareto4/modify
2. Change the description
3. Click on "Modify Dataset"

**Expected behavior**
I expect the description to be updated.

**Run environment (please complete the following information):**
- renku-core v0.14.0

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/1964
