### ISSUE TITLE
dataset: it is not possible to import datasets from internal projects

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#1962]
**Describe the bug**
Import of a dataset from a non-public project fails.

**Link to project**
https://dev.renku.ch/projects/cramakri/internal-test/datasets/some-random-numbers/

**To Reproduce**
Run the following in any renku repository.
1. `renku dataset import https://dev.renku.ch/datasets/b568ca8c-0a4e-454b-b099-316e3a86ad11`

`Cannot find these projects in the knowledge graph: https://dev.renku.ch/knowledge-graph/projects/cramakri/internal-test`

**Expected behavior**
I expect to be able to import datasets from non-public projects, assuming I have access to the project (which I do).

**Run environment (please complete the following information):**
- renku-python:v0.14.0
- knowledge-graph:1.34.0

**Comment by jachro** [comment]
I took out the security checks from the `GET /knowledge-graph/projects/:id` for now. The change is on knowledge-graph v1.34.3.

**Comment by mohammad-sdsc** [comment]
This story has three parts:
1. CLI: You can now use `renku login` to have a local token which will be passed to KG.
2. Renku UI: This is implemented in the linked PR. Service passes a gitlab token to renku core.
3. Interactive environment: This requires support from notebook services. A follow-up story is created: https://github.com/SwissDataScienceCenter/renku-python/issues/2059
