### ISSUE TITLE
add monitoring of (scheduled) jobs in deployments

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1969]
Currently, we don't have a way of checking that the scheduled maintenance tasks on the core service have been running nor of getting notified if they haven't been running in a while.

There should be a way to see the amount of jobs running on each queue (including dataset jobs), ideally in Grafana, and an early warning (email or error in sentry?) if they're haven't been running for a while. 

For dataset jobs, we might want to see how many usually run in a given time period and how they behave, and maybe add a warning as well if the current value is well below the usual amount for a given time period. This last part is probably tricky and might have to be fine-tuned, but it would give an indication if something goes wrong so we don't have to wait for users to report issues.

**Comment by jsam** [comment]
Hmm, how is that different from what we now with [rqmetrics](https://github.com/SwissDataScienceCenter/rqmetrics/blob/master/rqmetrics/exporter.py#L53).

The aggregations should works as well. Is there some bug with it?
