### ISSUE TITLE
Warn user on renku run if a filename contains illegal characters

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#1984]
In https://github.com/SwissDataScienceCenter/renku-python/pull/1963 we added support for unicode characters in filenames, solving a lot of filename problems. 

But as the CWL spec says: 
```
If the path contains POSIX shell metacharacters (|, &, ;, <, >, (, ), $ ,`, \, ", ', <space>, <tab>, and <newline>) or characters not allowed for Internationalized Domain Names for Applications then implementations may terminate the process with a permanentFailure.
```

So some characters aren't allowed by cwl in path names, but users might still have files with those characters in it. We should detect if any path contains an invalid character on `renku run` and pompt the user if they want to continue anyways or cancel the run.

The reasoning behind this is that `renku run` will work with those characters, it's just `rerun` and `update` that have issues. A user might just be interested in tracking his work (not rerunning ), and rerun would work if called with `--edit-inputs` where the filename is changed to a proper filename. So a user might still want to go ahead, they should just be aware of the risks.

**Comment by mr-c** [comment]
When using `cwltool` you can pass [`--relax-path-checks`](https://cwltool.readthedocs.io/en/latest/cli.html#cmdoption-cwltool-relax-path-checks) as a temporary workaround

**Comment by mohammad-alisafaee** [comment]
We should check other executors like toil to see if they have limitations on the files names as well.

**Comment by mr-c** [comment]
`toil-cwl-runner` has the same option

**Comment by Panaetius** [comment]
Closing as this was already addressed over a year ago
