### ISSUE TITLE
poor template URL handling

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#1988]
**Describe the bug**
If a template repo URL contains a trailing slash, the repo fetch fails - see [here](https://renku.discourse.group/t/community-contributed-project-templates/284/2)

**To Reproduce**

Go to https://renkulab.io/projects/new and put in `https://github.com/SwissDataScienceCenter/contributed-project-templates/` as the custom template URL. If you remove the trailing slash, all is well in the world. 

**Expected behavior**
The templates are fetched

**Screenshots and/or execution output**

![image](https://user-images.githubusercontent.com/3353586/112317883-c3130800-8cac-11eb-8111-55702d6403d8.png)

**Additional context**

This seems to only be a problem with the service, i.e. 

```
renku init -s https://github.com/SwissDataScienceCenter/contributed-project-templates.git -r main test-template
```

seems to work fine.

**Comment by Panaetius** [comment]
We should not use the same validation for git_urls for cloning template repos as we use for cloning user projects.
