### ISSUE TITLE
cli: git rm before renku update

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#202]
Define what should happen if:

1. all outputs of a step were removed from the git repo
2. a single output was removed from the repo

before running `renku update`.

cc @ciyer @rokroskar

**Comment by jirikuncar** [comment]
> 2. a single output was removed from the repo

#205 will ask user to explicitly add `--with-siblings` options.

**Comment by jirikuncar** [comment]
> 1. all outputs of a step were removed from the git repo

#205 will exit with message that all files are up-to-date.

**Comment by jirikuncar** [comment]
> Then, I modify the script in such a way that it also generates `out3`. From my point of view, it is the same script, so I should be able to use `renku update`

@lusamino Unfortunately, this is not possible. The update will always generate same files as it can not modify the workflow. If you change the script in a way that a new output is created, you must execute `renku run`.

**Comment by lusamino** [comment]
Thanks @jirikuncar . Fair enough then. That was simply my vision on how `renku update` would desirable work for me.

**Comment by rokroskar** [comment]
@lusamino I think the behavior you are envisioning is reserved for `renku rerun` which is not quite ready yet.

**Comment by lusamino** [comment]
Ok, that command then sounds interesting while it allows to continue tracking the lineage of outputs and inputs. Thanks!
