### ISSUE TITLE
No error when specifying an invalid reference for a project template.

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#2021]
# Description

See https://github.com/SwissDataScienceCenter/renku-ui/issues/1307.

**Run environment (please complete the following information):**
 - renku-core:0.14.1

**Comment by Panaetius** [comment]
This is a known bug and that I fixed in https://github.com/SwissDataScienceCenter/renku-python/pull/1957

The service has undocumented (and probably unintended) functionality which is removed now, where if a ref didn't exist, it would create a new branch with that name off of master.

**Comment by lorenzo-cavazzi** [comment]
This has been fixed (see SwissDataScienceCenter/renku-ui#1307)
