### ISSUE TITLE
Specifying `-r` without a source template should fail on init

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2023]
This should either fail or try to actually initialize from the reference provided:

```
renku init -r 73db625 test-init
```

The `.renku/metadata.yml` file shows the correct ref even though this is not the ref that was used to initialize the project (whatever the version of the template that is hard-coded in renku-python was used instead).

**Comment by Panaetius** [comment]
Since we don't have refs for the templates included inside renku, we should make `--template-source` mandatory if `--template-ref`/`-r` is specified.
