### ISSUE TITLE
Support for Workflows

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#206]
# Summary

This is followup to #202. Consider the following situation: 

- step1 generates file1
- step2 takes file1 as input and produces file2

```
step1* -> file1 -> step2* -> file2
```

Further, assume step2 uses a stochastic algorithm, so each run will be slightly different. We would like to regenerate file2 several times to compare the output. We would like to do something like

```
renku regen file2 -o file2.1
```

This should construct a workflow that expresses file2 and run the workflow, saving the output as file2.1 The provenance graph of file2.1 should make it clear that it is a version of file2.

# Solutions

One way to solve this is by introducing support for workflows. 
```
renku workflow alias file2 mywfl           # assigns the name mywfl to the workflow that generate file 2
renku run --workflow mywfl -o file2.1  # run the workflow
```

**Comment by lusamino** [comment]
Considering the wide range of users that should be able of using `renku`, I would try to simplify things further and avoid introducing more commands. Therefore, I believe that instead creating a new command `regen`, it would be just better to implement this into `update`, as follows: 
`renku update step2 -o file2.1` 
Perhaps I am oversimplifying, or I am just miserably wrong, but I think `renku update` is quite a cool feature and should implement all these features in a transparent way for the user.

**Comment by jirikuncar** [comment]
The intention for `renku update` was to enable re-execution of steps without modification and I am quite hesitant to add more options there.

In the case where you want to force re-execution of a file, I would propose:

```console
$ renku rerun [--with-siblings]  [--input file1] [--depth=1] file2
```
a) limit starting point by specifying files
b) limit by depth
