### ISSUE TITLE
Finalize move to new metadata

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2078]
- Remove old metadata format
- Make sure renku run/rerun/update/status, renku workflow show still work
- Deprecate renku log in favor of renku graph export
- add a migration to force doing `renku graph generate`

Note: once we start working on this, we'll have a feature freeze until it's done and we moved to the new metadata format and new storage backend

**Comment by mohammad-sdsc** [comment]
`rerun` and `update` commands should use new metadata's `Plan` directly to be able to set proper values for `ParameterValue` classes on an `Activity` after execution. Currently, we convert from a `Plan` to `Run` and then convert back from a `ProcessRun` to `Plan` which results in losing the mapping between parameter values and the original plan.

**Comment by Panaetius** [comment]
We can do this on a per-command basis with a PR per cli command or multiple if it's small ones.

**Comment by mohammad-sdsc** [comment]
For some commands (`run`, `rerun`, `update`), we are converting old metadata from/to CWL workflows. It probably make sense to do all these commands at once since we now need to covert the new metadata. Or, we can make the conversion in one PR and adopt the commands in another.
