### ISSUE TITLE
remove single-file dataset metadata and add invalidation to old dataset metadata

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2082]
As an experiment we added single-file metadata for datasets in the `renku graph` command namespace, but this turns out to not work well.

We should remove the relevant changes and port over the `prov:wasInvalidatedAt` property to the old dataset metadata to support dataset invalidation there.

Open questions:
- Should we do a migration that checks git history for deleted datasets and adds invalidation to them?
- Coordinate with the KG team as they already have mechanisms in place to detect dataset deletion

**Comment by mohammad-sdsc** [comment]
This is done as part of #2119.
