### ISSUE TITLE
Support importing dataset images when importing Zenodo datasets

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2102]
We currently expect the `images` on a dataset to be of type http://schema.org/ImageObject, but in the case of Zenodo, we just get a URL (plain string) to the image. We should map that in the import so we can import Datasets with an image correctly.

**Comment by mohammad-sdsc** [comment]
This is an example dataset with image: https://zenodo.org/record/830043.
