### ISSUE TITLE
Add mypy typechecking to tests

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2104]
We should use https://pypi.org/project/pytest-mypy/ or similar to enable type-checking in our tests, though only for code that actually has type annotations.

**Comment by vigsterkr** [comment]
i've recently installed [pyright](https://github.com/Microsoft/pyright) based plugin for vim and i must say it's pretty slick! i've ran it on develop and there's quite some noise (meaning false positive errors) but there's quite some actual typing errors that pyright got it right. maybe we wanna consider using it.... tbh i have no insights about the pros and cons regarding mypy and pyrights...
