### ISSUE TITLE
git-lfs was missing; invest a(nother) check against that

### ISSUE THREAD

**Issue by fgeorgatos** [SwissDataScienceCenter/renku-python#213]
it occurred when a project was created by another person...

**Comment by rokroskar** [comment]
thanks @fgeorgatos -- can you clarify what exactly the problem was?

**Comment by leafty** [comment]
the CLI does not print a warning if you do not have lfs installed, this also happenened with @3C111 --> the data folder was not using lfs

**Comment by jirikuncar** [comment]
- [ ] run `git lfs install` + `git lfs checkout` after cloning the Renku project
- [ ] possibly wrap it into `renku clone` command

**Comment by rokroskar** [comment]
I think this is no longer a problem. Closing.

**Comment by jirikuncar** [comment]
@rokroskar I don't think this was handled yet. We should change the title to: `cli: renku clone`

**Comment by rokroskar** [comment]
I see - in that case I'll remove it from this cleanup board?

**Comment by rokroskar** [comment]
`renku clone` has been implemented.
