### ISSUE TITLE
Add `renku workflow visualize` command

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2131]
Add `renku workflow visualize` command as per the 001 RFC. Still needs design on what the output actually looks like and what the flags are.

**Comment by rokroskar** [comment]
maybe the package that is menioned [in this SO post](https://stackoverflow.com/questions/3211801/graphviz-and-ascii-output) could be useful.

**Comment by rokroskar** [comment]
Or [this one](https://github.com/ggerganov/dot-to-ascii)
