### ISSUE TITLE
Improve handling of dataset tags

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#2210]
Currently, `DatasetTag` is stored as part of the dataset's metadata and it uses commit sha to refer to an exact dataset version.
We are moving away from using commit shas and we have a metadata database that can return objects by their ids. We should change this class to use datasets' ids instead of commit shas. We should also store it in the metadata database as an independent entity (and not as part of Dataset's metadata).

**Acceptance Criteria**
* Use dataset ids when tagging a dataset version
* Store `DatasetTag` as a Persistent object
* A migration to convert old `DatasetTag`s
* Make sure all tag-related commands work (e.g. `tag`, `ls-tags`, `export`, ...)

**Comment by mohammad-sdsc** [comment]
This would allow us to address some additional use-cases like tagging an older version of a dataset which are not currently possible.

**Comment by Panaetius** [comment]
Also check with the KG team on what's needed on their end
