### ISSUE TITLE
cli: create manual job for runner rerun

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#222]
- [ ] update `.gitlab-ci.yml` template
- [ ] commit and push results

---
NOTE: This is only a temporary solution before REANA is deployed

**Comment by rokroskar** [comment]
@jirikuncar doesn't this require some more features in the UI? Or how would the rerun be triggered?

**Comment by jirikuncar** [comment]
@rokroskar either UI or CLI for the moment. We need to access GitLab job trigger API in both cases.
