### ISSUE TITLE
docs: implement new structure

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2223]
After https://github.com/SwissDataScienceCenter/renku/pull/2191 is merged, the two sets of docs will be out of sync. The docs in this repo need to be adjusted to the new structure.

**Comment by Panaetius** [comment]
If there are any big rewrites that would take some time, collect them here  to create follow-up issues.

**Comment by Panaetius** [comment]
@rokroskar This can be closed now, right?

**Comment by rokroskar** [comment]
yes! I forgot to link this issue, sorry...
