### ISSUE TITLE
Refactor datasets

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#2227]
There are some potential improvements after migration to the new persistent layer and metadata that would result in a cleaner code for datasets:
* ~Have data files and metadata in a single commit instead of committing data files first in a separate commit~
* Move `DatasetsApiMixin` to its own class/package and remove all `LocalClient` dependencies
* Separate interface and management logic from `commands/dataset.py` and `DatasetsApiMixin` to have a clear distinction between the two
* ~Use dependency injection everywhere~
* ~Remove redundant tests; convert integration tests to unit tests where ever possible~

**Comment by Panaetius** [comment]
https://github.com/SwissDataScienceCenter/renku-python/issues/2565

https://github.com/SwissDataScienceCenter/renku-python/issues/2566
