### ISSUE TITLE
cli: support workflow naming, listing, importing

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#223]
```console
$ renku workflows/tools list/name/import
```

**Comment by rokroskar** [comment]
This should probably include creation of metadata fields in the repo's metadata file.

**Comment by jirikuncar** [comment]
We could go with following solutions:

1. Use `.renku/metadata.yml` for storing aliases for workflows/tools;
2. Add metadata inside workflows/tools CWL definition with name(s);
3. Create `.renku/refs/{workflows|tools}` with symlinks to generated files.

**Comment by Panaetius** [comment]
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1875
