### ISSUE TITLE
Refactor/untangle RenkuOperationMixin

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2242]
Currently, `renku.service.controllers.api.mixins.RenkuOperationMixin` has a bit too many hats. It handles:

- delayed/asynchronous or synchronous execution of a request
- adding/getting projects to/from the cache
- "remote" execution (cloning to a temp directory, bypassing the cache), used for anonymous sessions
- on-the-fly migration of a project
- Switching between branches in cached projects
- resetting/fetching remote changes in cached projects so they are in sync with gitlab

This makes this component very fragile, as there are many reasons why it might change and many changes that can break other things. It also makes it almost impossible to test all the different combinations of situations.

This functionality should be split up into several classes, with the service controls specifying which ones are relevant to them.

Namely:
- async execution: most endpoints don't make sense to be called in an async way (e.g. dataset.list), whereas others probably always should be async (`cache.migrate`, `dataset.import`). This should be handled by a dedicated control that only handles async execution, and we should determine which endpoints should be async. It is unclear if there are any good candidates for endpoints that should support both?
- A separate class for "local" and for "remote" execution so the two aren't mixed
- The cache itself should offer cache management functionality or there should be a `CacheManager` class that deals with fetching/resetting cached projects. 
- cached projects should be per branch/ref, not per project, so there's no conflict between them and no need to switch branches
- Some endpoints can work on refs (branch/tag/commit) while other (mainly write requests) can only really work on a branch. Service controls need to be able to specify which of the two they support, and the API should have a consistent naming for it (`ref` vs. `branch` ?)

It is unclear to me if we want on-the-fly migrations. We don't want them on write requests, sow e don't inadvertently migrate a repo, and they probably only make sense in async requests, as they can take quite long. And I'm not aware of any long running read requests that we have at the moment. Additionally, there is the issue that these implicit migrations poison the cache, as the cached project is migrated but not in sync with the remote anymore, where a read request shouldn't change the state of the repo.

Architecture wise, what we have right now with `renku_op` that is wrapped by different classes isn't actually bad, if it weren't just a single class doing the heavy lifting. Maybe using the Decorator pattern would be a good fit for this (maybe with a Factory class to return a decorator for Local or Remote execution?).

**Comment by Panaetius** [comment]
We should have an interface for a CacheManager or similar and an implementation of that interface. That'd also make it easier to move to a different caching mechanism in the future (e.g. if we had a dedicated repo cache service with mounting if we are ever able to multi-mount volumes).

The CacheManager should make it very clear what the lifecycle of cache objects is. 

Nice to have would be to have cache cleanup be something triggered via HTTP request+cronjob instead of rq-scheduler queue.

**Comment by olevski** [comment]
During this refactoring also resolve the following issues:
https://github.com/SwissDataScienceCenter/renku-python/issues/2797
https://github.com/SwissDataScienceCenter/renku-python/issues/3482
https://github.com/SwissDataScienceCenter/renku-python/issues/3493
