### ISSUE TITLE
Allowing varied output/input parameters

### ISSUE THREAD

**Issue by gavin-k-lee** [SwissDataScienceCenter/renku-python#2251]
**Is your feature request related to a problem? Please describe.**
As renku is used alongside external storage, such as mounted volumes (S3, Switch Drives etc.) or external databases, input and output parameters should allow for files and directories which are outside of the working directory. They should also allow for generic types such as strings, in case there is a particular way of specifying inputs/outputs on those external resources.

**Describe the solution you'd like**
As part of #1875 , allowing non-file inputs and outputs should be made possible. For example, the URL *https:/omero.epfl.ch/webclient/?show=dataset-523* could be an input or output. 

**Describe alternatives you've considered**
At the moment, only files and directories within the renku project directory can be passed to `--output` and we would then have to set `--no-output` which is undesirable, as we would like to utilise renku workflows as much as possible.

**Additional context**
Errors such as the following occur: *Error: Path “https:/omero.epfl.ch/webclient/?show=dataset-523” does not exist.*

**Comment by Panaetius** [comment]
I think the `--param` flag mentioned here covers this use-case: https://renku-python.readthedocs.io/en/latest/reference/commands.html?highlight=Specifying%20auxiliary%20parameters#detecting-input-paths

**Comment by gavin-k-lee** [comment]
Cool, let's have a look at this if it covers the use case. Thank you!

**Comment by Panaetius** [comment]
Did you ever get around to seeing if this covers the use-case?

**Comment by gavin-k-lee** [comment]
Yes sorry for the delay. I think it covers it:
```
 base ▶ ~ ▶ work ❯ welcome-to-renku ▶ master ▶ $ ▶ renku workflow show wc--l-Dockerfile-d9b21
Id: /plans/70603e8fad384a0a94b9f7e4f26fb085
Name: wc--l-Dockerfile-d9b21
Command: wc -l Dockerfile > wcD.txt
Success Codes: 
Inputs: 
        - l-1:
                Default Value: Dockerfile
                Position: 1
                Prefix: -l 
Outputs: 
        - output-2:
                Default Value: wcD.txt
                Position: 2
Parameters: 
        - omero_data:
                Default Value: https:/omero.epfl.ch/webclient/?show=dataset-523
                Position: None
```
