### ISSUE TITLE
use renku credentials for cloning

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2265]
Currently I can fetch a renku token and set up the credentials for pulling and pushing with `renku login --git` when inside a repository. However, a key application of this feature is to _clone_ repositories, i.e. using the token when (by definition) still outside of a renku repository. I would like the following to work:

```
renku login <renku-endpoint>
renku clone https://<renku-endpoint>/<project-slug>
```

it might even be nice to compress this into a one-liner: 

```
renku clone --login https://<renku-endpoint>/<project-slug>
```

Note that the user should not concern themselves with the fact that a specific URL needs to be used for the credential forwarding to GitLab to work, so we should handle that somehow.

**Comment by Panaetius** [comment]
Without `renku clone --login` part
