### ISSUE TITLE
cli: prepare directory structure for output files

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#228]
- [x] the existing directory structure which overlaps with output globs should be created for each step in `update` or `rerun`
- [x] include tests for script that expect an output directory to exist

**Comment by mitch-volpi** [comment]
Tested and worked, using `renku rerun --with-siblings`

**Comment by rokroskar** [comment]
@mitch-volpi can you elaborate on what was tested?

**Comment by mitch-volpi** [comment]
It has been run with output files in subfolders, and output files were correctly moved

**Comment by rokroskar** [comment]
great thanks -- I was having trouble understanding what this is all about ;)

**Comment by jirikuncar** [comment]
@rokroskar it's to allow following workflow:

```console
$ renku run papermill notebooks/process.ipynb notebooks/outputs/process.ipynb -p INPUT data/inputs/table.csv -p OUTPUT data/outputs/plot.png
$ jupyter lab
# edit notebook
$ git commit notebooks/process.ipynb
$ renku update
```
