### ISSUE TITLE
renku workflow ls --format json-ld fails

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2283]
Running 

```
renku workflow ls --format json-ld
```

fails with the stacktrace below. It works fine with `json` or `tabular` formats. 

**Renku version:** 0.16.1.dev24+g7eccf621
**OS:** Darwin (Darwin Kernel Version 19.6.0: Thu May  6 00:48:39 PDT 2021; root:xnu-6153.141.33~1/RELEASE_X86_64)
**Python:** 3.9.0

### Traceback

```
Traceback (most recent call last):
  File "[...]/marshmallow/schema.py", line 547, in dump
    result = self._serialize(processed_obj, many=many)
  File "[...]/calamus/schema.py", line 183, in _serialize
    value = field_obj.serialize(attr_name, obj, accessor=self.get_attribute)
  File "[...]/marshmallow/fields.py", line 318, in serialize
    return self._serialize(value, attr, obj, **kwargs)
  File "[...]/calamus/fields.py", line 527, in _serialize
    result.append(self._serialize_single_obj(obj, **kwargs))
  File "[...]/calamus/fields.py", line 499, in _serialize_single_obj
    schema = self.schema["to"][type(obj)]
KeyError: <class 'renku.core.commands.view_model.plan.CommandInputViewModel'>
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
Do we actually want to export JSON-LD here? So far only `renkug raph export` could export JSON-LD. And `--columns` doesn't really make sense with JSON-LD

**Comment by rokroskar** [comment]
That's true - then the simple solution is to just communicate a bit better about format options.

**Comment by rokroskar** [comment]
I though it would be nice to be able to get json-ld if you wanted to build a graph representation gradually instead of dumping everything at once. But that's probably a very niche usecase.
