### ISSUE TITLE
Bug (error) trying to import renku dataset to a renku project

### ISSUE THREAD

**Issue by firatozdemir** [SwissDataScienceCenter/renku-python#2369]
**Description**
`renku dataset import` not working on master branch for datasets that come from renku projects made with master branch.    
Maybe renku datasets not registered to knowledge graph on master branch.

**Links to projects**
[Main renku project](https://renkulab.io/projects/firat.ozdemir/tmp_renku_proj).   
[Second renku project where the dataset exists](https://renkulab.io/projects/firat.ozdemir/small-oa-dataset).   
[Third renku project from last stable release where a working dataset exists](https://renkulab.io/projects/firat.ozdemir/stable-small-oa-dataset).

**To Reproduce**
1. Clone renku-python master branch, build it. After, clone my renku project. Then try to import dataset from another renku project.
```bash
git clone git@github.com:SwissDataScienceCenter/renku-python.git
cd renku-python
pip install .[all]
cd ..
git clone git@renkulab.io:firat.ozdemir/tmp_renku_proj.git tmp_
cd tmp_
```  
A dataset from master branch of renku-python is located on [this renku project](https://renkulab.io/projects/firat.ozdemir/small-oa-dataset). Dataset name: small-oa-dataset-proj, project name: small-oa-dataset
```bash
renku dataset import https://renkulab.io/projects/firat.ozdemir/small-oa-dataset/datasets/small-oa-dataset-proj
```
Returns  

> Error: Cannot fetch dataset with name 'small-oa-dataset-proj' from 'https://renkulab.io/knowledge-graph/projects/firat.ozdemir/small-oa-dataset'

**Expected behavior**
I expect the a prompt to ask whether to download the found version of the imported dataset or not.   
Here is a working example:   
Dataset from stable renku release is located on [this renku project](https://renkulab.io/projects/firat.ozdemir/stable-small-oa-dataset). Dataset name: sample-small-dataset, project name: stable-small-oa-dataset
```bash
renku dataset import https://renkulab.io/projects/firat.ozdemir/stable-small-oa-dataset/datasets/sample-small-dataset
```
Returns  
> Processing commits 2/2 4d09f5e8958c9fc78d303f953850095aeda12178
> Successfully applied 1 migrations.
> CHECKSUM                                  NAME                     SIZE (MB)  TYPE
> ----------------------------------------  ---------------------  -----------  ------
> ae45879be9926ed516c542290bff9ccf98bac656  small_sim_dataset2.h5  16000000.00  h5
> Warning: Do you wish to download this version? [y/N]: N

This command succeeds. `renku dataset import` can import the dataset from a stable release renku project. 

**Run environment (please complete the following information):**
 - renku-python version: 0.16.1.dev51+gb8b124b1
 - Python version: 3.9.0
 - local terminal OR renkulab interactive environment? local
 - if renkulab, specify RStudio / Jupyterlab / Other & browser [e.g. chrome, safari] No

**Additional context**
I noticed that I can also import dataset from stable renku release after finding the node `@id` that matches @type: "http://schema.org/Dataset:   
![image](https://user-images.githubusercontent.com/6260768/134682292-3bec9ae2-aed3-482e-bbeb-afa91ef221fe.png)

```bash
renku dataset import https://renkulab.io/datasets/b12ce2d3-7bf4-4576-ba54-6a6a35d94e2b  
```

Accordingly, I attempted finding the same field for the dataset from the [2nd project](https://renkulab.io/projects/firat.ozdemir/small-oa-dataset). 
```bash
renku graph export --full --format json-ld
```
![image](https://user-images.githubusercontent.com/6260768/134682378-abb01eff-e702-4f4b-af3a-9a195425121e.png)

Then I try the same: 
```bash
renku dataset import https://renkulab.io/datasets/21fa6797e39a4f1e9344776436399977
```
I get the error: 
![image](https://user-images.githubusercontent.com/6260768/134682964-981acd57-91a0-4ae9-8d22-33820a675f08.png)

> Error: Resource not found in knowledge graph: https://renkulab.io/datasets/21fa6797e39a4f1e9344776436399977

Final note: Knowledge Graph integration is active on all 3 projects.

Edit: I realized I misunderstood the use of "--external" tag. So 2nd project essentially had only a reference to a relative path as the dataset file. This obviously leads to not being able to import the dataset from another renku project. After fixing this, my issue still persists same as before though.

**Comment by Panaetius** [comment]
For importing a dataset, renku first queries the knowledge graph (not the local one, the global one through a service endpoint) to get details for the dataset, and then imports it through git. If the project that contains the dataset was built with renku-python master, then it wouldn't be picked up by the knowledge graph as that doesn't support current master yet, so it'd say that it can't find the dataset.
