### ISSUE TITLE
bug: ci/cd fails for previously successful renku==0.14.1 spec. only renku==1.0.0.pre1 works

### ISSUE THREAD

**Issue by firatozdemir** [SwissDataScienceCenter/renku-python#2371]
**Describe the bug**
CI/CD pipeline failing for a project with renku==0.14.1 although it passed 3 months ago (with no changes). 

**Link to project**
[Project](https://renkulab.io/gitlab/das/bstnn) where I observed the behavior

**Reproduce**
[Here is the successful build log from 3months ago](https://renkulab.io/gitlab/das/bstnn/-/jobs/227168), using renku==0.14.1.    
[Fail log for the same commit that fails today](https://renkulab.io/gitlab/das/bstnn/-/jobs/289446), using renku==0.14.1.  
[Success log for the same project if I update renku version to renku==1.0.0.pre1](https://renkulab.io/gitlab/das/bstnn/-/jobs/289449). 

For reference, here is the root of error (seems like missing package rdflib-jsonld<0.6.0,>=0.5.0): 

>     ERROR: Command errored out with exit status 1:
>      command: /home/jovyan/.local/pipx/venvs/renku/bin/python -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ey4tcloy/rdflib-jsonld_2056368f122a489fa203be534966777b/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ey4tcloy/rdflib-jsonld_2056368f122a489fa203be534966777b/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-_rg_2j4b
>          cwd: /tmp/pip-install-ey4tcloy/rdflib-jsonld_2056368f122a489fa203be534966777b/
>     Complete output (1 lines):
>     error in rdflib-jsonld setup command: use_2to3 is invalid.
>     ----------------------------------------
>      WARNING: Discarding https://files.pythonhosted.org/packages/f5/17/45e137be0d93b70827fe5529c0400731344a978bc792193d7d9152e6dbe4/rdflib-jsonld-0.5.0.tar.gz#sha256=4f7d55326405071c7bce9acf5484643bcb984eadb84a6503053367da207105ed (from https://pypi.org/simple/rdflib-jsonld/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
>      ERROR: Could not find a version that satisfies the requirement rdflib-jsonld<0.6.0,>=0.5.0 (from renku) (from versions: 0.2, 0.3, 0.4.0, 0.5.0, 0.6.0, 0.6.1, 0.6.2)
>      ERROR: No matching distribution found for rdflib-jsonld<0.6.0,>=0.5.0
>      Error installing renku from spec 'renku==0.14.1'.

**Expected behavior**
Previously succeeding build should still succeed with the same renku build it worked before. Otherwise previously working projects would fail image builds. 

**Run environment (please complete the following information):**
 - renku-python:  0.14.1 and 0.16.1 fails, 1.0.0.pre1 succeeds
 - Python version: 3.7
 - local terminal OR renkulab interactive environment? renkulab ci/cd
 - if renkulab, specify RStudio / Jupyterlab / Other & browser [e.g. chrome, safari]: tried on renkulab

**Additional context**
This is not an issue for my project, but perhaps it ends up being one for other older projects that track attention one of these days.

**Comment by Panaetius** [comment]
0.16.1.post1 should work as well. There was a change in setuptools that prevents rdflib-jsonld from being installed, which we have no control over. Since we use pipx in the images to install renku and that automatically updates srtuptools, this breaks all old images, unfortunately.

If you need an older version of renku to work, there is a fix outlined in https://renku.discourse.group/t/error-during-environment-creation/407/10 to modify the dockerfile that also fixes it
