### ISSUE TITLE
Dataset import features/streamlining

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#239]
Working with datasets is a bit clunky at the moment. In addition, the current set up would require us to invent another abstraction for importing code that is separate from importing data. These two entities are in many ways the same (i.e. git objects) the only difference is that data might be stored in LFS or some other storage backend while code will reside completely inside git.  

## Proposed changes

How about the following functionality:

```
renku import <src path or URL> <optional relative dst path>
```

This will do what `renku dataset add` does at the moment, namely:

*  for URLs it will simply copy the data/code and create the associated metadata entry
* for git repos it will add the repo as a submodule into `.renku/vendors/` and link the required files into the destination path
* for local files it will copy them unless `--no-copy` is used in which case they are linked. 

## Metadata

Since we no longer have datasets packaged in the `data` directory anymore, there isn't much use for a `metadata.yaml` file along with each dataset. We should therefore keep a `.renku/metadata.yaml` file where all metadata associated with code and data files is stored. 

## Datasets 

We still want to be able to yield/produce datasets but we don't need to make things harder for users by requiring them to store everything in datasets from the beginning. For this, we should have something like `renku publish` which would package a collection of data and create a metadata file for the bundle. This would allow us to be flexible about the formats used, e.g. [frictionless data](frictionlessdata.io), [Research Object](http://www.researchobject.org/). In addition, it allows us to bundle code together with data (as in the case of Research Object).

**Comment by ebiiii** [comment]
In the case you "create" a new dataset (either by actually generating it and publishing it or by importing it for the first time on Renku from an external URL), we need a way to reference it so that it can then later on be imported in other projects, individually. Would this still map to submodules and new repositories ? If yes, then the metadata(.yml) should be available in those repositories as well ?

**Comment by ciyer** [comment]
@ebiii I wonder if we need a concept for "data refactoring." It seems like a natural progression for a project is to start will all the data for the project as part of the project, but as data sets need to be reused, extract them (possibly with code that belongs to it) into a separate repository.

**Comment by ebiiii** [comment]
@ciyer I think this can be the concept behind what Rok suggested with `renku publish` and I agree it makes sense to not force it right away at the beginning of a project.

**Comment by rokroskar** [comment]
@ebiiii I'm not sure I follow your question -- are you asking if we want to create platform-wide UUIDs or similar for data objects? I think we'll want that eventually but we're not there at the moment. For now, the unique identifier is the repo URL + repo path + commit-sha and I think this is enough for the time being. 

A related issue is whether we differentiate between data and code. We discussed this some time ago with @ciyer and one of the things that came up was that clearly identifying code vs data objects would eventually be needed because they may need to be treated differently.

**Comment by ebiiii** [comment]
@rokroskar UUIDs may come later, yes, but my suggestion was about having distinct repos for each dataset (or data/code bundle), so that it makes [repo URL + commit-sha] the reference. As pointed out by @ciyer this doesn't need to be the case right at the beginning of a project, but eventually all datasets of a projects will be in their own submodules, as the result of the "publishing" command. Or do you think this is already too far for a first step ?

**Comment by rokroskar** [comment]
aha I see. Yes, that's how I also envision it, i.e. refactoring will apply to data as well as code. It doesn't necessarily mean *all* datasets of a project will be submodules, I guess it would depend on the use-case. For one-off projects where a particular dataset is linked to a paper and tightly coupled with the code in the repo it might make sense to just keep it in the same repo. If it's used/reused heavily at a later point it might be moved to a standalone repo. In a lab where lots of people are using the same data and data ingestion is standardized (e.g. sequencing) it might make sense to create data-only repositories from the beginning. The point is more to keep it flexible at this point and not impose abstractions that in the best case would be confusing and in the worst case a barrier.

**Comment by ciyer** [comment]
For me, publishing is different from refactoring the core. Publishing is appropriate if you have a version of data and code that you want to make available. Refactoring is about changing the structure of the data and code to group together related things and create a unit that can be referenced alone and independent of the rest of the project from which these things come.

**Comment by jirikuncar** [comment]
We should not remove support for having multiple datasets in one repo, but rather look for a way to group multiple files/directories into separate dataset used for publishing.

**Comment by rokroskar** [comment]
@jirikuncar I didn't understand any of the above comments to suggest that we shouldn't allow multiple datasets per repo, unless I misunderstood?

**Comment by rokroskar** [comment]
@ciyer absolutely, publishing is definitely different than refactoring. I also don't think that in order to publish a dataset you would need to isolate it in its own repo -- it could be a bundled subset of a repo.

**Comment by rokroskar** [comment]
From our IRL discussion:

```
renku import
renku group
renku metadata <set> <get>
```

**Comment by ciyer** [comment]
A little more detail:

```
renku data import <url>
renku data group <path1> <path2> [...]
renku data metadata set [-f yaml-file] [key] [value]
```

**Comment by rokroskar** [comment]
@ciyer should there be a separate command for importing code? what about workflows? We need to structure this in a way that leaves those options open.

**Comment by rokroskar** [comment]
Revisiting this now - the API could look like

```bash
renku data import --dataset <dataset> <URL> <path>
renku dataset create <dataset>
renku dataset add <path> <dataset>
renku dataset import <URL> <dataset>
```

```
renku dataset import <zenodo-doi>
```
results in:

```
tree
data
  |_ <zenodo-doi>
    |_ <file>
```

```
renku data import <URL> <path>
```

results in

```
tree
<path>
```

I can now create a dataset and add this imported data to it: 
```
renku dataset create <dataset>
```
followed by

```
renku dataset add <path> <dataset>
```

**Comment by rokroskar** [comment]
closing in favor of https://github.com/SwissDataScienceCenter/renku/issues/593
