### ISSUE TITLE
Handle indirectly changing output filenames

### ISSUE THREAD

**Issue by vigsterkr** [SwissDataScienceCenter/renku-python#2461]
with `renku workflow execute` and `renku workflow iterate` input parameters of a workflow can be changed. But in case the output of the workflow is not specified as a parameter for the workflow, say it's generated by the script in the workflow, where the name is a function of the input parameters, currently both workflow commands will fail as in CWL we expect to have the same output filename.

a quick example

model.py
```
import sys

param, param_value = sys.argv[1].split("=")

with open(f"model_{param_value}.txt", 'w') as f:
    f.write("this is the model")
```

```
renku run --name train_model -- python model.py --learning_rate=0.1
```

the above will pickup `model_0.1.txt` being the output of the workflow.

now if one runs:
```
renku workflow execute --set "param-1=0.5" train_model
```

this will cause an error because in the CWL we expect that the output will be in `model_0.1.txt` where in fact it's going to be in `model_0.5.txt`.

In case of CWL this could be fixed by using wildcard pattern for the output, but this is quite error prone, and still there needs to be additional work to fix how the metadata is being recorded, because atm even if the wildcard approach is working in the `Activity` the original output filename will be recorded as generated output.

**Comment by Panaetius** [comment]
Wildcard support is planned to be added as per https://github.com/SwissDataScienceCenter/renku-python/blob/master/design/001-new-workflow-commands/001-new-workflow-commands.md#templated-values but I doubt it's something we could set automatically, it's something a user has to specify.

What we could do in addition to that is try and detect outputs that aren't matched by the Plan (with applied values) and show a warning to the user, to prompt them to add wildcards if that's what they want.

**Comment by Panaetius** [comment]
Use Jinja2, also for `datetime`.

No wildcard support for now.

Add validation to check that we can render the jinja2 entries.
