### ISSUE TITLE
defining outputfolder makes renku not up to date

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#250]
When I run a script with a path as input (e.g. -o outputpath) where the outputfiles need to come, renku thinks that the input changed (as there are new files in the directory). This is however not true, it is still based on the most recent data.

```
remko@ERIN-RNI-30243:~/Documents/renku-projects/VOM_natt/vom_natt$` renku run python3 src_py/prep_vom.py -im data/Silo/howard.txt -ic data/ManuaLoa_CO2/weekly_in_situ_co2_mlo.csv -o data/VOM_input/HowardSprings/
Script finished
remko@ERIN-RNI-30243:~/Documents/renku-projects/VOM_natt/vom_natt$ renku run python3 src_py/prep_vom.py -im data/Silo/sturt.txt -ic data/ManuaLoa_CO2/weekly_in_situ_co2_mlo.csv -o data/VOM_input/SturtPlains/
Script finished
remko@ERIN-RNI-30243:~/Documents/renku-projects/VOM_natt/vom_natt$ git push
Counting objects: 36, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (36/36), done.
Writing objects: 100% (36/36), 895.67 KiB | 3.51 MiB/s, done.
Total 36 (delta 23), reused 0 (delta 0)
To internal.renku.ch:VOM_natt/vom_natt.git
   75029de..a83da83  master -> master
remko@ERIN-RNI-30243:~/Documents/renku-projects/VOM_natt/vom_natt$ renku status
On branch master
Files generated from newer inputs:
  (use "renku log [<file>...]" to see the full lineage)
  (use "renku update [<file>...]" to generate the file from its latest inputs)

	data/VOM_input/AdelaideRiver/dailyweather.prn: data/VOM_input/AdelaideRiver#bef02a1d
	data/VOM_input/DalyRiver/dailyweather.prn: data/VOM_input/DalyRiver#06536a10
	data/VOM_input/DryRiver/dailyweather.prn: data/VOM_input/DryRiver#7d526e20
	data/VOM_input/HowardSprings/dailyweather.prn: data/VOM_input/HowardSprings#6d61b390
	data/VOM_input/SturtPlains/dailyweather.prn: data/VOM_input/SturtPlains#90271bd2
```

**Comment by jirikuncar** [comment]
@rcnijzink the inputs/output directories are not yet supported. I will add it to the priority list.

**Comment by rokroskar** [comment]
@rcnijzink could you retry by first installing renku-python from the master branch? See https://renku-python.readthedocs.io/en/latest/#installation

**Comment by rcnijzink** [comment]
I tried it, but when I use renku run I get the error that one of the outputfiles is not found. This command runs without problem without renku:

`renku run python3 src_py/sel_sce_runs.py -i output/HowardSprings/1/sce_out.txt -o work/HowardSprings/best/pars/ -n 4 -m 'ini'
Traceback (most recent call last):
  File "/home/remko/.local/bin/renku", line 11, in <module>
    load_entry_point('renku', 'console_scripts', 'renku')()
  File "/home/remko/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/remko/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/remko/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/remko/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/remko/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/remko/.local/lib/python3.6/site-packages/click/decorators.py", line 64, in new_func
    return ctx.invoke(f, obj, *args[1:], **kwargs)
  File "/home/remko/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/contextlib.py", line 51, in inner
    with self._recreate_cm():
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/remko/src/renku/renku/cli/_git.py", line 108, in with_git
    mapped_streams = _mapped_std_streams(dirty_paths)
  File "/home/remko/src/renku/renku/cli/_git.py", line 70, in _mapped_std_streams
    lookup_inos = {(stat.st_dev, stat.st_ino): path for stat, path in stats}
  File "/home/remko/src/renku/renku/cli/_git.py", line 70, in <dictcomp>
    lookup_inos = {(stat.st_dev, stat.st_ino): path for stat, path in stats}
  File "/home/remko/src/renku/renku/cli/_git.py", line 69, in <genexpr>
    stats = ((os.stat(path), path) for path in lookup_paths)
FileNotFoundError: [Errno 2] No such file or directory: '/home/remko/Documents/renku-projects/VOM_natt/vom_natt/work/HowardSprings/best/pars/pars150.txt'
`

**Comment by jirikuncar** [comment]
@rcnijzink it is a different 🐛 . I will create a separate issue for it.

**Comment by jirikuncar** [comment]
@rcnijzink the output directories should work thanks to the PR #300. Please let us know if you have any specific case where the `renku status|update` does not behave well. Thanks!
