### ISSUE TITLE
add a `project.lock_status` endpoint to the service

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2507]
Currently, long running operations like cache.migrate lock the project to other requests, raising an exception of a lock couldn't be acquired withing 15 seconds.

We should add a `project.lock_status` endpoint that can let clients know if a project is currently (write-)locked, returning a boolean.

The code for this could be something like
```
if "project_id" in self.context:
    project = self.cache.get_project(self.user, self.context["project_id"])
elif "git_url" in self.context:
    project = Project.get(
        (Project.user_id == self.user_data["user_id"]) & (Project.git_url == self.context["git_url"])
    )
else:
    raise Exception()

locked = True

try:
    with project.read_lock(timeout=0):
        locked=False
except (portalocker.LockException, portalocker.AlreadyLocked):
    locked = True

return locked
```

and of course without using the `RenkuOperationMixin`, similar to how renku.service.views.jobs doesn't use the mixin.

**Comment by mohammad-sdsc** [comment]
Discuss with UI to make sure that the API here is what they want.
