### ISSUE TITLE
renku dataset update semantics

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2520]
`renku dataset update` called without additional arguments will currently attempt to update _all_ datasets - it would be nice if it followed the same semantics as `renku update`, i.e. it should return the help text if called without any arguments and require the `--all` flag to update all datasets. ~~It would also be nice to have a "dry run" option to see which changes exist.~~

**Comment by Panaetius** [comment]
https://github.com/SwissDataScienceCenter/renku-python/issues/2564
