### ISSUE TITLE
Fix optimized migration check for users with an invalid auth

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#2546]
https://github.com/SwissDataScienceCenter/renku-python/issues/2432 implements an optimized migration check by downloading only necessary files. However, if a user's access token is invalid, this optimization raises an exception even for public projects.

**Comment by mohammad-sdsc** [comment]
It seems that gitlab raises an authorization error even for public repos when an auth header is provided. For example, `curl -H 'Authorization: Bearer 12345' https://dev.renku.ch/gitlab/api/v4/projects/renku-python-integration-tests%2Fno-renku` fails while `curl https://dev.renku.ch/gitlab/api/v4/projects/renku-python-integration-tests%2Fno-renku` works.

**Comment by Panaetius** [comment]
Also change it so it falls back to the normal code if the optimized Gitlab code fails.
