### ISSUE TITLE
Show workflow names in renku workflow visualize

### ISSUE THREAD

**Issue by cmdoret** [SwissDataScienceCenter/renku-python#2574]
When running `renku workflow visualize`, the step boxes contain workflow commands by default.
In some cases, these commands are long and truncated, it can be better to see workflow names instead.
When using the `--interactive` option, we can see the full command`, but the workflow name is not available in the detail view either.

Making the workflow names visible in the details view would be very useful.

Optionally, it could be good to add a `--names` flag to `renku workflow visualize` to show names instead of commands on the steps boxes.

**Comment by Panaetius** [comment]
I'll add it to interactive view. The `visualize` command already had a parameter `-c <columns>` that defaults to `-c command` which determines what to show in the box. I'll add `plan` to that, then `-c plan` accomplishes what you want.
