### ISSUE TITLE
jinja missing from basic installation

### ISSUE THREAD

**Issue by IsabelHerr** [SwissDataScienceCenter/renku-python#2613]
## Describe the bug
I am trying to initalize a renku project locally. Following the details here: (https://renku.readthedocs.io/projects/renku-python/en/v0.15.0/commands.html#module-renku.cli.init) i did the following : 

cd /my-project
renku init 

I get the following response : 

Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

## Details
I am working on a Macbook pro Monterey with the M1 chip

**Renku version:** 1.0.4
**OS:** Darwin (Darwin Kernel Version 21.1.0: Wed Oct 13 17:33:01 PDT 2021; root:xnu-8019.41.5~1/RELEASE_ARM64_T6000)
**Python:** 3.9.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/click/decorators.py", line 26, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "[...]/renku/cli/__init__.py", line 177, in cli
    from renku.core.management.client import LocalClient
  File "[...]/renku/core/management/client.py", line 23, in <module>
    from renku.core.management.datasets import DatasetsApiMixin
  File "[...]/renku/core/management/datasets.py", line 43, in <module>
    from renku.core.management.repository import RepositoryApiMixin
  File "[...]/renku/core/management/repository.py", line 28, in <module>
    from jinja2 import Template
ModuleNotFoundError: No module named 'jinja2'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
Were there any errors when you tried to install renku? How did you install it?

Because it says the python package `jinja2` is missing, but that is a requirement of renku that should be installed by `pip` alongside renku.

**Comment by IsabelHerr** [comment]
I used the following commands to install renku : 
$ python3 -m pip install --user pipx
$ python3 -m pipx ensurepath
$ pipx install renku

there were no errors 

I have pip version 21.1.3 and pipx version 1.0.0

**Comment by Panaetius** [comment]
Thanks for letting us know, we'll investigate if there is some issue with using pipx to install renku

**Comment by Panaetius** [comment]
Check if pipx still works and if not if there's an easy fix

**Comment by rokroskar** [comment]
@IsabelHerr we seem to have found the problem and it should be fixed in the next release - in the meantime, the work-around is to install renku with 

```
$ pipx install renku[all]
```

_or_ just inject `jinja` into your renku pipx environment with 

```
$ pipx inject renku jinja2  
```

**Comment by Panaetius** [comment]
Related to https://github.com/python-poetry/poetry/issues/3718
