### ISSUE TITLE
inputfile outdated, but outputfiles up to date?

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#262]
After doing some more work with Renku, it looks as if not all actions are traced. Renku status shows for example that these inputfiles for the our model are not up to date: 

```
Files generated from newer inputs:
  (use "renku log [<file>...]" to see the full lineage)
  (use "renku update [<file>...]" to generate the file from its latest inputs)

	work/AdelaideRiver/vom_namelist: data/VOM_input/AdelaideRiver/vom_namelist#5f8965ba
	work/HowardSprings/2/vom_namelist: data/VOM_input/HowardSprings/vom_namelist2#3f9d5800
	work/HowardSprings/3/vom_namelist: data/VOM_input/HowardSprings/vom_namelist3#3f9d5800
	work/HowardSprings/4/vom_namelist: data/VOM_input/HowardSprings/vom_namelist4#3f9d5800

Input files used in different versions:
  (use "renku log --revision <sha1> <file>" to see a lineage for the given revision)

	data/VOM_input/HowardSprings/vom_namelist2: a97803f3, 3f9d5800
	data/VOM_input/HowardSprings/vom_namelist3: 868aa3ea, 3f9d5800
	data/VOM_input/HowardSprings/vom_namelist4: 948738a4, 3f9d5800
	data/grassdata/DEM/PERMANENT/WIND: ae889941, 836ad5a4
	data/grassdata/DEM/PERMANENT/hist/dem_merged: ae889941, 9976b0d9
	data/grassdata/DEM/PERMANENT/hist/s15e130_dem: ae889941, 9976b0d9
	data/grassdata/DEM/PERMANENT/hist/s20e130_dem: ae889941, 9976b0d9
	data/grassdata/DEM/PERMANENT/sqlite/sqlite.db: 06fb82f8, 836ad5a4, 9976b0d9
	data/grassdata/DEM/PERMANENT/vector/ozflux_sites/hist: 06fb82f8, 9976b0d9
```

These are inputfiles for model runs, so the results of the modelruns should not be up to date as well. This is not the case, and using renku log also does not show the dependency on the input-files from the modelruns:

```
remko@ERIN-RNI-30243:~/Documents/renku-projects/VOM_natt/vom_natt$ renku log output/HowardSprings/1/sce_out.txt 
*  0f65546d output/HowardSprings/1/sce_progress.txt
| *  0f65546d output/HowardSprings/1/sce_bestpars.txt
|/
| *  0f65546d output/HowardSprings/1/sce_lastbest.txt
|/
| *  0f65546d output/HowardSprings/1/sce_lastloop.txt
|/
| *  0f65546d output/HowardSprings/1/sce_out.txt
|/
| *  0f65546d output/HowardSprings/1/sce_status.txt
|/
@  0f65546d .renku/workflow/4234914028a9439bbb7cde56ce13c17f_src_VOM_VOM_Fortran_model.x.cwl
```

So, is it correct that here only the last step is shown? Is it still connected to the inputdata?

**Comment by jirikuncar** [comment]
@rcnijzink It looks like the input files has not been specified as command line arguments. Can you paste the `renku run` command too?

**Comment by rcnijzink** [comment]
@jirikuncar Ah I think I understand. Indeed, it is just an executable that reads in a namelist, without defining the namelist on the command line, the namelist has also all the options for inputs and outputs. The workflow file looks like this:

`arguments: []
baseCommand:
- ../../../src/VOM/VOM_Fortran/model.x
class: CommandLineTool
cwlVersion: v1.0
hints: []
inputs: {}
outputs:
  output_0:
    outputBinding:
      glob: output/HowardSprings/1/sce_progress.txt
    streamable: false
    type: File
  output_1:
    outputBinding:
      glob: output/HowardSprings/1/sce_bestpars.txt
    streamable: false
    type: File
  output_2:
    outputBinding:
      glob: output/HowardSprings/1/sce_lastbest.txt
    streamable: false
    type: File
  output_3:
    outputBinding:
      glob: output/HowardSprings/1/sce_lastloop.txt
    streamable: false
    type: File
  output_4:
    outputBinding:
      glob: output/HowardSprings/1/sce_out.txt
    streamable: false
    type: File
  output_5:
    outputBinding:
      glob: output/HowardSprings/1/sce_status.txt
    streamable: false
    type: File
permanentFailCodes: []
requirements:
- class: InlineJavascriptRequirement
- class: InitialWorkDirRequirement
  listing:
  - entry: '$({"listing": [], "class": "Directory"})'
    entryname: output/HowardSprings/1
    writable: true
successCodes: []
temporaryFailCodes: []`

**Comment by jirikuncar** [comment]
@rcnijzink can you modify the command line arguments so you can include all input files?

There is a dirty trick to make sure the dependencies are correctly detected, but generating list of input files that can be used later on:

```console
$ renku run ls inputs/* > names.txt
$ renku log names.txt
$ renku xargs cat < names.txt > result.txt
$ renku log result.txt
```

**Comment by rcnijzink** [comment]
Thanks, I will try that!
