### ISSUE TITLE
docs: check if pipx still fits with our users needs

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2624]
In https://github.com/SwissDataScienceCenter/renku-python/issues/2613 we'll check if pipx still actually works and if not, if there's a simple fix for getting it to work.

This issue is about the more fundamental question if we still want to recommend pipx to users, if there's another tool that can fill a similar niche but behaves better. Does poetry have something for installing a global environment? Can [pyenv shims](https://github.com/pyenv/pyenv#understanding-shims) be used? Is there some other way to make a `console_scripts` entry globally available?

**Comment by rokroskar** [comment]
Checked that pipx works ✅ -- but see #2629

**Comment by Panaetius** [comment]
So I guess this can be closed?

**Comment by rokroskar** [comment]
well I was going to close it but wasn't sure if you wanted to evaluate pipx more carefully still.

**Comment by Panaetius** [comment]
Well I guess it does help some users with path stuff and if we don't need to put in any effort to maintain it, why not keep it. But if there is an issue again we should evaluate if it's worth the effort
