### ISSUE TITLE
linking inputfile with template and data

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#264]
When I copy files from templates to work with, I used renku run to maintain the dependency, after which I start filling the template with data from other analyses. Renku seems to lose the dependency here as well.

This is what I do:

```
renku run cp data/namelist_templates/vom_namelist_template_SCE data/VOM_input/HowardSprings/vom_namelist5
```

This works fine:

```
renku log data/VOM_input/HowardSprings/vom_namelist5 
*  67fcc5c8 data/VOM_input/HowardSprings/vom_namelist5
*  67fcc5c8 .renku/workflow/15d4385fa95d4af7aaab9227a6cb9e83_cp.cwl
@  e94da33f data/namelist_templates/vom_namelist_template_SCE
```

Now I start filling the template with outcomes of a different analysis, in this case I determined mean stream bed elevation, which is needed in the vom_namelist:

```
renku run sed -i "/i_zr/c\i_zr=$(grep 'mean=' data/SRTM/processed/stats_stream3.csv | cut -d "=" -f 2 )d0,            ! average channel bed elevation in m" data/VOM_input/HowardSprings/vom_namelist5
```
Now renku log does not show the link to the original files (the template and stats_stream3.csv), but only the following:

```
renku log data/VOM_input/HowardSprings/vom_namelist5 
*  1b259da0 data/VOM_input/HowardSprings/vom_namelist5
@  1b259da0 .renku/workflow/608fe06e2ed44a7c81da38337f1081b8_sed.cwl
```

So it seems it does not link to the original files, or does it still do that, but is renku log not showing it?

**Comment by jirikuncar** [comment]
@rcnijzink the subshell execution is not supported (yet). You will need to split the second command to several steps:

```console
$ renku run grep 'mean=' < data/SRTM/processed/stats_stream3.csv > data/SRTM/processed/stats_stream3.mean.line
$ renku run cut -d= -f2 <  data/SRTM/processed/stats_stream3.mean.line > data/SRTM/processed/stats_stream3.mean
$ renku run # create sed script
$ renku run sed "sed script" data/VOM_input/HowardSprings/vom_namelist5 > data/VOM_input/HowardSprings/vom_namelist5.replaced
```
also it is very hard to correctly support file edits so you should never modify file, but create a new one when executing `renku run`.

**Comment by rcnijzink** [comment]
Ok, super thanks! I did it as you suggested and that worked for me ;)
