### ISSUE TITLE
cli: renku init cannot handle non-existent directory

### ISSUE THREAD

**Issue by tduberne** [SwissDataScienceCenter/renku-python#272]
When getting started with the CLI, I expected `renku init` to be consistent with `git init`, and thus tried:

```
renku init some-nonexistent-directory
```
which fails.

It is not a big issue, as it only takes one additional command to get the directory initialized, but it would be nice to have renku commands as close to their git equivalent as possible, to minimize friction. I would be willing to have a go at it and provide a pull request for it, if there is interest. Of course, if there is any deep reason for not having this feature, I would be glad to know.

BTW, I find the whole Renku initiative very interesting, thanks a lot for building such a system!

**Comment by rokroskar** [comment]
Thanks for the feedback @tduberne -- yes, the existence of the directory is currently a prerequisite but could in principle be changed to be more in-line with the behavior of git. If you're willing to provide a PR, that would be great!
