### ISSUE TITLE
Activity ids generated wrong in migration.

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2747]
Due to the change in https://github.com/SwissDataScienceCenter/renku-python/pull/2581 activity ids are generate wrong when migrating, resulting in e.g. `https://renkulab.ioe446022537f8bb4a9e2514ae9bbdb3bdb2833888/` instead of `https://renkulab.io/activities/e446022537f8bb4a9e2514ae9bbdb3bdb2833888/`.

**Comment by rokroskar** [comment]
how was that bug not caught by the shacl checker?

**Comment by rokroskar** [comment]
I guess it doesn't check the structure of the URIs...

**Comment by rokroskar** [comment]
oh great, thanks, that makes sense.

**Comment by rokroskar** [comment]
Also, shouldn't this be closed?
