### ISSUE TITLE
Renku dataset import by keyword

### ISSUE THREAD

**Issue by almutlue** [SwissDataScienceCenter/renku-python#2755]
Reusing datasets in multiple renku projects by importing them using `renku dataset import` is a very convenient way of interacting between projects. In our pipeline we import all datasets with a certain keyword (after some checks about the generator) into a specific project. 

As `renku dataset import` expects the dataset URI, we first need to identify the ID and project of all datasets with a specific keyword. 

For this we query the KG endpoints to show all datasets with our keyword, similar to:

`data_ids = curl -s "${KG_URL}/datasets?query=$KEY" | jq -r '.[] | .'\""identifier"\"''` 
(afterwards we check if the keywords of the resulting ids match with our keyword)

If a dataset has already been imported into another project these queries will result several dataset identifier for the same _"original"_ dataset. When we now import this dataset again, we want to import from the _"root/original"_ project, which it was generated in, because we rely on regular updates. 
If the datasets point towards the copy of a dataset within a third project, it might not get updated, when the _original_ dataset was changed. 

As it is hard to tell from the KG query which dataset was the original one and which is a copy of that dataset, we have a hard time to ensure to pick the original URI for import. 

This is why something like an new option or similar for `renku dataset import`  to import from the **"root/original" dataset** instead of the **dataset copy**, when using `renku dataset import` with a **dataset URI**, that points to an imported dataset.

Althought the `sameAs` field is helpful to identify parent/root datasets from KG query results, this will not work, if the parent has been updated, but not the child, yet.

Thanks a lot!
Almut

**Comment by jachro** [comment]
Hi,

I might not be fully understanding your process but as far as I can see the problem you are having is around identifying which dataset returned by the Dataset Search API is the very original dataset (or the topmost dataset in other words). I'm guessing you know that on each item returned from the [Dataset Search API](https://github.com/SwissDataScienceCenter/renku-graph/blob/release/knowledge-graph/README.md#get-knowledge-graphdatasets), there's a `_url` property with a link to `details` URL. When you follow it, you get to the [Dataset Details API](https://github.com/SwissDataScienceCenter/renku-graph/blob/release/knowledge-graph/README.md#get-knowledge-graphdatasetsid) where you can find either `sameAs` or `derivedFrom` property. Based on these two you can find out if a dataset is the topmost dataset or not. The rules are as follows:
* there's a `derivedFrom` property which means this dataset is a modification of another Dataset and simply it's the topmost dataset if someone imported that specific version to another project;
* there's a `sameAs` property that points to the same dataset (the `sameAs` contains this dataset `identifier`);
* there's a `sameAs` property that points to a non-Renku dataset (e.g. the URL is a Zenodo or Dataverse URL looking like `https://doi.org/10.7910/DVN/WTZS4K`).

In all other cases, the dataset has to be somewhere in the import hierarchy but not at the very top.
A small note, it's impossible that `sameAs` and `derivedFrom` are both set on a single dataset.

I'm hoping that helps at least a bit. If not, please let us know so we can try to find a more satisfying solution.

**Comment by almutlue** [comment]
Hi @jachro, thanks a lot for your reply. 
This is in deed helpful, but I think I was not quite clear above.
We are struggeling to import a dataset from the project of origin (instead of a project where it has been imported in), but this could very much be a modification/update of the very first generated dataset.

So for example these 2 datasets: 
https://renkulab.io/knowledge-graph/datasets/94638c493af44b5e8bc09b2351f6a8c2  
https://renkulab.io/knowledge-graph/datasets/6c7bb8cc68794fa6af2df74bab23bc9a

The second one has been imported from the project of the first one, but they are not the same any longer (no `sameAs` field), as the first one has been updated/changed and the second not, yet. Both have a `derivedFrom` field, because they have been modified/are the topmost imported datasets respectively. When importing into a new downstream project we would want to import the first dataset only and not the second, because that is the repository that the dataset was originated from. As long as we haven't updated the second dataset, it is hard to do this in an automatized way.

This sounds very minor, because we anyways want to update all imported downstream datasets, but as we have a large set of projects, that are "connected" by dataset imports like this and continuously updated, it actually turned out to be a problem.

I know this is a rather specific problem and I understand, that it is a reasonable definition within renku to treat datasets that have been modified/diverged from the original as separate datasets. Anyways I would be very grateful for any idea on how to best detect/filter datasets that have their origin in another renku project.
Best,
Almut
