### ISSUE TITLE
use project template on renku init

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#279]
We need to somehow sync the project creation between `renku-python` and the UI. 

There is currently a repo for the project template, if possible we should use that everywhere. If not, lets use this space to brainstorm solutions.

**Comment by jirikuncar** [comment]
I would propose a simple service that runs:

```console
$ renku init [optional args]
$ git push https://auth2:TOKEN@REPO_URL/NAMESPACE/PROJECT
```

**Comment by rokroskar** [comment]
this will be handled with #546
