### ISSUE TITLE
cli: renku run --name TestFlexCheckPlot -- [...]

### ISSUE THREAD

**Issue by williamaeberhard** [SwissDataScienceCenter/renku-python#2790]
## Describe the bug
Clean repo, renku run on an Rscript command applied on a single .r file with a few arguments. The .r script was successfully executed (produced a plot saved as .png) and the background R process automatically quit as expected. The only feedback I got was "Ahhh you have found a bug".

## Details

**Renku version:** 1.0.1
**OS:** Linux (#101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021)
**Python:** 3.8.10

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/commands/run.py", line 166, in _run_command
    raise errors.InvalidSuccessCode(return_code, success_codes=success_codes)
  File "[...]/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "[...]/renku/core/management/workflow/plan_factory.py", line 568, in watch
    self.add_outputs(candidates)
  File "[...]/renku/core/management/workflow/plan_factory.py", line 273, in add_outputs
    input_path = Path(os.path.abspath(path)).relative_to(self.working_dir)
  File "[...]/pathlib.py", line 908, in relative_to
    raise ValueError("{!r} does not start with {!r}"
ValueError: '/data/shared/Big_Data/data/FLEXPART_output/ALERT/2019_diffparticlenums/2019050100/grid_time_20190502000000.nc' does not start with '/home/william/Sandbox_William/arcticnap'
```

## Additional context
Given the traceback this might be relevant: this is run on a virtual machine where the data are stored in /data/shared (where I have read/write permissions) but the renku run was executed from my home dir /home/william. Two of the arguments passed on to Rscript are the (relative) paths to the data file and where to save the .png plot.

**Comment by Panaetius** [comment]
thanks for reporting this, it looks like a bug because the file isn't in your repository. We'll look into it in the next sprint (next week).

**Comment by Panaetius** [comment]
I made a PR that fixes the immediate issue. But do note that using files outside the project in workflows has only partial support.

If you run the command above as is, `/data/shared/Big_Data/data/FLEXPART_output/ALERT/2019_diffparticlenums/2019050100/grid_time_20190502000000.nc` will be treated as a string parameter, not as an input file. So renku wouldn't automatically detect changes to it.
If you want to use a file outside the project as a proper input file, you'd have to add it to a dataset first using the `--external` flag, then the workflows can properly handle it as an input.

**Comment by williamaeberhard** [comment]
Thanks! I updated renku to the latest v1.2.0 and tried running `renku run` again. I got an error this time: it complains that my output directory is not empty and that I should to delete all files in there (with `git rm`) to execute `renku run` safely. My dir indeed contains a few png files, but all were tracked in the repo (I re-ran renku run from a clean repo). I suppose this error is part of the partial support for inputting files that are not tracked (here my .nc data file only seen as a character string as you explained).

**Comment by Panaetius** [comment]
Can you post the command you're running?

**Comment by williamaeberhard** [comment]
`renku run Rscript --vanilla src/FlexCheckPlot.r ../../../../data/shared/Big_Data/data/FLEXPART_output/UTQ_KEVO_THULE/2017/2017032500/grid_time_20170326000000.nc figs/tmp/ 1 45 23`

Explanations: `Rscript --vanilla` opens an R instance as a background process, executes the .r script and passes to it all following arguments as character strings. Here, the 1st argument (the long path in /data) is the data file used as an input while the 2nd argument (figs/tmp/) is the output directory for the .png that is created in the .r script.

**Comment by Panaetius** [comment]
so `figs/tmp/` is not empty, I assume?

The issue probably is that is you specify `figs/tmp/`, renku will treat that as "This whole directory is an output", as that's what the commandline is telling it. But that means the directory has to be empty (or at least all the files in it have to be generated by a renku workflow). This is because once renku tracks an output, it considers it "managed by renku", so to speak. Essentially it would record "This command created the files in this directory", to keep track of the provenance of the project. But if there's files in there already, recording that would be a lie, so it refuses to record that.

A simple solution would be to make a subdirectory inside `figs/tmp/` to output to. You can also tell renku that `figs/tmp` is just a string, not a folder parameter, in which case it would detect the files created and track the individiual files, instead of the whole folder. You'd do that passing `--param target-folder=figs/tmp/` to the `renku run` command as mentioned in the [Specifying auxiliary parameters section](https://renku.readthedocs.io/en/latest/renku-python/docs/reference/commands.html?highlight=--param#detecting-input-paths).

**Comment by Panaetius** [comment]
Do you think there is a way we could handle this better, e.g. adjust the message, to make it better understandable for users?

Or put another way, what would you have liked the command to tell you when this didn't work, in a short sentence? :slightly_smiling_face:

**Comment by williamaeberhard** [comment]
Hmm, ideally something that explains why the issue is happening (difficult in a short sentence, I know). The error message I got was clear in terms of what could immediately be done, i.e., empty the output dir, but it came without any explanation. Thus this is not super helpful if for some reason I cannot follow the suggested steps right away. In this case, understanding the renku default behavior of considering a path argument as an entire dir to track as part of a workflow was key to finding a solution. Perhaps at least supply a link as part of the error message, say to the [Detecting input paths section](https://renku.readthedocs.io/en/latest/renku-python/docs/reference/commands.html?highlight=--param#detecting-input-paths) of the renku run doc?
