### ISSUE TITLE
metadata version 10 changes

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2807]
Once we have to add a migration to metadata 10, there are some things that need to be cleaned up. This issue is meant to keep track of them.

- https://github.com/SwissDataScienceCenter/renku-python/pull/2805 introduced patching of python namespaces so old namespaces get automatically redirected to new namespaces. We should migrate all database objects that still point to an old namespace to the corresponding new one, so this isn't necessary anymore.
- https://github.com/SwissDataScienceCenter/renku-python/pull/2748/files#diff-1f777de0e82e75241448bca5bba8ab018557867063bd98d4e3a9fee45f90b8d5R50 we had broken activity ids and now fix them on the fly. we should fix them in the migration instead and remove this code.

**Comment by mohammad-sdsc** [comment]
https://github.com/SwissDataScienceCenter/renku-python/issues/2813
