### ISSUE TITLE
Support non-file data sources

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#2861]
We should support sources/inputs of data other than files, e.g. SQL queries or REST Apis. Probably through extending the dataset concept.

Some requirements/caveats:
- should be generic (non-filebased source), maybe with a plugin mechanism as well, not just  API and DB (could be streaming from S3 or downloading through FTP or any number of things)
- We have to be able to calculate a hash on it
- What if I have a DB query that returns rows in random order, even if it returns the same rows, the hash would change due to ordering and look as if it was a modified input
- What happens when I run renku status and the API/DB is down?
- How do we handle credentials/connection-strings etc? We probably don't want to store them in the repo but then how could someone else clone and execute it?
- If we have a workflow service and show status on the UI, how could the UI know the credentials?
- Do we check for changes on every renku status? If a project has 100s of API calls for different Activities, that could amoutn to a DDOS of the service or just be super slow
- Is this a problem we want to solve or something we want to impose on the other party? E.g. with downloading a homepage, we could check the Last-Modified  header with a HEAD request to not have to execute the full request, but then not every homepage sets that header. It's a trade-off between performance and making our lives easier vs. supporting everything.
- How could this ever be reproduced? If I have a DB that gets live sensor data streamed to it, and I executed a workflow yesterday, and now I want to reproduce that result, how could I do that if the query just returns current data
more formally, how do we deal with date dependency of data and reproducibility? For files, git/git-lfs takes care of this, but I doubt it's possible on arbitrary input streams
- How would we deal with changing schemas? If my DB query is SELECT * FROM sensor_data and now someone adds (or removes) a column from the sensor_data table, my workflow probably breaks. How do I as a user deal with this? How can I ensure reproducibility in 5 years time?

**Comment by rokroskar** [comment]
Is there really a use-case for this? Or is the intent to also design this in the context of the [external data RFC](https://github.com/SwissDataScienceCenter/renku-rfc/blob/main/design/007-external-data-handling/007-external-data-handling.md)?

**Comment by Panaetius** [comment]
@lokijuhy brought up the use-case but I'm not sure what the current state is after the meeting we had and if they can solve it another way.

**Comment by lokijuhy** [comment]
@rokroskar @Panaetius We do not have an active use case for this right now. After the input from the design meeting, I decided that for that use case (the ICOS project at Empa) we will investigate other options.

**Comment by rokroskar** [comment]
The main direction of this issue is not so different from the external data RFC though - so as this is in the sprint already we can just repurpose it for that :)

**Comment by Panaetius** [comment]
closing this since we have issues for S3 and other external sources
