### ISSUE TITLE
cli: renku error about missing attribute 'infrastructure'

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#2887]
## Describe the bug
Renku commands give an error about no attribute 'infrastructure'. This only happened in a new repository that I created today. 

## Details
It happened for this repo: https://renkulab.io/projects/remko.nijzink/vom-sens-hydro

**Renku version:** 1.1.4
**OS:** Linux (#118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022)
**Python:** 3.8.5

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/metadata/database.py", line 789, in deserialize
    object = self._deserialize_helper(data)
  File "[...]/renku/core/metadata/database.py", line 825, in _deserialize_helper
    cls = self._get_class(object_type)
  File "[...]/renku/core/metadata/database.py", line 768, in _get_class
    cls = get_class(type_name)
  File "[...]/renku/core/metadata/database.py", line 87, in get_class
    return get_attribute(module, components[1:])
  File "[...]/renku/core/metadata/database.py", line 112, in get_attribute
    object = getattr(object, component)
AttributeError: module 'renku' has no attribute 'infrastructure'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
A project that was modified with renku 1.2.x cannot be opened with renku < 1.2.x. 

But 1.2.x can open <1.2.x projects without needing a migration, just as soon as 1.2.x does a write, it becomes incompatible with earlier version. 

There was a change in 1.2 that's backwards compatible, but not forward compatible. hence we didn't create a major version release for it.

We also added a check that would warn a user if they are on a version of renku-python that's too old to work with a project, but that will only work if we do changes like this again in the future., i.e. versions after we introduced this.
