### ISSUE TITLE
Add "temp folder" option to renku dataset export

### ISSUE THREAD

**Issue by cmdoret** [SwissDataScienceCenter/renku-python#2905]
Users can create tags to version their Renku datasets, but accessing the contents of previous tags requires exporting it to a new {renku,zenodo,dataverse} dataset and importing it.

To improve the UX around tags, users should be able to "checkout" previous dataset tags without publishing them online.
One way to achieve this could be to add a "temporary folder" option to `renku dataset export` to extract the dataset content at a specific tags into a directory.

**Comment by Panaetius** [comment]
Where should it be checked out to? How to prevent a user from working with an old dataset in his project. We don't want an old version checked in or `renku dataset add` called on an old version.

**Comment by cmdoret** [comment]
How about exporting it to `<data_directory>/<ds-name>-<ds-tag>` to make the separation from the latest dataset clear ?
Alternatively, this could be a tarball.

**Comment by Panaetius** [comment]
Simply treat it as an export to a folder, irrespective of where that folder is (we assume it's unrelated to the project).

Include metadata as a yaml file.
