### ISSUE TITLE
Add JSON-LD as a log output format

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-python#293]
The metadata format used in `Renku` is de-facto json-ld, so it would make sense to serve lineage information using json-ld.

**Describe the solution you'd like**
Add `json-ld` as a valid format option for `renku log` command.
The lineage descriptors are expected to use the provo terms.

**Additional context**
This is needed to progress on metedata Knowledge representation within Renku. As the lineage information is currently handled by `renku-python`, this is the first place to start for producing json-ld metadata to be consumed across the platform.

**Comment by rokroskar** [comment]
closed via #299
