### ISSUE TITLE
feat: use existing remote image on local session launch

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#2934]
If an image has been built on the remote renkulab's CI, we should not need to build it again locally. Instead, we should just launch with the remote image. #2880 is already doing some image checks on the remote registry so we should be able to reuse some of the same logic. This would save a lot of time for users wanting to replicate cloud sessions on local machines. Caveat: not sure what to do about authentication with the docker registry for private projects.

**Comment by Panaetius** [comment]
Only for public projects. Followup issue for private projects (probably needs modification of gateway for authentication)
