### ISSUE TITLE
`date_modified` on datasets is set incorrectly

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-python#2957]
**Describe the bug**
`date_modified` property on the datasets is always set to current date/time which is not correct: https://github.com/SwissDataScienceCenter/renku-python/blob/add433e3b52854b5546bf9c57a09e893c3ff0d7b/renku/domain_model/dataset.py#L367
A manifestation of this bug is visible in `renku log`.

**To Reproduce**
1. `renku clone git@renkulab.io:rok.roskar/atmospheric-vertical-profiles.git`
2. `renku log`
3. See `Date` on each entry

**Expected behavior**
- `date_modified` should get its value from the persisted value
- migration must set proper `date_modified` on the datasets; we can use `date_created` or commit date/time
- current values for this field should be fixed either by a `renku doctor` fix or by using `date_created`

**Comment by olevski** [comment]
@mohammad-alisafaee I cannot replicate this.

After doing the above steps this is what I see:

```
Dataset atmospheric-vertical-profiles
Date: 2022-06-15T21:15:33+00:00
Changes: deleted

Dataset atmospheric-vertical-profiles
Date: 2022-06-15T21:15:33+00:00

Dataset atmospheric-vertical-profiles
Date: 2022-06-15T21:15:33+00:00
Changes: created
Title set to: atmospheric-vertical-profiles
Creators modified:
        + Jen Thomas <jenny.thomas@epfl.ch>
```

According to the issue and what you describe above then I should have seen todays date on all dates. Correct?

So this can just be closed.
