### ISSUE TITLE
Data lineage is not preserved with output data directories

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-python#300]
**Describe the bug**
Renku version 0.2.0rc2.dev20180824

Using renku run on a command that generates files in a new directory preserve the lineage of the directory, but not the lineage of the files created inside the directory. It has the expected behavior if we change the parameters of the run command (see example below). Also, creating the directory and committing it (with a .gitkeep file, because the directory cannot be empty) before running the command has the expected behavior.

**To Reproduce**

#Run once, swap with renku run command in comment, repeat.

```
rm -rf break-v0.2.0rc2.dev20180824
mkdir break-v0.2.0rc2.dev20180824
pushd break-v0.2.0rc2.dev20180824
renku init
renku dataset create foo
renku dataset add foo https://github.com/SwissDataScienceCenter/renku/blob/master/README.rst
echo  '#!/usr/bin/env bash
mkdir -p bar 
for i in {1..4}; do
cp data/foo/README.rst ./bar/README.$i
done
' > cmd.sh
chmod u+x cmd.sh
git add cmd.sh
git commit -m "cmd.sh"
#renku run ./cmd.sh bar data/foo/README.rst
renku run ./cmd.sh -out bar -in data/foo/README.rst
renku log
popd
```

**Expected behavior**

Expected output of renku log:

```
*  7900e314 bar/README.4
| *  7900e314 bar/README.3
|/
| *  7900e314 bar/README.2
|/
| *  7900e314 bar/README.1
|/
*  7900e314 .renku/workflow/b1256ce35c4145c392a72c12f757221f_cmd.sh_bar.cwl
@  d8116789 data/foo/README.rst
```

Actual output of renku log:

```
@  258e5608 bar/README.1

*  258e5608 bar
*  258e5608 .renku/workflow/965d656e559841308ffc42b589491cc0_cmd.sh.cwl
@  7d5c8942 data/foo/README.rst

@  258e5608 bar/README.2

@  258e5608 bar/README.3

@  258e5608 bar/README.4
```

**Desktop (please complete the following information):**
Tried on Mac OS X (10.11.6).

**Comment by jirikuncar** [comment]
It's a limitation of current version. We need to find a way how to create a virtual nodes that do a selection of a file from the given directory.

```
*  7900e314 bar/README.4
|           (part of output directory)
| *  7900e314 bar/README.3
|/            (part of output directory)
| *  7900e314 bar/README.2
|/            (part of output directory)
| *  7900e314 bar/README.1
|/            (part of output directory)
* 7900e314 bar # DIRECTORY!!!
* 7900e314 .renku/workflow/b1256ce35c4145c392a72c12f757221f_cmd.sh_bar.cwl
@ d8116789 data/foo/README.rst
```
