### ISSUE TITLE
Data is not automatically tracked by git-lfs in projects created from the UI

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-python#302]
**Describe the bug**
renku dataset add has different behavior depending on whether the project is created from the UI, or with the renku CLI.

**To Reproduce**
renku --version (local): 0.2.0rc2.dev20180824

Create a new project from the UI, clone the project locally, and in the local repo, create a data set and add data to it with the renku command line. The new data is not tracked by git lfs (there's no .gitattributes file).

**Expected behavior**
I expect the data to be tracked by git lfs. This is the behavior we get when adding data to a project created with renku init.

**Comment by jirikuncar** [comment]
This is related to #213
