### ISSUE TITLE
Enable using s3 credentials for more than one S3 service

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-python#3064]
Related to: https://github.com/SwissDataScienceCenter/renku-python/pull/3047

Currently the credentials can only be added for a single s3 endpoint/service. So for example if one bucket you want to access is hosted on AWS s3 and another on minio or elsewhere users would not be able to use both.

The `s3://` prefix is only tied to one set of credentials. And we are allowing only s3:// to be used as a prefix for s3 buckets.

`ProviderCredentials::get_credentials_section_name` can be used to enable this functionality.

**Comment by Panaetius** [comment]
@mohammad-alisafaee this was implemented, correct?

**Comment by mohammad-alisafaee** [comment]
Right.
