### ISSUE TITLE
cwl: mark directory as output if a file has been added there

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#309]
**Describe the bug**

An empty directory should be marked as output if a file is created there.

**To Reproduce**
1. `mkdir output`
2. `renku run python -c 'import sys, pathlib; (pathlib.Path(sys.argv[1]) / sys.argv[2]).touch()' output test`

**Expected behavior**

- [x] `renku log` must show "output" as output directory.
- [x] there must be no inputs files/directories
- [ ] ~~initial working directory requirement should be parametrized~~
- [x] there are no individual files as output

**Comment by erbou** [comment]
Fix worked for me. It also fixed #300.

**Comment by jirikuncar** [comment]
@erbou I will keep #300 open since I need to fix the relations between directories and files.
