### ISSUE TITLE
cwl: support scatter

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#310]
**Is your feature request related to a problem? Please describe.**

Process multiple files from a directory.

**Describe the solution you'd like**

Apply tool on multiple inputs (https://github.com/Gibbsdavidl/CWL_scatter_example).

**Describe alternatives you've considered**

Use git branches and merge.

**Comment by jirikuncar** [comment]
```
renku foreach NAME --glob="inputs/*.txt" run python {NAME} outputs/{NAME}.pdf
```

**Comment by Panaetius** [comment]
Duplicate of https://github.com/SwissDataScienceCenter/renku-python/issues/1875
