### ISSUE TITLE
add a workflow export endpoint on the core service

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#3190]
We should add a `workflow_plans.export` endpoint to the core service that exposes `renku workflow export` functionality. It should take a git url, branch, workflow name or id and target format (limited to CWL at the moment) and return valid CWl code in its payload.

This feature is useful for smartsky, as it makes it easy to use in other service for executing workflows.

**Comment by rokroskar** [comment]
cc @volodymyrss
