### ISSUE TITLE
remove v8 support

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#3206]
Back when we introduced API versioning, we said we'd support old metadata versions for 6 months after a new version is introduced. We're well past that point for v8 and as such, should phase it out.

So remove v8 from our chart and coordinate with the UI to remove it on their side as well.

We should keep the code for it around though so we can easily support v9 once we move to v10.

**Comment by olevski** [comment]
Double check what happens in the ui when we remove v8.

**Comment by Panaetius** [comment]
As per Lorenzo, the UI uses our /versions endpoint to see what is supported, so if that doesn't return `v8`, UI won't use v8. But a good idea still to double-check that.
