### ISSUE TITLE
Add documentation for running `renku session start` on a headless remote 

### ISSUE THREAD

**Issue by lokijuhy** [SwissDataScienceCenter/renku-python#3229]
We are aiming to support non-browser-based ways of interacting with Renku. One of these common modes of interaction that we should support is running a session on a headless remote machine. We have users that enjoy using Renku, but need more resources than are available on RenkuLab.io, and so would like to run Renku sessions on their own hardware. 

The scope of this task is to add documentation to the [Run a Renku Sessions on your Own Machine](https://renku.readthedocs.io/en/latest/how-to-guides/own_machine/session-running-locally.html) page for how to run a renku session on a remote and be able to view the session in a browser window on the local machine. 

This _might_ be as simple as the following:
* `ssh` to your remote
* Run `renku session start`
* Copy the port number it gives you
* Open a second ssh connection that opens that port
* Copy and paste the session url into your local browser

But maybe you have better ideas on how to accomplish this more elegantly, which is why I'm handing this task over to you! :) That said, it is _not_ necessarily in scope of this issue to change how `renku session start` works to make this process more elegant - if the workflow is ugly for now, that's ok. I'd rather get some hacky (but clear!) documentation up there quickly, and we can consider crafting a more elegant workflow in the future. 

FYI The Slack conversation where I first mentioned this is [here](https://swiss-data-science.slack.com/archives/G67N59QL8/p1669648150002889).

**Comment by olevski** [comment]
@lokijuhy just to make sure we are on the same page. The steps a user would take for this are:

1. Start a VM somewhere that is accessible via SSH (assuming this is at `my.vm.io`)
2. SSH into the VM
3. From the VM run `renku session start`, note the port where the session is running - lets assume this is `8888`
4. From the local computer run `ssh -L 8888:localhost:8888 user@my.vm.io`
5. From the local computer open browser at `http://localhost:8888/` and work with the session

Have you actually tried this? I think it should work but I am just curious. We should definitely confirm it works as expected when we write the docs.

**Comment by RichardJActon** [comment]
I've done this before with ssh port forwarding and over the wireguard mesh vpn I use tailscale.

Actually might be worth noting here that when running a docker service on 0.0.0.0 it exposes the ports on your system if your using ufw or similar iptables based firewalls and 127.0.0.1 might be a better default from a security perspective. So by deefault you wouldn't need the port forwarding if you're on the same local network and just use the ip of the host it's running on.

see: https://askubuntu.com/questions/652556/uncomplicated-firewall-ufw-is-not-blocking-anything-when-using-docker
