### ISSUE TITLE
Plan invalidation date is before plan creation date

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-python#3239]
When removing plans in `renku.core.workflow.plan::remove_plan`, last derivation's creation date is set after its deletion date.

We should fix this either by instantiating creation date object before the deletion date one (a bit tricky since deletion date is passed to the function) or by setting the creation date to be equal to the deletion date.

We also need a migration to fix older projects.

**Comment by mohammad-alisafaee** [comment]
On a separate note, should we keep the creation date, set to the initial creation date and add a modification date field similar to what we do for datasets?

**Comment by Panaetius** [comment]
I think this was fixed in 2.0.0
