### ISSUE TITLE
Problems pushing many large files, server closing connection

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-python#327]
I am trying to create some medium size datasets, around 15Gb one, and another around 40Gb. Both are composed by many small `gz` files, all below 500Mb.

I just want to report that, when doing `renku dataset add ./<some set of folders>`, and then `git push`, the operations fails and it prompts the following

```
Connection to domain.com closed by remote host.
fatal: The remote end hung up unexpectedly
```

I was trying with just 20 files (10 folders) of 1.5Gb in total, and I believe the problem was during the compression process

I solved this by bashing the process and adding and pushing one by one, and it is working fine. But I open the issue because I believe it should be possible to do this all at once.

**Comment by jirikuncar** [comment]
This looks like a LFS server problem.

**Comment by rokroskar** [comment]
I think this was due to a misconfiguration of LFS. Closing for now -- please reopen if this is not the case!
