### ISSUE TITLE
Mappings can have an empty default value which SHACL doesn't accept

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#3274]
if I just do `renku workflow compose -m my_map=run1.my_param my_composite run1 run2`, I get a mapping without a default value, which is perfectly fine. if a mapping has no default value and no value is specified, execution just takes the default value of the mapped to parameters.

When cleaning up our SHACL a while back, we added https://github.com/SwissDataScienceCenter/renku-python/blob/develop/renku/data/shacl_shape.json#L1638 which breaks in this case. Either we make it so the schema also exports defaultValue when it's None, or we remove that constraint.

**Comment by Panaetius** [comment]
@mohammad-alisafaee this is fixed, right?

**Comment by mohammad-alisafaee** [comment]
Right, it's fixed by https://github.com/SwissDataScienceCenter/renku-python/pull/3326
