### ISSUE TITLE
bug: toil is not installed as a required dependency

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#3275]
**Describe the bug**

Installing renku from PyPI does not also install `toil` as a required dependency, causing update/rerun operations to fail. 

**To Reproduce**

```
virtualenv venv-renku
source venv-renku/bin/activate
pip install renku
renku run -h
...
--provider [local|cwltool]  The workflow engine to use for executing
                              workflow files.
...
```
This last line should include `toil`. 

cc @lokijuhy

**Comment by Panaetius** [comment]
Already fixed in https://github.com/SwissDataScienceCenter/renku-python/pull/3272

**Comment by rokroskar** [comment]
It's also a problem with `1.11.0` which already has that fix: https://github.com/SwissDataScienceCenter/renku-python/blob/1.x-lts/pyproject.toml#L139
