### ISSUE TITLE
update cwltool to resolve conflicts with jupyter

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#328]
**Describe the bug**
mistune version mismatch causes conflicts with newer versions of the Jupyter stack and current cwltool/schema-salad requirements

**To Reproduce**
install renku-python from source together with jupyterlab

**Expected behavior**
installation should succeed

**Additional context**
can be fixed by bumping the cwltool version requirement

**Comment by leafty** [comment]
As this can happen again in the future, a good idea could be to document sandbox installs, e.g. in its own environment (see: renku/singleuser).
