### ISSUE TITLE
renku session start fails on a newly initialized local repo

### ISSUE THREAD

**Issue by RichardJActon** [SwissDataScienceCenter/renku-python#3298]
## Describe the bug

If I initialize a new project with `renku init <name>` then try to run `renku session start` in that project I get an error (see below). If I create the project in the renkulab.io gitlab and add it as a remote it starts working if I'm logged in and the project is public this seems related to #3291 which appears to be being fixed in #3292 which @mohammad-alisafaee is working on. I'm not sure if behavior would also be resolved by the fixes in that PR.

It would be nice to have an option to force local building of the docker image and block the default behavior of looking for an image on a remote `--local-build` or something. Not sure what the current default behavior is if you run `renku session start` when not logged in but it might be nice to have a prompt to login to look for pre-built images or build locally if you don't specify build locally with this option.

## Details
*Please verify and redact the details.*

**Renku version:** 2.1.0
**OS:** Linux (#64-Ubuntu SMP Thu Jan 5 11:43:13 UTC 2023)
**Python:** 3.10.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "[...]/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/local-only-docker:55db5a7/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/renku/core/session/docker.py", line 83, in find_image
    self.docker_client().images.get(image_name)
  File "[...]/docker/models/images.py", line 314, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "[...]/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "[...]/docker/api/image.py", line 251, in inspect_image
    return self._result(
  File "[...]/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "[...]/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "[...]/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/local-only-docker:55db5a7/json: Not Found ("no such image: local-only-docker:55db5a7: No such image: local-only-docker:55db5a7")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "[...]/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http+docker://localhost/v1.41/distribution/local-only-docker:55db5a7/json

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/session.py", line 222, in start
    session_start_command()
  File "[...]/renku/command/command_builder/command.py", line 252, in execute
    output = self._operation(*args, **kwargs)  # type: ignore
  File "pydantic/decorator.py", line 40, in pydantic.decorator.validate_arguments.validate.wrapper_function
  File "pydantic/decorator.py", line 134, in pydantic.decorator.ValidatedFunction.call
  File "pydantic/decorator.py", line 206, in pydantic.decorator.ValidatedFunction.execute
  File "[...]/renku/core/session/session.py", line 92, in session_start
    if not provider_api.find_image(image_name, config):
  File "[...]/renku/core/session/docker.py", line 86, in find_image
    self.docker_client().images.get_registry_data(image_name)
  File "[...]/docker/models/images.py", line 335, in get_registry_data
    attrs=self.client.api.inspect_distribution(name, auth_config),
  File "[...]/docker/utils/decorators.py", line 34, in wrapper
    return f(self, *args, **kwargs)
  File "[...]/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "[...]/docker/api/image.py", line 287, in inspect_distribution
    return self._result(
  File "[...]/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "[...]/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e)
  File "[...]/docker/errors.py", line 31, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation)
docker.errors.APIError: 403 Client Error for http+docker://localhost/v1.41/distribution/local-only-docker:55db5a7/json: Forbidden ("errors:
denied: requested access to the resource is denied
unauthorized: authentication required
")
```

**Comment by mohammad-alisafaee** [comment]
Hello @RichardJActon,

Thanks for taking the time to report this!

As you've guessed the PR https://github.com/SwissDataScienceCenter/renku-python/pull/3292 fixes this problem as well. We'll make a release with this fix early next week. Meanwhile, you can install Renku from that PR's branch to have the fix.

Regarding your suggestion for a `--local-build`, I'll discuss it with our team to see if and how we are going to support it. As a (not ideal) workaround, you can remove the git repository's remote (e.g. `git remote remove origin`) and then try to start the session; in this way, Renku cannot find the remote image and prompts to build it locally.

Please note that you don't need to login for checking/downloading images of public projects; login is required for accessing your sessions on a Renku deployment. ATM, Renku doesn't support downloading image for private projects and will always prompt to build them locally.

Kind regards,
Mohammad

**Comment by rokroskar** [comment]
Hi @RichardJActon regarding the local builds, I'm trying to understand what you have in mind - the current behavior is to pull an existing image if it exists in order to save time. If it doesn't exist, we build it locally. Are you suggesting to override this by ignoring the remote image? I can see this being useful if you are iterating on a Dockerfile and just want to always build the local changes. However I'm also wondering how far we should go in wrapping docker functionality before just instructing the user to do `docker build`...

**Comment by RichardJActon** [comment]
Hi @rokroskar, Yes it is mostly for that use case of iterating on a local Dockerfile. Also maybe Mohammad's PR resolves it but I've had a few situations where failing to find a remote image has not failed gracefully i.e. just produced an error and not fallen back on a local build so I've found myself wanting to force a local build to get around this. 

I think I tried it with just `docker build` commands once a while back but `renku session start` seems to be wrapping a couple of other things like keeping the naming convention of images consistent, picking a port, starting the container, and that login token you get in the address for the session. It's a few extra slightly non-obvious steps to get the exact same result as having the renku cli fail to find a remote image and building one locally instead.

**Comment by RichardJActon** [comment]
So the path the lead me to suggesting something like `renku session start --local-build` went something like this.  

I was initially working just in the renkulab.io environment where the use of docker is pretty well wrapped. I can iterate on an image in the webui and gitlab CI will try and build it and I can go debug my Dockerfile if the build fails or it doesn't do what I expected but it's a bit of a long feedback loop though and means I have to commit the intermediate steps of my debugging a Dockerfile to the repo.  

So I tried running sessions locally do some slightly faster trial and error. This was a fairly inconsistent experience as sometimes it'd successfully pull a pre-built image from a public project, sometimes I'd get some kind of error where an image was not able to be found and sometimes It'd try and build locally. The main issue was the situations where it would produce an error fetching an image and not fallback on a local build and then I was faced with the option of reverse engineering how Renku normally wraps the docker build process when it successfully falls back on a local build. I poked at this a bit couldn't immediately replicate the effect of a successful `renku session start` with simple docker commands, not knowing how complex this wrapper layer is or how much work it's going to be to figure it out how to replicate the steps manually defaulted back to building on renkulab as this was a known quantity.

It seems like not being able to force a local build with the cli app produces a slightly worse experience than you get through the web client where you can effectively force a build with the CI.  

Whilst it would be possible to document the manual steps to have the same effect as running  `renku session start` and having it fall back over to a local build with docker commands it seems like some unnecessary extra steps for the user. If I've built my own dockerised environment I know how to interact with it with native docker commands but if renku has already wrapped enough of the process of starting a docker session that it has made some choices about how to interact with that session then I now have a gap in my understanding of how to start a docker session in the 'renku style'.  

If I wanted to do anything more custom or complicated then It makes sense that the design should expect me to learn 'renku's opinions' about how to start, build, & run a docker session in order to customise them. I should have to go read the docs for anything more than this but I'd say forcing a local build is on the side of the line of it makes sense to wrap this docker functionality but just before where it does not. Forcing a local build is more along the lines of I want to adopt renku's conventions for spinning up a docker container without having to know what those are. That way I can still customise the contents of the container  and still interact with it in a 'renku-ish' way.  

Sorry for the essay - wanted to spell out the user experience that got me here

**Comment by rokroskar** [comment]
Thanks @RichardJActon that makes a lot of sense. So in this case, `--local-build` would _always_ trigger the build locally - I'd say it could still pull the remote image if available, but then kick off the build. Then you also benefit from any cached layers that might exist. @Panaetius should we make a separate issue for this?

**Comment by Panaetius** [comment]
This is sort of supported using the `--image` argument, where you can set an arbitrary image name that isn't pushed, so forcing a local build.

`--local-build` would surely map to the user intent more closely, at the cost of having more options/making the command more confusing. I think I'd prefer a `--no-pull`/`--skip-pull` option either way.

**Comment by rokroskar** [comment]
@Panaetius I don't follow - so if you set `--image` it doesn't just try to use the image you specify but actually builds a new one and gives it that name?

**Comment by rokroskar** [comment]
@RichardJActon I think this is the part I missed

> then I was faced with the option of reverse engineering how Renku normally wraps the docker build process when it successfully falls back on a local build.

As @Panaetius pointed out - there is nothing special in the build; so if you do a standard `docker build -t <tag> .` the image should build just fine. Theny you can do `renku session start --image <tag>` to use the image you just built locally. Does that come close enough to what you need?

**Comment by RichardJActon** [comment]
OK nice, now I know there's nothing extra in the in the docker build command and, from the help for `renku session start`, that I can start a renku session with a specific image using the `--image` flag I can do the following if I want an image that follows a similar naming convention but indicates it's from working changes on top of the latest commit.

```
TAG=$(printf "registry.renkulab.io/hdbi/data-management/hdbi-data-resource:%s-wd" $(git rev-parse --short HEAD))
docker build -t $TAG .
renku session start --image $TAG
```

This works OK for _ME_. It's 2-3 lines instead of one and a context switch over to docker commands instead of renku cli commands. Which is why I still think an option for a local build without having to drop back to running docker commands would be helpful for renku users with less docker experience if they encounter the need to prefer a local build (e.g. somewhere with a bad internet connection).
