### ISSUE TITLE
Allow updating renamed Renku templates

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-python#3305]
Renku project template IDs (directories) have been renamed in version `0.4.1` (`minimal` postfix was removed). This causes the template update logic to ignore newer template versions since it cannot find previous IDs. This needs to be fixed by searching for the new IDs when updating.

**Additional context**
UI uses Renku template repository's URL as template source (instead of `"renku"`) for Renku templates.

**Workaround**
We can use `renku template set -f <new-id>` to manually enable updates.

**Comment by Panaetius** [comment]
Add aliases for renamed templates or add a separate "displayname" property for what is shown to the user.
