### ISSUE TITLE
Add an option to push after run

### ISSUE THREAD

**Issue by leafty** [SwissDataScienceCenter/renku-python#331]
**Is your feature request related to a problem? Please describe.**
Have the option to push results after a `renku run` (or `update`, `rerun`, etc.).

When using `renku-python` on renkulab.io, the server instance will be culled after some inactivity.
This means that one has to monitor long running jobs to not lose their work.
I avoided this by doing:
```bash
git checkout -b current-work
renku run <...> && git push -u origin current-work
```
It would be nice to have all that compacted in the `renku run` command.

**Describe the solution you'd like**
Add an option to relevant commands: `--push`.
The option will make it so that before the run command:
- a new branch is created (maybe with a timestamp or a unique string)

After the run command (which means after the commit):
- the commit is pushed back to the source repository

**Describe alternatives you've considered**
Using:
```bash
renku run <...> && git push -u origin current-work
```

**Additional context**
Using `&& git push` meant I did not lose my work after I accidentally stopped my jupyter instance.

**Comment by jirikuncar** [comment]
The branch name can be the name of CWL tool file created by `renku run`.

I would move the automatic push to `renku-jupyterlab-ts` extension for now.

**Comment by leafty** [comment]
> The branch name can be the name of CWL tool file created by renku run.

can you prepend the `git author` name e.g. `leafty-3453jdjsjs32`? I think this would make it quite easy to recognize the new branch.

**Comment by jirikuncar** [comment]
> > The branch name can be the name of CWL tool file created by renku run.
> 
> can you prepend the `git author` name e.g. `leafty-3453jdjsjs32`? I think this would make it quite easy to recognize the new branch.

The question is if we want to encourage work on forks or in the `upstream`. For pushes to `upstream` it makes sense to include username as prefix, although I am fan of prefixing by issue (ku) number (e.g. `123-trained-prediction-model`).

**Comment by leafty** [comment]
the point is to run and push no matter what, so the branch name should be unique, but users should still have a way to sort out the result.

**Comment by rokroskar** [comment]
This has been addressed with the autosave functionality.
