### ISSUE TITLE
No write permissions when running renku on an own machine

### ISSUE THREAD

**Issue by rawlik** [SwissDataScienceCenter/renku-python#3321]
**Describe the bug**
When a renku session on an own machine the ids of the files in the container remain the same as on the host machine, which makes them impossible to modify and to create new files.

**Expected behavior**
When I start a renku session on my own machine I can modify and create files inside that session.

**Run environment (please complete the following information):**
renku 2.2.0

**Comment by Panaetius** [comment]
@rawlik Thank you for reporting this issue and the great description. I've moved it to the right repository and we'll look into it in the next sprint

**Comment by Panaetius** [comment]
I can't reproduce this on my machine.
```
$ renku init test-docker-session
$ cd test-docker-session
$ renku session start -p docker
[...]
The session for 'test-docker-session:44d02e3' has been successfully started. It is available at:
        http://0.0.0.0:32768/?token=73291e0fb9b945cf94300ac0ed8d7ccc
[...Open URL above and add file 'test.txt' in the notebook...]
$ ls -l |grep test
-rw-r--r-- 1 user   100    0 Feb 28 11:47 test.txt
```
tested with renku version 2.3.0 on Linux.

Can you reproduce the error and write the exact commands executed/steps taken? What operating system?

**Comment by rawlik** [comment]
I just did exactly the same, selecting "python-minimal", and have no write permissions.

Ubuntu 20.04.4 LTS (GNU/Linux 5.13.0-51-generic x86_64)
Docker version 20.10.22, build 3a2c30b
renku 2.3.0


It may be important that my uid and gid are different from jovyan's:
```
(base) rawlik_m@magnifico:~/renku/test-docker-session$ id
uid=1004(rawlik_m) gid=1003(rawlik_m) groups=1003(rawlik_m),27(sudo),132(sambashare),998(docker)
```
In a renku session:
```
base ▶ ~ ▶ work ❯ test-docker-session ▶ $ ▶ id
uid=1000(jovyan) gid=100(users) groups=100(users)
```
