### ISSUE TITLE
Remove `--move`, `--copy`, and `--link` from `dataset add` options

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-python#3333]
**Is your feature request related to a problem? Please describe.**
I found `--move`, `--copy`, and `--link` flags complicated when adding files to a dataset. They also make the implementation much more complex since we need to address all these cases. 

**Describe the solution you'd like**
In most cases, users want to copy files to a dataset's data directory when adding files to it. We should always copy files and remove all these options. The only drawback is that files that are parts of more than one dataset are duplicated. This only results in consuming more local disk space; if those files are large then they reside in LFS but then there is only one copy of these files in LFS because it uses file hash to store them. Moving files to another dataset is also possible using `renku mv` command.

We also need to migrate old projects to have the same structure everywhere.

**Comment by Panaetius** [comment]
Should run this by Laura

**Comment by mohammad-alisafaee** [comment]
The decision was to keep them: https://swiss-data-science.slack.com/archives/C04QPJ9T8LF/p1677231750742909.

**Comment by mohammad-alisafaee** [comment]
We should then prompt these options for files that are inside the project's directory and not for those that are outside. For example, we don't support `--link` for files that are outside the project.

We could also set a default action in the options and don't prompt users every time.

**Comment by Panaetius** [comment]
And a config option that a user can use to set the desired default action
