### ISSUE TITLE
Template update with user-modified Dockerfile

### ISSUE THREAD

**Issue by mohammad-alisafaee** [SwissDataScienceCenter/renku-python#3354]
**Is your feature request related to a problem? Please describe.**
When updating a project's template, if user has modified the Dockerfile we don't overwrite it by default. This results in a template with the latest version but with an incomplete Dockerfile. If latest template version has a feature that requires Dockerfile to be updated then project will be in a (somehow) broken state.

**Describe the solution you'd like**
The update operation should fail and users should resolve Dockerfile conflicts manually.

**Describe alternatives you've considered**
Add a Renku-specific section to the Dockerfile and use it for Renku-related features similar to what we do for git hooks: https://github.com/SwissDataScienceCenter/renku-python/blob/4220f4eb807b8ce51cb374dcbc435012fcdcda75/renku/data/pre-commit.sh#L21

**Comment by Panaetius** [comment]
Should work together with the UI since they are overhauling the status check
