### ISSUE TITLE
issue using "renku save"

### ISSUE THREAD

**Issue by carlottaolivero** [SwissDataScienceCenter/renku-python#3355]
Hi,
I was sawing the data using renku save and this message appears.
Can you help me in solving the issue?
Thank you very much

 base > ~ > work ❯ test-ww-13-01-23 > master > 5? > $ > **renku save**
Info: Adding these files to Git LFS:
        miniconda3/pkgs/cache/497deca9.q
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0/sbin/kdb5_util
        miniconda3/include/unicode/calendar.h
        miniconda3/pkgs/python-fastjsonschema-2.16.3-pyhd8ed1ab_0.conda
        miniconda3/pkgs/openssl-1.1.1s-h7f8727e_0/include/openssl/obj_mac.h
        miniconda3/pkgs/cache/a0b50a38.q
        miniconda3/include/zstd.h
        miniconda3/pkgs/libgcc-ng-11.2.0-h1234567_1/share/info/libgomp.info
        miniconda3/pkgs/libgomp-11.2.0-h1234567_1.conda
        miniconda3/pkgs/cache/2a957770.json
        miniconda3/pkgs/readline-8.2-h5eee18b_0.conda
        miniconda3/pkgs/setuptools-65.6.3-py310h06a4308_0/info/paths.json
        miniconda3/pkgs/libsolv-0.7.23-h3eb15da_0.conda
        miniconda3/pkgs/openssl-1.1.1s-h7f8727e_0/bin/openssl
        miniconda3/pkgs/ld_impl_linux-64-2.40-h41732ed_0.conda
        miniconda3/pkgs/ld_impl_linux-64-2.38-h1181459_1/bin/x86_64-conda-linux-gnu-ld
        miniconda3/pkgs/c-ares-1.18.1-h7f98852_0.tar.bz2
        miniconda3/pkgs/pip-22.3.1-py310h06a4308_0/info/paths.json
        miniconda3/pkgs/cache/2ce54b42.q
        miniconda3/bin/nghttpd
        miniconda3/pkgs/python-3.10.9-he550d4f_0_cpython.conda
        miniconda3/pkgs/cffi-1.15.1-py310h255011f_3.conda
        miniconda3/pkgs/python-3.10.9-he550d4f_0_cpython/info/paths.json
        miniconda3/bin/kadmin
        miniconda3/bin/python3.10
        miniconda3/pkgs/icu-70.1-h27087fc_0.tar.bz2
        miniconda3/pkgs/setuptools-67.5.1-pyhd8ed1ab_0/site-packages/setuptools/cli-arm64.exe
        miniconda3/pkgs/readline-8.1.2-h0f457ee_0.tar.bz2
        miniconda3/pkgs/openssl-3.0.8-h0b41bf4_0.conda
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0/include/krb5/krb5.h
        miniconda3/pkgs/openssl-3.0.8-h0b41bf4_0/include/openssl/obj_mac.h
        working/samples/20230220/torino/raw_data/23BL00087TO_R2.fastq
        miniconda3/pkgs/sqlite-3.40.0-h4ff8645_0/bin/sqlite3
        miniconda3/pkgs/jinja2-3.1.2-pyhd8ed1ab_1.tar.bz2
        miniconda3/pkgs/libnghttp2-1.52.0-h61bc06f_0/bin/nghttpx
        miniconda3/pkgs/libarchive-3.6.2-h3d51595_0/bin/bsdcpio
        miniconda3/pkgs/openssl-3.0.8-h0b41bf4_0/include/openssl/ssl.h
        miniconda3/pkgs/cache/09cdf8bf.json
        miniconda3/pkgs/brotlipy-0.7.0-py310h7f8727e_1002.conda
        miniconda3/pkgs/python-3.10.9-h7a1cb2a_0.conda
        miniconda3/pkgs/cache/4ea078d6.json
        miniconda3/pkgs/psutil-5.9.4-py310h5764c6d_0.tar.bz2
        miniconda3/pkgs/brotlipy-0.7.0-py310h5764c6d_1005.tar.bz2
        miniconda3/pkgs/pyrsistent-0.19.3-py310h1fa729e_0.conda
        miniconda3/pkgs/ruamel.yaml.clib-0.2.7-py310h1fa729e_1.conda
        miniconda3/conda-meta/conda-23.1.0-py310hff52083_0.json
        miniconda3/pkgs/libgomp-12.2.0-h65d4601_19.tar.bz2
        miniconda3/pkgs/pycosat-0.6.4-py310h5764c6d_1/info/recipe/qg3-08.cnf
        miniconda3/pkgs/bzip2-1.0.8-h7f98852_4/bin/bzcat
        miniconda3/pkgs/zstd-1.5.2-h3eb15da_6.conda
        miniconda3/pkgs/libcurl-7.88.1-hdc1c0ab_0.conda
        miniconda3/pkgs/libnghttp2-1.52.0-h61bc06f_0.conda
        miniconda3/pkgs/bzip2-1.0.8-h7f98852_4.tar.bz2
        miniconda3/pkgs/python-3.10.9-he550d4f_0_cpython/info/files
        miniconda3/pkgs/zlib-1.2.13-h5eee18b_0.conda
        miniconda3/pkgs/libgcc-ng-12.2.0-h65d4601_19/share/info/libgomp.info
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0/info/paths.json
        miniconda3/include/unicode/unistr.h
        miniconda3/pkgs/icu-70.1-h27087fc_0/bin/genrb
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0/sbin/kadmind
        miniconda3/pkgs/zstd-1.5.2-h3eb15da_6/bin/zstd
        miniconda3/pkgs/fmt-9.1.0-h924138e_0/include/fmt/format.h
        miniconda3/include/nghttp2/nghttp2.h
        miniconda3/sbin/kadmin.local
        miniconda3/pkgs/zstandard-0.19.0-py310hdeb6495_1.conda
        miniconda3/pkgs/cache/09cdf8bf.q
        miniconda3/pkgs/pycosat-0.6.4-py310h5764c6d_1/info/test/qg3-08.cnf
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0/sbin/krb5kdc
        miniconda3/pkgs/ld_impl_linux-64-2.38-h1181459_1.conda
        working/samples/20230220/torino/raw_data/23BL00087TO_R1.fastq
        miniconda3/pkgs/libev-4.33-h516909a_1/share/man/man3/ev.3
        miniconda3/pkgs/openssl-1.1.1s-h7f8727e_0/include/openssl/ssl.h
        miniconda3/pkgs/openssl-3.0.8-h0b41bf4_0/include/openssl/evp.h
        miniconda3/bin/bunzip2
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0.conda
        miniconda3/pkgs/ca-certificates-2023.01.10-h06a4308_0/ssl/cacert.pem
        miniconda3/pkgs/conda-package-handling-2.0.2-py310h06a4308_0/info/test/tests/data/mock-2.0.0-py37_1000.tar.bz2
        miniconda3/pkgs/urllib3-1.26.14-py310h06a4308_0.conda
        miniconda3/pkgs/cache/62c98390.json
        miniconda3/pkgs/snakemake-minimal-7.24.0-pyhdfd78af_1.tar.bz2
        miniconda3/include/coin/CbcModel.hpp
        miniconda3/include/fmt/core.h
        miniconda3/pkgs/docutils-0.19-py310hff52083_1.tar.bz2
        miniconda3/pkgs/python-3.10.9-h7a1cb2a_0/info/paths.json
        miniconda3/pkgs/tzdata-2022g-h04d1e81_0/share/zoneinfo/tzdata.zi
        miniconda3/pkgs/nbformat-5.7.3-pyhd8ed1ab_0.conda
        miniconda3/pkgs/ncurses-6.3-h27087fc_1/include/curses.h
        miniconda3/pkgs/libev-4.33-h516909a_1.tar.bz2
        miniconda3/pkgs/libarchive-3.6.2-h3d51595_0/bin/bsdtar
        miniconda3/pkgs/bzip2-1.0.8-h7b6447c_0/bin/bzip2
        miniconda3/pkgs/cache/47929eba.q
        miniconda3/pkgs/ca-certificates-2022.12.7-ha878542_0.conda
        miniconda3/bin/zstd
        miniconda3/pkgs/coin-or-osi-0.108.7-h2720bb7_2.tar.bz2
        miniconda3/pkgs/bzip2-1.0.8-h7f98852_4/bin/bzip2
        miniconda3/pkgs/ncurses-6.4-h6a678d5_0/info/paths.json
        miniconda3/share/doc/libssh2/NEWS
        miniconda3/pkgs/ncurses-6.4-h6a678d5_0.conda
        miniconda3/pkgs/conda-package-handling-2.0.2-pyh38be061_0.conda
        miniconda3/pkgs/yaml-cpp-0.7.0-h27087fc_2.tar.bz2
        miniconda3/pkgs/coin-or-cgl-0.60.6-h6f57e76_2.tar.bz2
        miniconda3/share/man/man3/ev.3
        miniconda3/bin/bsdtar
        miniconda3/pkgs/setuptools-67.5.1-pyhd8ed1ab_0.conda
        miniconda3/include/coin/CbcOrClpParam.cpp
        miniconda3/sbin/kadmind
        miniconda3/bin/x86_64-conda-linux-gnu-ld
        working/samples/20230213/torino/raw_data/23BL00076TO_R2.fastq
        miniconda3/pkgs/openssl-1.1.1s-h7f8727e_0.conda
        miniconda3/sbin/kdb5_util
        miniconda3/pkgs/ncurses-6.3-h27087fc_1.tar.bz2
        miniconda3/pkgs/libnghttp2-1.52.0-h61bc06f_0/include/nghttp2/nghttp2.h
        miniconda3/pkgs/cache/2a957770.q
        miniconda3/pkgs/lz4-c-1.9.4-hcb278e6_0.conda
        miniconda3/pkgs/cache/9e0f62c3.json
        miniconda3/pkgs/libcurl-7.88.1-hdc1c0ab_0/include/curl/curl.h
        working/samples/20230220/novara/raw_data/23BL00091NO_R1.fastq
        miniconda3/include/openssl/evp.h
        miniconda3/pkgs/libssh2-1.10.0-hf14f497_3.tar.bz2
        miniconda3/pkgs/libgfortran5-12.2.0-h337968e_19.tar.bz2
        miniconda3/pkgs/cache/227b7582.q
        miniconda3/bin/sqlite3
        miniconda3/pkgs/tk-8.6.12-h27826a3_0/include/tclInt.h
        miniconda3/pkgs/certifi-2022.12.7-pyhd8ed1ab_0/site-packages/certifi/cacert.pem
        miniconda3/bin/nghttpx
        miniconda3/pkgs/libmamba-1.3.1-hcea66bb_2/bin/mamba-package
        miniconda3/bin/genrb
        miniconda3/bin/bzcat
        miniconda3/pkgs/pulp-2.7.0-py310hff52083_0.tar.bz2
        miniconda3/pkgs/xz-5.2.10-h5eee18b_1.conda
        miniconda3/pkgs/setuptools-65.6.3-py310h06a4308_0.conda
        miniconda3/pkgs/python-3.10.9-h7a1cb2a_0/bin/python3.10
        miniconda3/pkgs/coin-or-clp-1.17.7-hc56784d_2/include/coin/CbcOrClpParam.cpp
        miniconda3/pkgs/tk-8.6.12-h27826a3_0.tar.bz2
        miniconda3/pkgs/xz-5.2.6-h166bdaf_0.tar.bz2
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0/site-packages/pip/_vendor/distlib/w64.exe
        miniconda3/pkgs/lzo-2.10-h516909a_1000/libexec/lzo/examples/lzotest
        miniconda3/pkgs/conda-package-handling-2.0.2-pyh38be061_0/info/test/tests/data/mock-2.0.0-py37_1000.tar.bz2
        miniconda3/pkgs/tk-8.6.12-h1ccaba5_0/include/tclDecls.h
        miniconda3/pkgs/jsonschema-4.17.3-pyhd8ed1ab_0/site-packages/jsonschema/benchmarks/issue232/issue.json
        miniconda3/include/fmt/format.h
        miniconda3/pkgs/cache/62c98390.q
        miniconda3/pkgs/cffi-1.15.1-py310h5eee18b_3.conda
        miniconda3/pkgs/pyopenssl-23.0.0-pyhd8ed1ab_0.conda
        miniconda3/pkgs/lzo-2.10-h516909a_1000/include/lzo/lzodefs.h
        miniconda3/include/curl/curl.h
        miniconda3/pkgs/tzdata-2022g-h04d1e81_0/info/paths.json
        miniconda3/pkgs/icu-70.1-h27087fc_0/include/unicode/unistr.h
        miniconda3/pkgs/cache/227b7582.json
        miniconda3/pkgs/bzip2-1.0.8-h7b6447c_0/bin/bunzip2
        miniconda3/pkgs/coin-or-clp-1.17.7-hc56784d_2.tar.bz2
        miniconda3/include/unicode/uchar.h
        miniconda3/pkgs/conda-23.1.0-py310h06a4308_0/info/paths.json
        miniconda3/pkgs/cache/47929eba.json
        miniconda3/pkgs/libopenblas-0.3.21-pthreads_h78a6416_3.tar.bz2
        miniconda3/pkgs/cache/f1f1f480.json
        miniconda3/pkgs/icu-70.1-h27087fc_0/include/unicode/uchar.h
        miniconda3/include/openssl/obj_mac.h
        miniconda3/pkgs/sqlite-3.40.1-h5082296_0/bin/sqlite3
        miniconda3/pkgs/coin-or-cbc-2.10.8-h3786ebc_0.tar.bz2
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0.conda
        miniconda3/pkgs/tqdm-4.64.1-py310h06a4308_0.conda
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0/site-packages/pip/_vendor/distlib/w64-arm.exe
        miniconda3/pkgs/icu-70.1-h27087fc_0/include/unicode/calendar.h
        miniconda3/pkgs/cache/ffeee55f.q
        miniconda3/pkgs/certifi-2022.12.7-pyhd8ed1ab_0.conda
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0/site-packages/pip/_vendor/distlib/t64-arm.exe
        miniconda3/bin/bzip2
        miniconda3/pkgs/bzip2-1.0.8-h7b6447c_0/bin/bzcat
        miniconda3/pkgs/fmt-9.1.0-h924138e_0.tar.bz2
        miniconda3/include/tclDecls.h
        miniconda3/pkgs/datrie-0.8.2-py310h5764c6d_6.tar.bz2
        miniconda3/pkgs/tk-8.6.12-h27826a3_0/include/tclDecls.h
        miniconda3/pkgs/cache/4ea078d6.q
        working/samples/20230220/novara/raw_data/23BL00091NO_R2.fastq
        miniconda3/include/krb5/krb5.h
        miniconda3/pkgs/ruamel.yaml.clib-0.2.6-py310h5eee18b_1.conda
        miniconda3/pkgs/python-3.10.9-h7a1cb2a_0/info/files
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0/sbin/kadmin.local
        miniconda3/conda-meta/python-3.10.9-he550d4f_0_cpython.json
        miniconda3/pkgs/pycosat-0.6.4-py310h5eee18b_0/info/test/qg3-08.cnf
        miniconda3/pkgs/zstd-1.5.2-h3eb15da_6/include/zstd.h
        miniconda3/pkgs/cache/f1f1f480.q
        miniconda3/include/unicode/measunit.h
        miniconda3/pkgs/ncurses-6.4-h6a678d5_0/include/curses.h
        miniconda3/pkgs/gitpython-3.1.31-pyhd8ed1ab_0.conda
        miniconda3/pkgs/cache/b35683e8.q
        miniconda3/pkgs/icu-70.1-h27087fc_0/info/test/gb-18030-2000.ucm
        miniconda3/pkgs/libmamba-1.3.1-hcea66bb_2.conda
        miniconda3/pkgs/cache/18414ddb.q
        miniconda3/pkgs/coin-or-cbc-2.10.8-h3786ebc_0/include/coin/CbcModel.hpp
        miniconda3/share/man/man3/libsolv-bindings.3
        miniconda3/include/lzo/lzodefs.h
        miniconda3/pkgs/cryptography-38.0.4-py310h9ce1e76_0.conda
        miniconda3/pkgs/python-3.10.9-he550d4f_0_cpython/bin/python3.10
        miniconda3/pkgs/conda-23.1.0-py310hff52083_0.conda
        miniconda3/pkgs/keyutils-1.6.1-h166bdaf_0.tar.bz2
        miniconda3/pkgs/cache/18414ddb.json
        miniconda3/conda-meta/pip-23.0.1-pyhd8ed1ab_0.json
        miniconda3/pkgs/conda-package-handling-2.0.2-pyh38be061_0/info/test/tests/data/mock-2.0.0-py37_1000.conda
        miniconda3/pkgs/ld_impl_linux-64-2.40-h41732ed_0/bin/x86_64-conda-linux-gnu-ld
        miniconda3/libexec/lzo/examples/lzotest
        miniconda3/pkgs/sqlite-3.40.1-h5082296_0/include/sqlite3.h
        miniconda3/pkgs/libstdcxx-ng-11.2.0-h1234567_1.conda
        miniconda3/pkgs/sqlite-3.40.1-h5082296_0.conda
        miniconda3/share/zoneinfo/tzdata.zi
        working/samples/20230213/novara/raw_data/23BL00080NO_R2.fastq
        miniconda3/pkgs/cryptography-39.0.2-py310h34c0648_0.conda
        miniconda3/pkgs/pycosat-0.6.4-py310h5eee18b_0/info/recipe/qg3-08.cnf
        miniconda3/conda-meta/setuptools-67.5.1-pyhd8ed1ab_0.json
        miniconda3/pkgs/libmambapy-1.3.1-py310h1428755_2.conda
        miniconda3/pkgs/cache/e599ec5e.json
        miniconda3/pkgs/cache/e599ec5e.q
        miniconda3/pkgs/libnghttp2-1.52.0-h61bc06f_0/bin/nghttpd
        miniconda3/pkgs/tk-8.6.12-h1ccaba5_0/info/paths.json
        Miniconda3-latest-Linux-x86_64.sh
        miniconda3/conda-meta/tzdata-2022g-h191b570_0.json
        miniconda3/include/curses.h
        miniconda3/pkgs/libssh2-1.10.0-hf14f497_3/share/doc/libssh2/NEWS
        miniconda3/pkgs/lzo-2.10-h516909a_1000.tar.bz2
        miniconda3/pkgs/lz4-c-1.9.4-hcb278e6_0/bin/lz4
        miniconda3/pkgs/pip-22.3.1-py310h06a4308_0.conda
        miniconda3/pkgs/tk-8.6.12-h1ccaba5_0/include/tclInt.h
        miniconda3/pkgs/libstdcxx-ng-12.2.0-h46fd767_19.tar.bz2
        miniconda3/pkgs/icu-70.1-h27087fc_0/info/recipe/gb-18030-2000.ucm
        miniconda3/pkgs/tzdata-2022g-h191b570_0/share/zoneinfo/tzdata.zi
        miniconda3/pkgs/cache/9e0f62c3.q
        working/samples/20230213/torino/raw_data/23BL00076TO_R1.fastq
        miniconda3/pkgs/ruamel.yaml-0.17.21-py310h5eee18b_0.conda
        miniconda3/pkgs/cache/a0b50a38.json
        miniconda3/include/sqlite3.h
        miniconda3/ssl/cacert.pem
        miniconda3/conda-meta/ncurses-6.3-h27087fc_1.json
        miniconda3/pkgs/cache/497deca9.json
        miniconda3/pkgs/cache/3e39a7aa.json
        miniconda3/bin/bsdcpio
        miniconda3/pkgs/python-fastjsonschema-2.16.3-pyhd8ed1ab_0/info/test/src/tests/examples/issue-109/85e52038-4d69-50e9-9e46-e379b8d830af.json
        miniconda3/pkgs/libxml2-2.10.3-h7463322_0.tar.bz2
        miniconda3/pkgs/tk-8.6.12-h27826a3_0/info/paths.json
        miniconda3/sbin/krb5kdc
        miniconda3/pkgs/urllib3-1.26.14-pyhd8ed1ab_0.conda
        miniconda3/include/openssl/ssl.h
        miniconda3/pkgs/libgcc-ng-12.2.0-h65d4601_19.tar.bz2
        miniconda3/pkgs/ca-certificates-2023.01.10-h06a4308_0.conda
        miniconda3/pkgs/libsolv-0.7.23-h3eb15da_0/share/man/man3/libsolv-bindings.3
        miniconda3/pkgs/coin-or-utils-2.11.6-h202d8b1_2.tar.bz2
        miniconda3/pkgs/krb5-1.20.1-h81ceb04_0/bin/kadmin
        miniconda3/share/info/libgomp.info
        miniconda3/bin/nghttp
        miniconda3/pkgs/pyyaml-6.0-py310h5764c6d_5.tar.bz2
        miniconda3/pkgs/libnghttp2-1.52.0-h61bc06f_0/bin/nghttp
        miniconda3/pkgs/openssl-3.0.8-h0b41bf4_0/bin/openssl
        miniconda3/pkgs/readline-8.2-h5eee18b_0/share/info/readline.info
        miniconda3/pkgs/toolz-0.12.0-py310h06a4308_0.conda
        miniconda3/include/unicode/urename.h
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0/site-packages/pip/_vendor/distlib/t64.exe
        miniconda3/pkgs/ruamel.yaml-0.17.21-py310h5764c6d_2.tar.bz2
        miniconda3/pkgs/icu-70.1-h27087fc_0/include/unicode/urename.h
        miniconda3/pkgs/setuptools-67.5.1-pyhd8ed1ab_0/site-packages/setuptools/gui-arm64.exe
        miniconda3/pkgs/libsqlite-3.40.0-h753d276_0.tar.bz2
        miniconda3/pkgs/cache/b35683e8.json
        miniconda3/pkgs/tk-8.6.12-h1ccaba5_0.conda
        miniconda3/pkgs/ca-certificates-2022.12.7-ha878542_0/ssl/cacert.pem
        miniconda3/pkgs/icu-70.1-h27087fc_0/include/unicode/measunit.h
        miniconda3/pkgs/tzdata-2022g-h191b570_0.conda
        miniconda3/bin/openssl
        miniconda3/pkgs/conda-23.1.0-py310hff52083_0/info/paths.json
        miniconda3/conda-meta/tk-8.6.12-h27826a3_0.json
        working/samples/20230213/novara/raw_data/23BL00080NO_R1.fastq
        miniconda3/pkgs/readline-8.1.2-h0f457ee_0/share/info/readline.info
        miniconda3/pkgs/zstandard-0.18.0-py310h5eee18b_0.conda
        miniconda3/pkgs/cache/2ce54b42.json
        miniconda3/conda-meta/docutils-0.19-py310hff52083_1.json
        miniconda3/pkgs/fmt-9.1.0-h924138e_0/include/fmt/core.h
        miniconda3/pkgs/libffi-3.4.2-h6a678d5_6/info/test/testsuite/libffi.bhaible/test-callback.c
        miniconda3/pkgs/bzip2-1.0.8-h7f98852_4/bin/bunzip2
        miniconda3/pkgs/pycparser-2.21-pyhd8ed1ab_0.tar.bz2
        miniconda3/pkgs/sqlite-3.40.0-h4ff8645_0.tar.bz2
        miniconda3/pkgs/ncurses-6.3-h27087fc_1/info/paths.json
        miniconda3/pkgs/libedit-3.1.20191231-he28a2e2_2.tar.bz2
        miniconda3/pkgs/cache/3e39a7aa.q
        miniconda3/pkgs/pip-23.0.1-pyhd8ed1ab_0/site-packages/pip/_vendor/certifi/cacert.pem
        miniconda3/pkgs/humanfriendly-10.0-py310hff52083_4.tar.bz2
        miniconda3/pkgs/libiconv-1.17-h166bdaf_0.tar.bz2
        miniconda3/pkgs/pycosat-0.6.4-py310h5764c6d_1.tar.bz2
        miniconda3/include/tclInt.h
        miniconda3/share/info/readline.info
        miniconda3/bin/mamba-package
        miniconda3/pkgs/conda-package-handling-2.0.2-py310h06a4308_0/info/test/tests/data/mock-2.0.0-py37_1000.conda
        miniconda3/pkgs/cache/ffeee55f.json
        miniconda3/bin/lz4
        miniconda3/pkgs/libgcc-ng-11.2.0-h1234567_1.conda
        miniconda3/pkgs/conda-23.1.0-py310h06a4308_0.conda
        miniconda3/pkgs/tzdata-2022g-h04d1e81_0.conda
        miniconda3/pkgs/libarchive-3.6.2-h3d51595_0.conda
        miniconda3/pkgs/tzdata-2022g-h191b570_0/info/paths.json
        miniconda3/pkgs/conda-package-handling-2.0.2-py310h06a4308_0.conda
        miniconda3/pkgs/python-fastjsonschema-2.16.3-pyhd8ed1ab_0/info/test/src/tests/examples/issue-109/fhir.schema.json
        miniconda3/pkgs/certifi-2022.12.7-py310h06a4308_0.conda
        miniconda3/pkgs/libffi-3.4.2-h6a678d5_6.conda
        miniconda3/pkgs/libsqlite-3.40.0-h753d276_0/include/sqlite3.h
To disable this message in the future, run:
        renku config set show_lfs_message False
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: open
Did it work? [Y/n]: n

## Describe the bug
A clear and concise description.

## Details
*Please verify and redact the details.*

**Renku version:** 1.10.0
**OS:** Linux (#58-Ubuntu SMP Thu Oct 13 08:03:55 UTC 2022)
**Python:** 3.9.12

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/ui/cli/exception_handler.py", line 133, in main
    return super().main(*args, **kwargs)
  File "[...]/renku/ui/cli/exception_handler.py", line 92, in main
    return super().main(*args, **kwargs)
  File "[...]/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "[...]/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "[...]/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "[...]/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "[...]/renku/ui/cli/save.py", line 114, in save
    save_and_push_command()
  File "[...]/renku/command/command_builder/command.py", line 252, in execute
    output = self._operation(*args, **kwargs)  # type: ignore
  File "[...]/renku/command/save.py", line 68, in _save_and_push
    paths = commit_changes(*paths, repository=repository, message=message)
  File "[...]/renku/core/util/git.py", line 494, in commit_changes
    repository.commit(message)
  File "[...]/renku/infrastructure/repository.py", line 248, in commit
    self.run_git_command(
  File "[...]/renku/infrastructure/repository.py", line 391, in run_git_command
    return _run_git_command(self._repository, command, *args, **kwargs)
  File "[...]/renku/infrastructure/repository.py", line 1758, in _run_git_command
    return getattr(repository.git, command)(*args, **kwargs)
  File "[...]/git/cmd.py", line 639, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "[...]/git/cmd.py", line 1184, in _call_process
    return self.execute(call, **exec_kwargs)
  File "[...]/git/cmd.py", line 873, in execute
    proc = Popen(command,
  File "[...]/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "[...]/subprocess.py", line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
OSError: [Errno 7] Argument list too long: 'git'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
Thank you for reporting this, this happens when we try to call a command in a subprocess and there's too many files for your shell to handle.

In most places, we batch these kinds of call to not hit this limit, but it looks like we missed batching a call in this case.
