### ISSUE TITLE
cli: connect files and directories

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#336]
**Is your feature request related to a problem? Please describe.**

The input/output directories can be used with `renku run` command, however there are various cases where the lineage (update) may be broken:

- [x] a file/subdirectory from an output directory used as input
```
*  13609391 bb/c/d
|           (part of bb/c directory)
*  13609391 bb/c
|           (part of bb directory)
*  13609391 bb
*  13609391 .renku/workflow/2d081727f9244fc7bc50a3b3747e0d96_cp.cwl
| *  585ba2c2 aa/b/c/d
| |           (part of aa/b/c directory)
| *  585ba2c2 aa/b/c
|/            (part of aa/b directory)
*  585ba2c2 aa/b
*  585ba2c2 aa
*  585ba2c2 .renku/workflow/231bb4f21d1f486b86f65369cfb88aae_cp.cwl
| *  2f662624 a/b/c/d
| |           (part of a/b/c directory)
| *  2f662624 a/b/c
| |           (part of a/b directory)
| *  2f662624 a/b
|/            (part of a directory)
@  2f662624 (latest -> 5985b6ef) a
```
- [x] a parent directory with content from multiple executions (https://www.commonwl.org/v1.0/Workflow.html#WorkflowStepInput - `linkMerge`?)
```
*  5b4f6008 a.ls
*    5b4f6008 .renku/workflow/1faf97f697ec45288c2f284490903c38_ls.cwl
|\
| \
| |\
*---+  374efed2 a  # TODO virtual selection step is missing
|/ /
| *  374efed2 a/2
| @  374efed2 .renku/workflow/ecafcf5345f4446d8183e56b08000640_echo.cwl
*  d935e501 a/1
@  d935e501 .renku/workflow/fd93a892f0214d5db3b123be16f5c415_echo.cwl
```

**Describe the solution you'd like**

Define valid [Expression Tools](https://www.commonwl.org/v1.0/Workflow.html#ExpressionTool) that can handle file selection and linking.

**Describe alternatives you've considered**

Using `CommandLineTool` with dummy command (`true`).

**Additional context**

TBD

**Comment by Panaetius** [comment]
This works in new workflows
