### ISSUE TITLE
provide an overview of renku commands in git history with option to undo

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#338]
**Is your feature request related to a problem? Please describe.**

Undoing the result of a `renku` command can be mind-boggling for new users. 

**Describe the solution you'd like**

We should provide functionality for 

a) seeing a listing of the `renku` commands that have been run (i.e. a selective `git log`
b) reverting a particular `renku` action, with the caveat that we need to show and somehow handle the dependencies of such a revert. 

**Describe alternatives you've considered**

Document manual rebase/revert

**Comment by jirikuncar** [comment]
@ciyer wrote in #440

**Is your feature request related to a problem? Please describe.**
Undoing the effect of renku commands in the repository is tedious. It would nice if this were simpler.

**Describe the solution you'd like**
Add a command `renku undo [--force]`:

Undo the last renku operation

- if working dir is dirty, ask user to stash changes or clean
- if the last commit was not a renku operation, fail with a message that undo can only undo renku operations
- if the last commit has been pushed to its tracking branch (assuming this is easy to detect), fail unless the force flag is turned on.
- if all sanity checks pass, reset HEAD to HEAD~1 and clean working dir. 

**Describe alternatives you've considered**
Do the same operation by hand.
