### ISSUE TITLE
renku mv (update necessary files when renaming a folder or a file)

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-python#341]
as an example: an folder for input files was created containing a typo, e.g `inpput-folder`, some renku runs were performed with the data in it, then, someone decides to correct that typo... a `git mv` is not sufficient..

besides `.gitattributes` for `git lfs` files, which files need to be updated?

renaming could also be applied to intermediate files and folders in the workflow..

**Comment by jirikuncar** [comment]
- [ ] add strategy for metadata modifications (`--strategy=(update|delete|ignore)`)
