### ISSUE TITLE
failure to add files in subdirectory to git-lfs correctly

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#342]
**Describe the bug**

If the output directory is specified on the command line, it is added to `.gitattributes` as 

```
path/to/dir filter=lfs diff=lfs merge=lfs -text
```

Note from the [git-lfs docs](https://git-scm.com/docs/gitattributes):

> patterns that match a directory do not recursively match paths inside that directory (so using the trailing-slash path/ syntax is pointless in an attributes file; use path/** instead)

This means that whatever files are produced in the output directory are not currently being added to LFS. 

**Expected behavior**

The `.gitattributes` file should instead include

```
path/to/dir/** filter=lfs diff=lfs merge=lfs -text
```

**Comment by leafty** [comment]
Should we have something liks `data/lfs/**` in there then?

**Comment by rokroskar** [comment]
Or just `data/**`

**Comment by leafty** [comment]
There are small files in there sometimes. And we should move out the metadata files if we do that.

**Comment by rokroskar** [comment]
Or just exclude certain files
