### ISSUE TITLE
Unclear messaging for error in using workflows 

### ISSUE THREAD

**Issue by bethcg** [SwissDataScienceCenter/renku-python#3504]
Tracking inputs, outputs and parameters, a user had this error many times, causing the workflow to not be tracked 

```
finished.
Error: Invalid parameter value - Duplicate input, output or parameter names found: use_embeddings
```

This is the definition of that parameter:

```
_ = Parameter(name="use_embeddings", value=args.use_embeddings)
```

where `args.use_embeddings` is a `str`. The user has tried a few things: cleaning with `renku gc`, commenting this (and then it gives the same error with another parameter), but could not understand what is going on. In the beginning, as value I was providing `True`, and I thought that might be the reason. But now, I just provide a `str`. 

Finally, the user could make it work with the command:
`renku run python src/bert_topic_extraction.py --nr_topics 300 --use_embeddings False --remove_entities False`

Hence, these 3 parameters may be tracked twice: internally, and from the command use to run. Hence, the error is understood.  However, it is still en extremely annoying this. We propose: (i) could this be checked before actually running /executing the files? And (ii) Renku prompting: `Duplicated inputs, please do something.`

**Comment by lusamino** [comment]
Actually, the way I made this works was by commenting the respective `Parameters` commands inside the script. This way, I was sort of avoiding doubly providing the parameters: through the CLI, and inside the script. 

However, this is not a solution, as I may, or may not, provide this parameters in the CLI. Therefore, this should be done automatically, or a flag may allow to override this (currently there are only flags for inputs and outputs `no-input-detection`, `no-output-detection`).

Thank you!
