### ISSUE TITLE
cli: renku session start -p docker

### ISSUE THREAD

**Issue by philipp-baumann** [SwissDataScienceCenter/renku-python#3552]
## Describe the bug
CLI command errors with the bug below, see traceback below, when I did

```sh
renku session start -p docker .
```

If you need more details for the diagnostics, happy to share.

## Details

**Renku version:** 2.5.0
**OS:** Linux (22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb 17 15:17:25 UTC 2)
**Python:** 3.10.6

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/core/session/docker.py", line 359, in session_start_helper
    container = self.docker_client().containers.run(
  File "[...]/docker/models/containers.py", line 819, in run
    container = self.create(image=image, command=command,
  File "[...]/docker/models/containers.py", line 877, in create
    create_kwargs = _create_container_args(kwargs)
  File "[...]/docker/models/containers.py", line 1095, in _create_container_args
    create_kwargs['host_config'] = HostConfig(**host_config_kwargs)
  File "[...]/docker/types/containers.py", line 369, in __init__
    raise host_config_type_error(
TypeError: Invalid type for security_opt param: expected list but found <class 'tuple'>
```

## Additional context
Add any other context about the problem.

**Comment by philipp-baumann** [comment]
Thanks @Panaetius sorry for putting this `.`, which is wrong syntax I have introduced. Now pulling fine with `renku session start -p docker`

**Comment by philipp-baumann** [comment]
Just reopening, actually I still get the same error message when running without `.`. There seems to be another issue, from the stack trance message it must be something related to `security_opt`.

**Comment by philipp-baumann** [comment]
For the record, I have added pipenv lock file for the local computational environment where I ran `renku session start -p docker` subcommand, if this helps in any case to diagnose further: https://renkulab.io/projects/philipp.baumann/applied-infrared-spectroscopic-modeling-workshop-for-soil-and-plant-diagnostics/files/blob/Pipfile.lock

**Comment by Panaetius** [comment]
I reopened the issue. Unfortunately, we probably won't get around to looking into it until after summer holidays season, as we're spread a bit thin right now. Sorry about that.

**Comment by philipp-baumann** [comment]
> I reopened the issue. Unfortunately, we probably won't get around to looking into it until after summer holidays season, as we're spread a bit thin right now. Sorry about that.

no rush though from my side. I do not necessarily need a local docker. I am both familiar with RHEL and Ubuntu, so all fine.

**Comment by philipp-baumann** [comment]
thanks! 🚀
