### ISSUE TITLE
cli: how to use named workflows/tools?

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#356]
Thinking about how such a feature would be used:

1. some combination of steps is used to produce an output; the user wants to remember this and creates a named workflow (e.g. "generate cumulative plot"
2. the user wants to "remember" a single important step, so they want to name it, e.g. "corpus word count"

How would I go about figuring out which cwl file I need to name? If I do 

```
$ renku workflow
e2fe342b7cd54636ac4f6455dd673729_python.cwl:
f32897546b0d4e1db84671a17280a0f1_python.cwl:
```

it's not obvious what they actually do.

_Originally posted by @rokroskar in https://github.com/SwissDataScienceCenter/renku-python/pull/354#issuecomment-439038123_

**Comment by Panaetius** [comment]
Not relevant anymore due to https://github.com/SwissDataScienceCenter/renku-python/issues/1875
