### ISSUE TITLE
normalize git_url in service cache

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#3575]
currently, the core-svc could be called with `https://renkulab.io/gitlab/namespace/project.git` and `https://renkulab.io/gitlab/namespace/project`, and since the URLs differ (but refer to the same repo), we'd get two separate cache entries. We should normalize the git_url to make sure the same cache is always used.

**Comment by olevski** [comment]
Note: If it has `.git` remove it and use the url without `.git` in the cache.
