### ISSUE TITLE
Running several instances of `renku run` at the same time

### ISSUE THREAD

**Issue by lusamino** [SwissDataScienceCenter/renku-python#359]
**Is your feature request related to a problem? Please describe.**
Simply, some simulations might take long, and it would be desirable to have the possibility of running several renku at the same time, and leave then running, taking care of avoiding any collisions

**Describe the solution you'd like**
In principle we might think that the inputs will be the same, but each output file will have a different suffix, to avoid collisions. Then, simply allow this possibility.

**Comment by jirikuncar** [comment]
It could be done by using: https://github.com/git/git/blob/master/contrib/workdir/git-new-workdir

**Comment by rokroskar** [comment]
update: this seems to be the way to do it: https://git-scm.com/docs/git-worktree

**Comment by lusamino** [comment]
Awesome! Will take a look once I need to use it again. Thanks!

**Comment by rokroskar** [comment]
we're actually addressing this in #369
