### ISSUE TITLE
Remove python pillow from production requirements

### ISSUE THREAD

**Issue by olevski** [SwissDataScienceCenter/renku-python#3605]
It seems that we only use pillow in tests and to convert an image to base64 encoded string

Google says you can base64 encode an image like this:
```
import base64

with open('house.webp', 'rb') as image_file:
    base64_bytes = base64.b64encode(image_file.read())
    print(base64_bytes)

    base64_string = base64_bytes.decode()
    print(base64_string)
```

So we should only include pillow as a dev dependency (or if possible simply not at all).

**Comment by olevski** [comment]
Code taken from: https://bobbyhadz.com/blog/convert-image-to-base64-string-in-python#convert-an-image-to-a-base64-encoded-string-in-python

**Comment by Panaetius** [comment]
we use it to create a thumbnail https://github.com/SwissDataScienceCenter/renku-python/blob/develop/renku/ui/service/controllers/templates_read_manifest.py#L63

**Comment by Panaetius** [comment]
closing this for now, unless you have an alternative for creating thumbnails? then please reopen
