### ISSUE TITLE
Passing commit references to `config.show` doesn't work as expected

### ISSUE THREAD

**Issue by lorenzo-cavazzi** [SwissDataScienceCenter/renku-python#3649]
**Describe the bug**
The `GET /config.show` endpoint has a parameter called `branch` that (thanks to #3579) should accept all valid references.
It doesn't seem to work correctly. Here is an example that should return 0 CPU instead of 8 CPU
https://dev.renku.ch/ui-server/api/renku/10/config.show?branch=b44d8b8bca27d5e0c271083c57b17861ef370624&git_url=https%3A%2F%2Fgitlab.dev.renku.ch%2Fflora.thiebaut%2Fa-playground-project
Using the branch (`test-settings`) also leads to the same result; it seems that the field is ignored.

**Link to project**
[If possible, provide a public renkulab link to the project with the bug.](https://gitlab.dev.renku.ch/flora.thiebaut/a-playground-project/-/commit/b44d8b8bca27d5e0c271083c57b17861ef370624)

**To Reproduce**
Use the link above; the project is just an example. It should be easy to reproduce this by playing around with the project config.

**Run environment (please complete the following information):**
Tested on dev.renku.ch where the renku-core version is `v2.7.0`

**Comment by Panaetius** [comment]
@lorenzo-cavazzi the `branch` field only accepts branches (as per the name), use the `commit_sha` field (in the PR you linked https://github.com/SwissDataScienceCenter/renku-python/pull/3608/files#diff-ec6227d8ba49d96645055b9405410a0fe9b7bb4b259bfbb369afde37b98e2a26R42-R43 )

**Comment by lorenzo-cavazzi** [comment]
I tried the `commit_sha` solution on the `develop` branch, but I still got the same problem

P.S. The link probably won't work anymore in a few days from now, just update it with a working deployment

https://renku-ci-ui-2854.dev.renku.ch/ui-server/api/renku/10/config.show?commit_sha=b44d8b8bca27d5e0c271083c57b17861ef370624&git_url=https%3A%2F%2Fgitlab.dev.renku.ch%2Fflora.thiebaut%2Fa-playground-project

![image](https://github.com/SwissDataScienceCenter/renku-python/assets/43481553/292f0bd5-ef0c-4a66-9697-9f6ba951fb87)

**Comment by Panaetius** [comment]
i tested this on the same deployment with newest develop which has some fixes for the internal cache and everything worked as expected. closing this issue

**Comment by leafty** [comment]
The endpoint does not work for anonymous users:
```json
{"error":{"code":1010,"devMessage":"Repository not found. Git error message: stderr: 'cloning into '/tmp/tmp0249ujrt'... warning: redirecting to https://gitlab.dev.renku.ch/flora.thiebaut/a-playground-project.git/ post git-upload-pack (568 bytes) warning: could not find remote branch acd42ec5661190e0012d0d8e7e21eea5aefdb333 to clone. fatal: remote branch acd42ec5661190e0012d0d8e7e21eea5aefdb333 not found in upstream origin '","devReference":"https://renku-python.readthedocs.io/en/latest/service_errors.html#renku.ui.service.errors.UserRepoUrlInvalidError","userMessage":"A valid Git repository is not available at the target URL, or the user does not have the required permissions to access it."}}
```

**Comment by Panaetius** [comment]
```
fatal: remote branch acd42ec5661190e0012d0d8e7e21eea5aefdb333 not found in upstream origin
```
seems the branch doesn't exist? there shouldn't be a reason for it failing for anonymous users unless the repo isn't public

**Comment by leafty** [comment]
Oh sorry, I don't know why I used `branch=`.

The problem still remains though, I get different answers if I use a logged in session or an anonymous session:

Logged in:
```
https://dev.renku.ch/ui-server/api/renku/10/config.show?git_url=https%3A%2F%2Fgitlab.dev.renku.ch%2Fjohann.thiebaut1%2Fanother-playground-project&commit_sha=a5dc1ae5cda2ecd5ab70ceafa799603e9d76cdd4
```
```json
{"result":{"config":{"interactive.cpu_request":"10","interactive.default_url":"/lab","renku.autocommit_lfs":"false","renku.check_datadir_files":"true","renku.lfs_threshold":"100kb"},"default":{"interactive.default_url":"/lab","renku.autocommit_lfs":"false","renku.check_datadir_files":"true","renku.lfs_threshold":"100kb"}}}
```

Anonymous:
```
https://dev.renku.ch/ui-server/api/renku/10/config.show?git_url=https%3A%2F%2Fgitlab.dev.renku.ch%2Fjohann.thiebaut1%2Fanother-playground-project&commit_sha=a5dc1ae5cda2ecd5ab70ceafa799603e9d76cdd4
```
```json
{"result":{"config":{"interactive.cpu_request":"0.4","interactive.default_url":"/lab","interactive.disk_request":"4G","interactive.mem_request":"1G","renku.autocommit_lfs":"false","renku.check_datadir_files":"true","renku.lfs_threshold":"100kb"},"default":{"interactive.default_url":"/lab","renku.autocommit_lfs":"false","renku.check_datadir_files":"true","renku.lfs_threshold":"100kb"}}}
```

**Comment by Panaetius** [comment]
does this eventually converge or persist? could be a caching issue.

**Comment by leafty** [comment]
The anonymous responses seem incorrect

**Comment by Panaetius** [comment]
i checked and this wasn't implemented for the anonymous code path. we'll address that
