### ISSUE TITLE
Notify user if renku dataset add references files in .gitignore

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#385]
**Is your feature request related to a problem? Please describe.**

When converting an existing repo to a renku repo, data files might be in gitignore (since you normally do not want large files in your repo). This can go unnoticed when running renku dataset add. The result is confusing since there are no errors, and the files have been copied to the dataset directory, but they are not in the repo / lfs.

**Describe the solution you'd like**

Warn the user when this happens and emit a command that can be used to fix this problem. E.g., when trying to add an ignored file to git, you get
```
The following paths are ignored by one of your .gitignore files:
[...]
Use -f if you really want to add them.
```

**Describe alternatives you've considered**
The current alternative is be confused as to why all commands succeeded and the files are in the expected location on the filesystem but not in git/lfs. 

**Additional context**

**Comment by jirikuncar** [comment]
There is a nice library that might help with the implementation https://pypi.org/project/pathspec/
