### ISSUE TITLE
cli: group outdated and deleted files

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-python#392]
**Is your feature request related to a problem? Please describe.**
The status shows individual files in an output folder together with same outdated dependency.

**Describe the solution you'd like**
Group files by dependencies and/or common prefix.

**Describe alternatives you've considered**
TBD

**Additional context**
I have an output directory with a lot of files and the status message gets very loooong.

**Comment by jirikuncar** [comment]
Add ``--group/--no-group`` flag.

**Comment by jirikuncar** [comment]
The grouping works for files in output directories.
