### ISSUE TITLE
Feature request: renku dataset delete

### ISSUE THREAD

**Issue by nperraud** [SwissDataScienceCenter/renku-python#418]
**Is your feature request related to a problem? Please describe.**
Removing manually a dataset now is pain. Woud be great to have an helping command for that.

**Describe the solution you'd like**
`renku dataset delete d` should delete the dataset `d` and rebase if `d` has not beed used

**Comment by jirikuncar** [comment]
- [ ] check if there are existing files
- [ ] `--purge/--force/--???` or ask for each file individually (prompt)

```console
$ renku dataset delete <name>
There are linked files ...

  (use "renku dataset unlink/remove <name> <path> [<path> ...] to ...)
    data/<name>/file1
    data/<name>/file2
   ...

You can delete linked files using ...
```
