### ISSUE TITLE
Dataset add command with --copy/--no-copy works in reversed order

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#448]
**Describe the bug**
I think --copy/--no-copy flags on add command are reversed.

**To Reproduce**
```
>> renku dataset add --no-copy my-dataset ../a 
>> ls -i data/my-dataset/
5904072 a
>> ls -i ../
4064143 a 
```

I would expect if I use --no-copy flag that no copy has been made. From the example above we can see that the copy has been made, even though I used --no-copy flag.

The opposite case `--copy` which I would expect to make a copy, creates a hard link with expected/same inodes.

Proposal 1: Fix the flag to be the opposite and add the test to validate this.
Proposal 2: Remove this flag altogether?

related #418

**Comment by rokroskar** [comment]
we should make this less cryptic and just have copy by default and offer the `--link` option. The doc should include a warning for what this means (overwriting the linked file will cause the original to change... may not be obvious to people)
