### ISSUE TITLE
Simplify management of dataset paths

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#449]
Common use case when working with dataset components is to work with absolute (resolved) paths of dataset files. Currently, inside dataset metadata, we are storing relative paths, which often should be resolved into real paths.

A proposal, as we discussed, is to build a map which would contain all elements needed to easily work with dataset files paths.
 
AC:

1. Can map from relative path to resolved absolute path
2. Can easily traverse to find which files are contained in multiple datasets

**Comment by rokroskar** [comment]
I don't understand what is being proposed here - what is the problem with turning a relative path into an absolute one, if you know the starting point? Absolute paths are not stored to avoid committing information about a user's filesystem into the repo.

**Comment by jirikuncar** [comment]
This issue is somewhat outdated since we are including `__reference__` property for each metadata object loaded from a filesystem, hence it should be way simpler to resolve relative paths in the metadata objects.
