### ISSUE TITLE
report execution times in renku run

### ISSUE THREAD

**Issue by erbou** [SwissDataScienceCenter/renku-python#461]
report run times (user, system, total) in executions. In addition this should be included in the knowledge graph, ideally with info about the runtime environment (RAM, vCPU, etc).

**Comment by jirikuncar** [comment]
The total time is already included as `authored_date` - `commit_date`.

**Comment by Panaetius** [comment]
I think we should track this on the `renku:Run` nodes as well as the `prov:ProcessRun` ones, then we could give estimates for rerun/update later on.

**Comment by Panaetius** [comment]
Will be done as part of https://github.com/SwissDataScienceCenter/renku-python/issues/1875
