### ISSUE TITLE
cli: renku storage pull PATH should resolve symlinks first

### ISSUE THREAD

**Issue by LiliGasser** [SwissDataScienceCenter/renku-python#462]
**Describe the bug**
`renku storage pull PATH` should resolve symlinks first.

Maybe it is due to relative submodules ...

**Comment by rokroskar** [comment]
we worked on this recently, which version of renku are you using?

**Comment by LiliGasser** [comment]
0.4.1.dev12

**Comment by rokroskar** [comment]
can you tell me what you are trying to do exactly?

**Comment by LiliGasser** [comment]
Jiri helped set up a symlink between the democrasci_preprocwp1 and the democrasci_kgraphwp22 repo for one folder. This folder contains git lfs files. When I try to `git lfs pull -I` the linked files, it does not do it.

**Comment by jirikuncar** [comment]
There could have been an issue with the submodule setup. We were using the latest `renku` version.

```console
$ ls -l
foo -> .renku/vendors/renkulab.io/namespace/project/data/foo
$ renku storage pull foo
# no info - checkout?
```

**Comment by rokroskar** [comment]
I seem to recall this is exactly the problem we were trying to fix a few weeks ago. Maybe it wasn't quite fixed correctly.

**Comment by mohammad-sdsc** [comment]
Since we got away from using git submodules when adding data from a git repo (https://github.com/SwissDataScienceCenter/renku-python/issues/681), this should not be an issue anymore for such datasets when we migrate all old projects (https://github.com/SwissDataScienceCenter/renku-python/issues/980).
