### ISSUE TITLE
cli: improve ls-files command to format files based on user cwd

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#463]
Implement support for filtering based on the user current working directory. 

If the user changes directory inside some data path in the repository, ls-files filtering should take into account current working directory and only filter data which is contained inside of this path.

**Comment by rokroskar** [comment]
Won't that be confusing? Couldn't you just show the files with the adjusted relative paths? What is the `git lfs ls-files` behavior?

**Comment by jirikuncar** [comment]
>  contained inside of this path.

It should still show everything but format them relative to cwd.
