### ISSUE TITLE
cli: pre-commit hook for large files

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#474]
Include a pre-commit hook for reducing risk of committing large files to Git repository.
A suggestion would be to ask the user for confirmation when
- adding a binary
- adding a text file larger than 1 kb
- adding more than 100 files at once
- adding a file that is in /data
- adding a text file with extension in {'.csv', '.tsv', '.json'} 

to git instead of git lfs. Also, the `--no-verify` flag can be used to skip those checks. 

---
see http://shuhrat.github.io/programming/git-lfs-tips-and-tricks.html 

cc @erbou @ableuler

**Comment by mohammad-sdsc** [comment]
This is addressed slightly different in https://github.com/SwissDataScienceCenter/renku-python/issues/1100.
