### ISSUE TITLE
cli: clean notebooks before commit

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-python#478]
A pre-commit hook could be used to clear output cells and reset execution counters of `.ipynb` files before committing. 

---
Also, this should be coordinated with the jupyterlab extension (cc @vfried ).

**Comment by rokroskar** [comment]
I don't think you want that in general. For example, if you then linked to the notebook in a Ku, you would not see any plots etc, which makes it not so useful for discussion.

**Comment by jirikuncar** [comment]
IMHO this applies only to "input" notebooks run by papermil.

**Comment by rokroskar** [comment]
`papermill` does this already since it makes a copy of the notebook and saves the "rendered" version.

**Comment by jirikuncar** [comment]
as a reference after our discussion: the input notebook needs to be cleaned before running `papermill` to keep `renku status` "up-to-date" if no changes were done to the notebook.
