### ISSUE TITLE
models: export Agent for Activities

### ISSUE THREAD

**Issue by jirikuncar** [SwissDataScienceCenter/renku-python#508]
Each activity (not only `renku *`) should have an agent.

**Comment by jachro** [comment]
I believe not only activity but each commit should have an `agent` so effectively we'll have triples like the following:
`file:///commit/<commit_id>, prov:agent, <renku-cli-version>`
which example could be:
`file:///commit/df654c3b1bd105a29d658f78f6380a842feac879, prov:agent, 0.5.1`

**Comment by rokroskar** [comment]
Just to clarify - a commit is the basic `Activity` that is created if no CWL-related activity is found.

**Comment by jachro** [comment]
Hi Rok,

I tested the change and noticed that there was a change from dcterms:SoftwareAgent to prov:SoftwareAgent. I adapted triples-generator to work with that and the changes are here:
https://github.com/SwissDataScienceCenter/renku-graph/pull/102

**Comment by rokroskar** [comment]
Ok thanks let me make sure that the vocabulary use makes sense before we commit this
