### ISSUE TITLE
cli: add dataset edit command

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#512]
Add dataset edit command with which user can add new or edit existing metadata.

`renku dataset edit some-dataset`

Should open a `$EDITOR` and load metadata of a dataset.

**Comment by ciyer** [comment]
Good idea. Should also be possible to store the template to a file and open it in another text editor (Think about the usage on the server where you might be limited to nano as a command line editor. There, you might want to write to a file and edit the file in JupyterLab).

One possibility
`renku dataset edit some-dataset  -o some-file.yaml`
and
`renku dataset edit some-dataset -f some-file.yaml`

The first writes the current metadata to a file. The second reads it in from a file and does not open an editor.
