### ISSUE TITLE
Graph building fails with whitespaces

### ISSUE THREAD

**Issue by Clement-Lef** [SwissDataScienceCenter/renku-python#517]
**Describe the bug**
When committing a notebook with a space in its name (ie. "Test Notebook.ipynb") the pipeline dot fails to complete. 

**To Reproduce**
1. Create a notebook with a whitespace in its name.
2. Commit it and push it.
3. The pipeline dot will fail.

See this repo: https://renkulab.io/gitlab/clement.lefebvre/test_blank_space/-/jobs/6521

**Expected behavior**
Successful pipeline dot build.

**Additional context**
I only tried with notebooks files.

**Comment by rokroskar** [comment]
Thanks for reporting this @Clement-Lef -- clearly this is something that needs to be handled correctly and we'll fix it asap.

**Comment by Panaetius** [comment]
This was fixed by https://github.com/SwissDataScienceCenter/renku-python/pull/584, no?

**Comment by mohammad-sdsc** [comment]
I believe so but apparently I did not link it to the PR (just did it now) and it was not closed. AFAIK the issue did not happen again after the PR was merged.
