### ISSUE TITLE
cli: renku migrate datasets

### ISSUE THREAD

**Issue by nperraud** [SwissDataScienceCenter/renku-python#518]
## Describe the bug
`renku migrate datasets` failled

## Details
*Please verify and redact the details.*

**Renku version:** 0.5.1.dev8
**OS:** Darwin (Darwin Kernel Version 18.0.0: Wed Aug 22 20:13:40 PDT 2018; root:xnu-4903.201.2~1/RELEASE_X86_64)
**Python:** 3.6.4

### Traceback

```
Traceback (most recent call last):
  File "[...]/site-packages/renku/cli/_client.py", line 80, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "[...]/site-packages/renku/cli/migrate.py", line 65, in datasets
    lambda key: os.path.
  File "[...]/site-packages/renku/models/datasets.py", line 222, in rename_files
    setattr(renamed, '__source__', self.__source__.copy())
AttributeError: 'NoneType' object has no attribute 'copy'
```

## Additional context
Add any other context about the problem.

**Comment by Panaetius** [comment]
I believe this was fixed already, see https://github.com/SwissDataScienceCenter/renku-python/pull/534/files#diff-789882e3192075d99a30e86bdb4c03c7R265

**Comment by rokroskar** [comment]
@nperraud could you please check with the latest renku version?

**Comment by rokroskar** [comment]
this should be fixed now so closing the issue for the time being - please reopen if the problem comes back.
