### ISSUE TITLE
cli: renku update fails

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-python#523]
## Describe the bug
Trying to run `renku update` on a workflow which pre-processes 4 files and then combines them to one result in a second step.

## Details

**Renku version:** 0.5.1.dev9
**OS:** Darwin (Darwin Kernel Version 18.5.0: Mon Mar 11 20:40:32 PDT 2019; root:xnu-4903.251.3~3/RELEASE_X86_64)
**Python:** 3.7.0

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/cli/_client.py", line 80, in new_func
    result = ctx.invoke(method, client, *args, **kwargs)
  File "[...]/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "[...]/renku/cli/update.py", line 190, in update
    execute(client, output_file, output_paths=output_paths)
  File "[...]/renku/cli/_cwl.py", line 71, in execute
    outputs = process()
  File "[...]/site-packages/cwltool/factory.py", line 35, in __call__
    raise WorkflowStatus(out, status)
cwltool.factory.WorkflowStatus: Completed permanentFail
```

**Comment by rokroskar** [comment]
can you share the sequence of commands and the full stack trace?

**Comment by ableuler** [comment]
After some debugging I understand where my mistake was: Inside my python script I was using the relative path of the input file as a "hidden" input and writing the output file to the same directory. The `renku run` command records a workflow which expects an output at `relative/directory/path/output.xyz`. However, when `cwltool` re-runs the workflow, the input file is copied to a temporary location and the relative path information of the original input file is lost. 
I don't really understand why `cwltool` can not maintain relative paths underneath the temporary folder from where it executes the workflow, but it's definitely not a renku problem.

**Comment by rokroskar** [comment]
Yep, this is a super common problem/pattern though. Either we need to warn, document, or fail in some better way

**Comment by rokroskar** [comment]
I don't know whether this is a "feature" of the reference cwl runner implementation or if it's somehow required/expected by cwl.

**Comment by ableuler** [comment]
I agree and I'm pretty sure I'm not the first and not the last one running into this issue. Strictly speaking they are probably right. The path at which a file sits is not part of the file content or metadata, so when you pass a file to a workflow you should not expect to have access to the path. But I don't see why it shouldn't be possible for the reference implementation to be a bit more generous here.

But yeah, this should probably go to a `common pitfalls` section in the renku-python docs.
