### ISSUE TITLE
Configuration manager

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#532]
Implement configuration management for system-wide renku installation.

Configuration management should handle:
```
~/.renku
```

Where `~` is a user directory path (e.g. `C:\Users\<username>\.renku` or `/home/<username>/.renku`)

**Comment by jirikuncar** [comment]
Please take advantage of .git config as much as possible.

**Comment by rokroskar** [comment]
@jirikuncar seems to me that it would make things a bit confusing - why would a user expect to find renku configuration details in their `.gitconfig` file? Renku is not a git command/extension.
