### ISSUE TITLE
explicit specification of inputs and outputs

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#542]
**Is your feature request related to a problem? Please describe.**
Although it is generally nice, there are times when renku run's attempts to magically detect inputs and outputs get in the way.
- If I could explicitly specify my outputs, Renku could run on an otherwise dirty worktree
- Sometimes my script processes a fixed path and there is not need to specify inputs and outputs on the command line.

**Describe the solution you'd like**
I would like the ability to specify the input and output files when executing commands.

**Describe alternatives you've considered**
I do not think there are alternatives when this is necessary.

**Comment by rokroskar** [comment]
I think this needs to be qualified a bit further - I believe what you are asking for is:

> If inputs/outputs are explicitly specified, do not try to guess them from the state of the git repository.

**Comment by rokroskar** [comment]
This is probably related to #311 - or at least maybe the same CWL mechanism could be used.
