### ISSUE TITLE
cli: dataset add should ignore query parameters

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#544]
**Describe the bug**
The filename created with `renku dataset add` includes query parameters

**To Reproduce**
```
renku dataset create flights
renku dataset add flights https://www.dropbox.com/s/99w7evit5y7jxb3/2019-01-flights.csv.zip?dl=0
```

Look at the name of the resulting file.

**Expected behavior**

The query parameters should be stripped. In the above example, the result should be just `2019-01-flights.csv.zip`.

It might be necessary to ask the user how she wants the URL converted into a filename.

**Comment by fgeorgatos** [comment]
example desired behaviour:
```
$ wget --content-disposition https://www.dropbox.com/s/99w7evit5y7jxb3/2019-01-flights.csv.zip\?dl\=0
[...]
$ ls -las 2019-01-flights.csv.zip
16512 -rw-r--r--@ 1 fotios  staff  7930099 Jun 13 15:35 2019-01-flights.csv.zip
```
