### ISSUE TITLE
Use the same project templates as the UI

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#546]
**Is your feature request related to a problem? Please describe.**

We need to standardize project creation and use the same templates as the UI. 

**Describe the solution you'd like**

We should by default use the same repository of templates as the UI does. Optionally, the user could provide a URL to a renku template. The user would have options like:

```bash
renku init --template-name [template name: e.g., basic-r, basic-python] renku-project
renku init --template https://github.com/<path-to-repo-with-template> renku-project
```

If multiple directories with templates exist, the user would be presented with a choice.

The templates in the https://github.com/SwissDataScienceCenter/renku-project-template project should be shipped with the CLI and can be used even if there is no network connection.

**Comment by lorenzo-cavazzi** [comment]
when fetching a remote template, should we assume a `manifest.yaml` file must be available with information about the set `folder, name, description` of the valid templates contained in the repo as in https://github.com/SwissDataScienceCenter/renku-project-template/blob/master/manifest.yaml?

**Comment by rokroskar** [comment]
yes, I think that's the defining feature of a template - @ciyer?

**Comment by ciyer** [comment]
Yes, `manifest.yaml` must be there. A template is defined by an entry with a `folder` key. The `name` and `description` keys are optional, defaulting to the `folder`.
