### ISSUE TITLE
renku log --format Makefile produces incorrect output

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#553]
**Describe the bug**
The Makefile produced by renku log --format Makefile is incorrect. If the workflow is comprised of multiple targets, there is no `all` target, which I would expect to be the default goal.

**To Reproduce**
It is easiest to reproduce with the workflow from the SciPy tutorial: https://github.com/SwissDataScienceCenter/r10e-ds-py/blob/master/notebooks/03-renku/01-Starting.ipynb

Run through the notebook. The very last cell shows a Makefile representing the workflow, but because there is no `all` target, make will not actually rebuild everything if there is a change in one of the upstream files.

```
notebooks/02-Inspection.ran.ipynb: data/output/2019-01-flights-preprocessed.csv notebooks/02-Inspection.ipynb
	@papermill -p input_path data/output/2019-01-flights-preprocessed.csv notebooks/02-Inspection.ipynb notebooks/02-Inspection.ran.ipynb 
data/output/2019-01-flights-preprocessed.csv notebooks/01-Preprocess.ran.ipynb: data/flights/2019-01-flights.csv.zip notebooks/01-Preprocess.ipynb
	@papermill -p input_path data/flights/2019-01-flights.csv.zip -p output_path data/output/2019-01-flights-preprocessed.csv notebooks/01-Preprocess.ipynb notebooks/01-Preprocess.ran.ipynb 
```

**Expected behavior**

There should be an all target that has all the other targets as a dependencies.

```
all: notebooks/01-Preprocess.ran.ipynb data/output/2019-01-flights-preprocessed.csv notebooks/02-Inspection.ran.ipynb

notebooks/01-Preprocess.ran.ipynb data/output/2019-01-flights-preprocessed.csv: data/flights/2019-01-flights.csv.zip notebooks/01-Preprocess.ipynb
	@papermill -p input_path data/flights/2019-01-flights.csv.zip -p output_path data/output/2019-01-flights-preprocessed.csv notebooks/01-Preprocess.ipynb notebooks/01-Preprocess.ran.ipynb
notebooks/02-Inspection.ran.ipynb: data/output/2019-01-flights-preprocessed.csv notebooks/02-Inspection.ipynb
	@papermill -p input_path data/output/2019-01-flights-preprocessed.csv notebooks/02-Inspection.ipynb notebooks/02-Inspection.ran.ipynb 
```

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: N/A
 - Version: 0.5.0

**Comment by Panaetius** [comment]
We don't have Makefile anymore. We could write a Makefile export plugin in the future, but for now this isn't supported.
