### ISSUE TITLE
Standardize/complete the file URIs in the `isPartOf` triple

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#554]
It looks the file URIs in the `isPartOf` triples do not point to the right resource on Renku. For instance, triples generated on `renku-kuba` environment have URIs pointing to a non-existing resource on Renku DEV and instead of `https://renku-kuba.dev.renku.ch/projects/rokroskar/vom_natt` they point to `https://dev.renku.ch/rokroskar/vom_natt`.

**Original issue description**
I found out that `renku log --format rdf` produces ~triples where the objects of the `isPartOf` triples are comprised of `<GitLabHost>/<projectPath>`. While I'm not aware of why it was done this way, I think it's unnecessary and having only `<projectPath>` should be totally sufficient. The reasons I'm flagging that up are:
* `<projectPath>` defines a project uniquely within a GitLab instance;
* currently, the `<GitLabHost>/<projectPath>` values used in the mentioned triples do not really point to the projects in GitLab, as for instance on the DEV environment, they look like that: `https://dev.renku.ch/rokroskar/vom_natt` so they're lacking the `gitlab` part; 
* there's a certain amount of the maintenance cost associated with keeping the host in there as once we change GitLab hostname, an update query would have to be run on all the triples;
* even if we'd like to do searches across different Renku instances (a federation of Renkus), I'd imagine we'd rather go through an external Renku API, not access the RDF store directly (exposing the store to the outside world does seem to be the best idea from the security point of view);
* because the graph-service needs to find triples for a project, the GitLab hostname has to be defined in the service's config. However, that hostname cannot be used for any REST calls to GitLab as it's simply not valid and would require yet another config value.

So could we drop the hostname from the `isPartOf` triples, please? I believe it will make our life easier.

**Comment by rokroskar** [comment]
I agree that we need to refine this - but I disagree that we should get rid of the host part. IDs in RDF are supposed to be URIs -- I should be able to click on the `id` of any node in our graph and go to a resolvable URL. It's true that these are broken at the moment, but removing them completely does not solve the problem. We should instead define clearly what they should be and stick with it. 

This goes together with defining the URL schema of the UI (cc @SwissDataScienceCenter/renku-ui-maintainers) -- imho `https://dev.renku.ch/rokroskar/vom_natt` should take me to the **renku** page for that project, not gitlab. So in that sense, the current triples are actually correct but we need to redo how this is handled in the UI.

**Comment by jachro** [comment]
Right, that makes sense to me. The only thing I have to do then is to change my understanding of these values and change some property names in my code so it's not the GitLab host but Renku host. So I guess the only fix we'd need to do is that `renku log` puts proper Renku host like in my case would be `https://renku-kuba.dev.renku.ch/rokroskar/vom_natt` instead of `https://dev.renku.ch/rokroskar/vom_natt`. Do you think then we should keep this issue or there's one maybe one created already?

**Comment by rokroskar** [comment]
We should create an issue to standardize/complete the file URIs, I don't think one exists.

**Comment by jachro** [comment]
Maybe I can just rename this one as it's effectively just about that.

**Comment by rokroskar** [comment]
Sure, but then also please edit the description

**Comment by rokroskar** [comment]
This has been already planned in the UI for some time but never done - see https://github.com/SwissDataScienceCenter/renku-ui/issues/167

It will become critical for enabling a dynamic KG display, so we should do it asap.

**Comment by jachro** [comment]
As #660 was a duplicate and it got closed, I'm moving its acceptance criteria here so it's all clear.

As a Renku owner, I'd like `renku log` to generate project's resources triples pointing to the `http(s)://renku/projects/<namespace>/<project-name>` instead of `http(s)://renku/namespace/project-name`.

**Comment by rokroskar** [comment]
@jachro can you add that to the description of the issue to make it easier to see?
