### ISSUE TITLE
The rdf type of Person is incorrect

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#555]
The output of `renku log` results in something like:

<img width="403" alt="image" src="https://user-images.githubusercontent.com/3353586/59800777-bf886b00-92e7-11e9-89ca-24d916ed19ae.png">

but in the json-ld context of `Person` we have 

https://github.com/SwissDataScienceCenter/renku-python/blob/6a9173cc01b262ca0365cee061fc7550647120a6/renku/models/provenance/agents.py#L30-L33

This should be fixed first to include schema.org instead of foaf and second to refer to prov-o instead of dcterms.

**Comment by Panaetius** [comment]
is this still an issue?

In current code it's 
```
@jsonld.s(
    type=[
        'prov:Person',
        'schema:Person',
    ],
    context={
        'schema': 'http://schema.org/',
        'prov': 'http://www.w3.org/ns/prov#',
        'rdfs': 'http://www.w3.org/2000/01/rdf-schema#'
    },
    slots=True,
)
```

**Comment by rokroskar** [comment]
Thanks @Panaetius  - is this the case everywhere?
