### ISSUE TITLE
Allow dataset commands to operate on a dirty repo

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#560]
**Is your feature request related to a problem? Please describe.**
Commands like `renku dataset create` should not care if there are uncommitted files in the repo (unless they happen to be in the dataset directory). 

**Describe the solution you'd like**
Implement functionality to ignore certain paths on the dirty repo check. 

Relates to #543

**Comment by jsam** [comment]
Just to add a bit clarification on this (as we discussed).

Saving state (ie. making a commit) is still mandatory, but the requirement that a repository needs to be clean should not be there. On an unclean repository, after executing `renku dataset create` command, we should only commit needed metadata files and not all untracked files.

Current setup with `pass_local_client(clean=False, commit=True)` will stage and commit all untracked files. We should change this so, it only stages and commits files from a specific directory (ie. dataset metadata directory). In this case, another option would be to add something similar to `pass_local_client(clean=False, commit_only=['.renku/datasets']).
