### ISSUE TITLE
renku init --no-external-storage should be more explicit

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#562]
**Describe the bug**
If git lfs is enabled in a global config, `renku init --no-external-storage` will not prevent files from being added to LFS. Currently it does not *install* LFS but it also does not prevent LFS from being used if it is enabled in a higher-level config. It should instead run `git lfs install --skip-smudge --local`

**Comment by mohammad-sdsc** [comment]
I don't understand the proposed solution here: `git lfs install --skip-smudge --local`. This does not prevent *adding* of files to LFS and only avoid automatic downloading of LFS files when pulling or cloning.

**Comment by rokroskar** [comment]
No, running `git lfs install --skip-smudge --local` results in this `.git/config`:

```
[filter "lfs"]
        required = true
        clean = git-lfs clean -- %f
        smudge = git-lfs smudge --skip -- %f
        process = git-lfs filter-process --skip
```

**Comment by rokroskar** [comment]
Actually I think the `--no-local-storage` option is just broken for some reason - even if I don't have git-lfs installed anywhere and I initialize the repo with the `-S` option it still tries to put outputs in LFS.

**Comment by mohammad-sdsc** [comment]
Exactly, I've tried with different LFS variation (i.e. --skip-smudge added to local, user, and system's .gitconfig) and it still add files to LFS.

**Comment by mohammad-sdsc** [comment]
```
$ git lfs install --help

...
* --skip-smudge:
    Skips automatic downloading of objects on clone or pull. This requires a
    manual "git lfs pull" every time a new commit is checked out on your
    repository.
...
```

**Comment by mohammad-sdsc** [comment]
The problem is that when at the project creation time we provide the `--no-external-storage`, it is not persisted in the renku project file (if such a thing exist). Therefore, when we call the next command, renku has no idea that it shouldn't use LFS.

**Comment by jsam** [comment]
The way how you can know that repo is initialized with `--no-external-storage` flag is by looking at .git/config and searching for LFS section. If there is no such section there, you know that repo was initialized with `--no-external-storage`. 

There is `.renku/metadata.yml` file if you need to persist certain options, but I'm not sure if we should persist this one since it could lead to inconsistency with git.

**Comment by rokroskar** [comment]
The thing is that renku-python should *already* be doing this check. 

Maybe https://github.com/SwissDataScienceCenter/renku-python/blob/ae67be74587a181e6a3c83cdf07ecbc082e58a06/renku/api/storage.py#L62 needs to specifically check the local instead of global configuration.

**Comment by mohammad-sdsc** [comment]
In that code, when calling `self.repo.config_reader()` with no parameter it checks the config for the repo and all higher configs (i.e. user and system). This is fixed by passing the desired level to it: `self.repo.config_reader(config_level="repository").

I am fixing this.
