### ISSUE TITLE
Persist datadir information in project config

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#570]
Currently, we have no way of telling datadir for a dataset before instantiation of click context. This is needed to make all datasets commands able to operate on a dirty repository.

**Comment by rokroskar** [comment]
should this be part of `.renku/metadata.yml` or a project-local config file? I'm not sure, for example, we need/want this information in the KG (and I don't really know what we'd call it).

**Comment by Panaetius** [comment]
Related to https://github.com/SwissDataScienceCenter/renku-python/issues/1284
