### ISSUE TITLE
renku show error

### ISSUE THREAD

**Issue by hluetck** [SwissDataScienceCenter/renku-python#572]
**Describe the bug**
In the renku project, I can successfully call `renku show inputs` and `renku show outputs`. But when calling `renku show siblings`, I get the following error:

```
Error: The file "Dockerfile" was not created by a renku command.

Check the file history using: git log --follow "Dockerfile"
```

The output of `git log --follow "Dockerfile"` is:

```
commit ff55cb2bc1c1927ca51dcca0e3c8582a3599bfd9
Author: 1234 <dummy@ethz.ch>
Date:   Fri Jun 28 12:54:46 2019 +0200

    renku init
```

**To Reproduce**

```
mkdir renku
cd renku

renku init

git lfs install --local
git lfs track '*.h5'
git add .gitattributes
git commit -m "adding .gitattributes"

# create required folder hierarchy as datasets
renku dataset create M1/Session1/raw
renku dataset create M1/Session1/preprocessed
renku dataset create M1/Session1/extracted

# add data
renku dataset add M1/Session1/raw /Users/.../M1/Session1/raw/*

# add preprocessing scripts and wrapper
mkdir src
cp ~/myscript1 src/
cp ~/myscript2 src/
git add src
git commit -m "adding preprocessing scripts"

cd src
export PATH="$PATH:."
renku run myscript1
renku workflow set-name preprocessing

# some more processing steps follow
```

**Expected behavior**
I expected the command would display the siblings and not return an error.

**Screenshots**
N/A

**Desktop (please complete the following information):**

* OS: macOS

**Comment by rokroskar** [comment]
Thanks @hluetck for reporting this - are you running `renku show siblings Dockerfile` specifically? or without specifying a particular file?

**Comment by hluetck** [comment]
I was running the command without specifying a path / file. Actually, I did not realise that `show siblings` takes another input argument. When I run `renku show siblings data/M1/Session1/extracted/cellMap.mat` the output looks correct:
```
data/M1/Session1/extracted/cellMap.mat
data/M1/Session1/extracted/resultsPCAICA.mat
```
The command `renku show siblings Dockerfile` returns an error though:
```
Error: The file "Dockerfile" was not created by a renku command.

Check the file history using: git log --follow "Dockerfile"
```
But I guess from a user point of view, this is not a big issue.
