### ISSUE TITLE
Knowledge graph only shows renku update

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#573]
**Is your feature request related to a problem? Please describe.**
After running renku update on a file, the knowledge graph doesn't show the actual command to create the file, but only "renku update" instead of "renku python ...". 

**Describe the solution you'd like**
The former command to create the file

**Comment by rokroskar** [comment]
Hi @rcnijzink thanks for reporting this - it's a long standing problem that we need to address!

**Comment by rokroskar** [comment]
This requires changes to the modeling of execution steps in the KG. We should take this opportunity and use-case to drive the restructuring of the workflows KG.

**Comment by rokroskar** [comment]
#1185 should enable a query that will give us what we need

**Comment by Panaetius** [comment]
Only for `dot` output
