### ISSUE TITLE
Persist user information in the global configuration

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#574]
For certain commands, like `dataset export` we need to have up-to-date and complete metadata about the user. We should prompt the user once for this metadata and store it in the global configuration file so it can be used whenever needed. 

**Describe the solution you'd like**
`renku` should check if e.g. user affiliation is set - if not, provide a simple one-line instruction on how to add it to the configuration in the same way that `git` asks for user name and email.

**Comment by Panaetius** [comment]
Check what fields are needed.
Figure out where to store it

**Comment by Panaetius** [comment]
Closing as `renku config` works with the`--global` flag and we do store certain tokens in global user config.

Feel free to create a new issue if there is a specific piece of information that we should add to the global config but currently don't.
