### ISSUE TITLE
Default configuration for diffing text files in git-lfs

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#579]
**Is your feature request related to a problem? Please describe.**
Renku puts all outputs in git-lfs, even if they are text (e.g., csv). This makes these files difficult to diff, but with the right configuration, it is easy.

**Describe the solution you'd like**
Use this configuration: `git config diff.lfs.textconv cat` 

**Describe alternatives you've considered**
This can be done manually, but given renku's behavior, I think it makes sense to set the default this way.

**Comment by Panaetius** [comment]
Is this still relevant now that we can tell renku which files we want in LFS and we only commit files larger than a threshold to LFS?
