### ISSUE TITLE
Datasets improvements

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#583]
Here are the key takeaways we had about datasets improvements:

1. Dataset versioning
2. Usage of datasets in renku run and inclusion of datasets to knowledge graph
3. Explicit inputs
4. Data shopping / Importing from existing renku repositories

**Comment by rokroskar** [comment]
closing this for now in favor of https://github.com/SwissDataScienceCenter/renku/issues/594. Feel free to open more specific issues for the points above.

**Comment by ableuler** [comment]
I agree that this wasn't really an actionable item. I've instead created a small paragraph about this in the [meeting notes](https://docs.google.com/document/d/1mG7yD3jO2d9US8tA724TtXxxIuoSRvRFhF3hgV_0s4I/edit?usp=sharing).

**Comment by rokroskar** [comment]
Perfect, thanks!
