### ISSUE TITLE
cli: subcommand clean up

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#585]
**Describe the bug**
There are a bunch of commands that are not current:

```bash
Commands:
  config      Get and set Renku repository and global options.
  dataset     Handle datasets.
  deactivate  Deactivate environment for tracking work on a specific...
  doctor      Check your system and repository for potential problems.
  githooks    Manage Git hooks for Renku repository.
  help        Show help message and exit.
  image       Manipulate images related to the Renku project.
  init        Initialize a project.
  log         Show logs for a file.
  migrate     Migrate to latest Renku version.
  mv          Move files and check repository for potential problems.
  pull        Pull latest data from server.
  rerun       Recreate files generated by a sequence of ``run`` commands.
  rm          Remove files and check repository for potential problems.
  run         Tracking work on a specific problem.
  runner      Simplify running of CI scripts.
  show        Show information about objects in current repository.
  status      Show a status of the repository.
  storage     Manage an external storage.
  update      Update existing files by rerunning their outdated workflow.
  workflow    List or manage workflows with subcommands.
  workon      Activate environment for tracking work on a specific problem.
```

**To Reproduce**
`renku --help`

**Expected behavior**
I only want to see commands that actually do something.

**Comment by jsam** [comment]
Since all commands do something, but that something is not strictly related to the problem which renku is solving, I completely understand your point. Could you provide us with a list of subcommands/structure you would like to see?

**Comment by ciyer** [comment]
I would say remove the following from the help listing for now since they are either not used or not well documented:

```
  config      Get and set Renku repository and global options.
  deactivate  Deactivate environment for tracking work on a specific...
  pull        Pull latest data from server.
  runner      Simplify running of CI scripts.
  show        Show information about objects in current repository.
  workon      Activate environment for tracking work on a specific problem.
```

* config: Not sure what thearguments/parameters are for this
* deactivate/workon: this is not actually used
* pull: has been replaced by `renku storage pull`
* runner: could be useful, but the functionality needs to be fleshed out
* show: could be useful, but the functionality needs to be fleshed out

**Comment by rokroskar** [comment]
In addition to the above:

* `image`
* move `githooks` to `init githooks install/uninstall`

**Comment by mohammad-sdsc** [comment]
The command syntax with @rokroskar's suggestion would be clunky; the user has to enter:
```
renku init --force . githooks install --force
```
or
```
renku init --force . githooks uninstall
```
The path to the Renku project must appear before the `githooks` command. I could not find a clean workaround for this using Click.

Moreover, when running `renku init` it installs git hooks by default, so, `renku init . githooks install` would be redundant.

I suggest to add a `--uninstall-githooks` option to the `init` command to cover all use-cases:
```
renku init --force --uninstall-githooks # remove git hooks

renku init --force # re-install git hooks
```

**Comment by rokroskar** [comment]
What's wrong with `renku init --force githooks`?

`init --force` does more than just install the hooks, it also modifies several files.

**Comment by mohammad-sdsc** [comment]
We cannot run `init` without `--force` in an already-initialised repo and since after initialisation repo already has git hooks we need to have a second `--force` to force-re-initialise those hooks.
