### ISSUE TITLE
Implement a plugin mechanism for graph extensions

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#594]
The sources of data for the KG are currently hard-coded - we should relax this and provide a plugin mechanism by which we can more easily extend the entities that populate the graph. 

A possible implementation would be a class with two methods

```
can_process(<path-prefix>)
generate_object
```

These classes would be automatically discovered and invoked by a factory function during the processing of a commit.

**Comment by jsam** [comment]
Since the current proposal we have in mind is only limited to extending the graph through Python, I feel we should iterate a bit on it, since I think we can come up with a solution which would be language agnostic. This should probably be an epic accompanied by a proposal.

**Comment by rokroskar** [comment]
closed in #883
