### ISSUE TITLE
Update command should update upstream

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#600]
**Describe the bug**
For workflows, more than 2 steps, updating middle nodes does not update upstream which lead to that node, which causes the wrong output to be generated.

**To Reproduce**

https://gist.github.com/jsam/6c2b0902dca183dcd2904d7aabbb1c52
https://gist.github.com/jsam/89af9e40c6208073c7ebf786d809e087

**Expected behavior**
I would expect that upstream node which leads to a mid node within a workflow to be updated and not just 1 selected node.

**Comment by Panaetius** [comment]
This works correctly with new workflows
