### ISSUE TITLE
cli: renku dataset add arcleman [...]

### ISSUE THREAD

**Issue by ghost** [SwissDataScienceCenter/renku-python#601]
## Describe the bug
I want to add data do a dataset using the basic renku command but it's not working...

## Details
*Please verify and redact the details.*

**Renku version:** 0.5.1
**OS:** Linux (#60-Ubuntu SMP Tue Jul 2 18:22:20 UTC 2019)
**Python:** 3.7.3

### Traceback

```
Traceback (most recent call last):
  File "[...]/renku/api/datasets.py", line 157, in add_data_to_dataset
    dataset, dataset_path, url, target, **kwargs
  File "[...]/renku/api/datasets.py", line 338, in _add_from_git
    submodule_path.relative_to(self.path).as_posix()
  File "[...]/git/cmd.py", line 545, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "[...]/git/cmd.py", line 1014, in _call_process
    return self.execute(call, **exec_kwargs)
  File "[...]/git/cmd.py", line 825, in execute
    raise GitCommandError(command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git submodule add --force --name julia /home/julia .renku/vendors/local/home/julia
  stderr: 'Cloning into '/home/julia/renku-projects/sv_renku_imaging/.renku/vendors/local/home/julia'...
done.
fatal: You are on a branch yet to be born
Unable to checkout submodule '.renku/vendors/local/home/julia''
```

## Additional context
Add any other context about the problem.

**Comment by jsam** [comment]
Hey Julia,

Thanks for reporting the issue. Could you provide us with a little bit more context? Like which parameters did you use on the add command? What is the git structure you are using? Submodules? How did you set the project up?

Thanks.

**Comment by juliabb** [comment]
Hi!

It’s a project located on sv-renku at EPFL. I installed renku, cloned the repository and now I would like to add some data to an already existing dataset “arcleman”. I have been trying all sorts of things for a few hours now but I can’t seem to get it right.

This is the exact input and output:

julia@hummelab-OptiPlex-7040:~/renku-projects/sv_renku_imaging$ renku dataset add arcleman /home/julia/Desktop/new_exports/DICOM
/home/julia/.local/pipx/venvs/renku/lib/python3.7/site-packages/renku/api/datasets.py:302: UserWarning: Importing local git repository, use HTTPS
 warnings.warn('Importing local git repository, use HTTPS')
Ahhhhhhhh! You have found a bug. [:beetle:]

I am not sure that I understand what you mean by git structure and submodules, I am still fairly new to git and renku…

Best regards,
Julia

**Comment by jsam** [comment]
Hey!

Could you paste us the output of the `renku submodule status` while you are in renku repository?

Thanks.

**Comment by juliabb** [comment]
Here you go:

julia@hummelab-OptiPlex-7040:~/renku-projects/sv_renku_imaging$ renku submodule status
Usage: renku [OPTIONS] COMMAND [ARGS]...
Try "renku -h" for help.

Error: No such command "submodule".

**Comment by jsam** [comment]
Sorry, I made a mistake. I meant `git submodule status`.

**Comment by juliabb** [comment]
There is no output:



julia@hummelab-OptiPlex-7040:~/renku-projects/sv_renku_imaging$ git submodule status

julia@hummelab-OptiPlex-7040:~/renku-projects/sv_renku_imaging$

**Comment by juliabb** [comment]
do you have any news?

**Comment by jsam** [comment]
Sorry for the late reply. I'm still trying to reproduce the issue.

**Comment by rokroskar** [comment]
Hi @juliabb - I'm chiming in a bit late here - is `/home/julia/Desktop/new_exports/DICOM` a git repository?

**Comment by rokroskar** [comment]
Closing this for now - @juliabb please reopen if the issue has not been resolved!
