### ISSUE TITLE
incompatible version format

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#604]
apparently cannot use local versions on PyPi https://travis-ci.org/SwissDataScienceCenter/renku-python/jobs/562731291#L1185

Need to have the full version URL available, but the `__version__` to be set to the dev-tag excluding the commit hash.

**Comment by jsam** [comment]
I propose we remove publishing development versions to PyPI. We can use pip to install from git repos for development purposes. Unless there is a real need to publish to PyPi, I say we remove those things and while we are at it remove publishing releases to Zenodo as well. :smile:

**Comment by rokroskar** [comment]
I don't dislike publishing development versions to pypi - this way every merge to master is ready to be used and there doesn't need to be a difference in how they are installed. Publishing to zenodo might be unnecessary at this stage, however.
