### ISSUE TITLE
renku runs hangs and doesn't finish task

### ISSUE THREAD

**Issue by rcnijzink** [SwissDataScienceCenter/renku-python#605]
**Describe the bug**
I updated renku, and now renku run takes forever and hangs. Output-files are produced, but the renku command doesn't finish. I used to have this problem before, but this was solved when I was in Zurich (and so I don't know exactly how it was solved...). It had to do with renku checking if there is a newer version available and it used to happen only the first time renku run was run for that day. Now I never get passed this first time unfortunately. 

**To Reproduce**
I just do renku run

**Expected behavior**
That renku run finishes

**Desktop (please complete the following information):**
Ubuntu 18.04.2 LTS

**Comment by rokroskar** [comment]
Hi @rcnijzink thanks for reporting this - we just updated how the version is handled and it looks like it may have broken some functionality. I am about to merge a PR that should (hopefully) fix this.

**Comment by rcnijzink** [comment]
Ok, thanks! But maybe good to note that I had it with version 0.5.2.dev3, but I also have it with 0.5.1

**Comment by rokroskar** [comment]
Aha ok I see -- it shouldn't happen with 0.5.1. Maybe something else is going on...

**Comment by jsam** [comment]
Can you provide more information? How do you generate output files? Pipe or redirect? Could you maybe provide us with `strace` output to get more information or the steps how to reproduce it?

Thanks.

**Comment by rcnijzink** [comment]
I ran this:
```
renku run python3 src_py/write_namelist.py -is data/ELVIS/sturt_stats.txt --i_cpccf 0.2d-6 --i_lat -17.1507 --i_ksat 2.5d-6 --i_thetar 0.078d0 --i_thetas 0.43d0 --i_nvg 1.56d0 --i_avg 3.6d0 --i_delz 0.2 -o work/SturtPlains/nofreedrainage_cpcff0.2/vom_namelist
```
But is also happens with just something simple, like renku run cp file1 file2.

strace -c give this:
```
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 84.93    0.254255       16950        15         1 wait4
  3.83    0.011458           2      6452           getdents
  2.92    0.008755           2      4025        36 openat
  2.58    0.007722           1      8109      2395 stat
  1.62    0.004864           1      4066           close
  1.58    0.004736           1      4717           fstat
  0.82    0.002453         123        20           clone
  0.55    0.001655           1      1568           read
  0.28    0.000845           2       462           mmap
  0.18    0.000552           1       851        37 lseek
  0.16    0.000470           2       193           munmap
  0.14    0.000423           3       123       119 readlink
  0.12    0.000350           5        69           mprotect
  0.07    0.000210           4        49         6 futex
  0.06    0.000180           2        73           brk
  0.05    0.000151          13        12         9 access
  0.03    0.000089           1       159       148 ioctl
  0.02    0.000074           2        41           pipe2
  0.01    0.000018           0        67           rt_sigaction
  0.00    0.000012           3         4           fcntl
  0.00    0.000010          10         1           arch_prctl
  0.00    0.000009           9         1           rt_sigprocmask
  0.00    0.000009           9         1           sysinfo
  0.00    0.000009           9         1           set_tid_address
  0.00    0.000009           9         1           set_robust_list
  0.00    0.000009           9         1           prlimit64
  0.00    0.000007           0        67         1 lstat
  0.00    0.000005           1         6           getcwd
  0.00    0.000005           5         1           sigaltstack
  0.00    0.000004           1         6           poll
  0.00    0.000004           4         1           flock
  0.00    0.000003           1         3           getuid
  0.00    0.000003           1         3           getgid
  0.00    0.000003           1         3           geteuid
  0.00    0.000003           1         3           getegid
  0.00    0.000002           1         3           uname
  0.00    0.000001           1         1         1 statfs
  0.00    0.000000           0         2           write
  0.00    0.000000           0         3           dup
  0.00    0.000000           0         1           getpid
  0.00    0.000000           0         1           socket
  0.00    0.000000           0         1           bind
  0.00    0.000000           0         1           execve
  0.00    0.000000           0         1           unlink
  0.00    0.000000           0         1           getrandom
------ ----------- ----------- --------- --------- ----------------
100.00    0.299367                 31189      2753 total
```

**Comment by jsam** [comment]
I'm trying to reproduce it, but unsuccessful. I tried both 0.5.1 and 0.5.2dirty.

Are you behind any proxy / Is HTTP_PROXY env variable set?  It's a bit hard for me to tell from this formatting where the issue might be, could you just run strace without flags:

```
strace renku run python ....
```
You can paste it to gist and just link it to here if it's too large.

Thanks.

**Comment by rcnijzink** [comment]
Ok, yes it's big indeed:
https://gist.github.com/rcnijzink/2b776bd941fb68add2c61c39df2f8a15

And no, HTTP_PROXY is not set.

**Comment by rcnijzink** [comment]
Ok, I upgraded to 0.5.2, and tried a couple of things. When I do renku run with an outputfile that was already created and commited before (so basically I update the file), it hangs. Also when I git rm the file. But when I change it to a new file name, not part of the repo so far it finishes as normal.

So this fails as vom_namelist already existed:
```
renku run python3 src_py/write_namelist.py -is data/ELVIS/sturt_stats.txt --i_cpccf 0.2d-6 --i_lat -17.1507 --i_ksat 2.5d-6 --i_thetar 0.078d0 --i_thetas 0.43d0 --i_nvg 1.56d0 --i_avg 3.6d0 --i_delz 0.2 -o work/SturtPlains/nofreedrainage_cpcff0.2/vom_namelist
```

Changing it to this finished as expected:
```
renku run python3 src_py/write_namelist.py -is data/ELVIS/sturt_stats.txt --i_cpccf 0.2d-6 --i_lat -17.1507 --i_ksat 2.5d-6 --i_thetar 0.078d0 --i_thetas 0.43d0 --i_nvg 1.56d0 --i_avg 3.6d0 --i_delz 0.2 -o work/SturtPlains/nofreedrainage_cpcff0.2/vom_namelist_new
```

**Comment by rcnijzink** [comment]
So when I run strace, the last line tells it is waiting:
```
wait4(15278,
```

When I check this PID, it tells me it has to do with git-lfs:
```
UID        PID  PPID  C STIME TTY          TIME CMD
remko    15278 15181  0 14:00 pts/1    00:00:00 git lfs track --
```

When I now kill this process, renku finishes normally. So at least I have a workaround now, but I hope it doesn't harm killing this process.

**Comment by Panaetius** [comment]
What happens if you just run `git lfs track --` in that folder?
How large is the folder, are there many individual files?

When I try running `git lfs track --` it finishes quickly, and I can't reproduce the issue. But with that said, when overwriting files with a `renku run` command, `git lfs track` gets run without it actually needing to be run. https://github.com/SwissDataScienceCenter/renku-python/blob/master/renku/api/storage.py#L135 The `call` here should only be executed if `track_paths` contains some paths. This is a bug in our code that leads to your issue, but doesn't explain why the `git lfs track` command hangs.

**Comment by rcnijzink** [comment]
If I just run `git lfs track`, is shows quickly the list of lfs, no problem there. It only happens when I do renku run with an output file that has been created previously (even when removed afterwards)

**Comment by Panaetius** [comment]
That's weird. 
Can you tell me the output of `python --version`, `git --version` and `git lfs --version` please?

**Comment by rcnijzink** [comment]
So that's this:

Python 3.6.8
git version 2.17.1
git-lfs/2.3.4 (GitHub; linux amd64; go 1.8.3)

**Comment by Panaetius** [comment]
I tried reproducing this issue inside of an Ubuntu 18.04 LTS docker image with the exact same versions of python, git and git lfs, but couldn't reproduce it.

The bugfix in the Pull Request should make it so git lfs is not called in this case, preventing the issue from happening, but I'm unclear on why the call hangs in the first place.

**Comment by rcnijzink** [comment]
Thanks for looking into this! @Panaetius, which PR are you referring to? Do you mean I should update my renku installation?
