### ISSUE TITLE
`renku log --format rdf` produces invalid xml

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#616]
It looks that in some cases `renku log --format rdf` produces syntactically invalid xml documents. When such an xml is pushed to a Triples Store, it responds with `Content is not allowed in trailing section`.

**Reproducing**
My experience is, which unfortunately I cannot prove, is that described behaviour is not always deterministic but at least on our `UI-team` instance it happens all the time for:
* project: `lorenzo.cavazzi.tech/zurich-bikes-tutorial `
* commits: `a40f192f991614ce2ff530146e64fb2c0f148496`,  `e802145e589703cb69c68d092e0c11795548f791`, `7922ee1681d61ffe52f10bb59f28ebc7c380a3b4` and  `1aabd4021acf7c7d4b669ad0d587466a0a1fc7cd`

**Comment by mohammad-sdsc** [comment]
I could not reproduce this issue on `dev.renku.ch`. I've forked `lorenzo.cavazzi.tech/zurich-bikes-tutorial` project which is available at https://dev.renku.ch/projects/95/, and for each mentioned commit ran `renku log --format rdf`. All the XML were valid and I could upload them to Jena.

Renku version on `dev.renku.ch` is `0.5.2`.

[https://app.zenhub.com/files/100947017/c41b3598-d5bb-4b86-a88b-491ac329ad73/download](https://app.zenhub.com/files/100947017/c41b3598-d5bb-4b86-a88b-491ac329ad73/download)

**Comment by mohammad-sdsc** [comment]
I therefore close this issue. Feel free to re-open it if you see this bug again. Since this issue is tricky to reproduce, please attach your project, generated XML file, or any other useful resources that would help to investigate it more.

**Comment by jachro** [comment]
I'd rather keep that open as we know it happens. What I'll do, is I'll instrument the code which sends the data to Jena and dump the RDF XML when Jena responds with this error.

**Comment by ciyer** [comment]
This is possibly also happening on https://dev.renku.ch/projects/cramakri/renku-tutorial-flights/files/lineage/notebooks/00-FilterFlights.ran.ipynb

**Comment by jachro** [comment]
I tried to reproduce the error by instrumenting the code and re-provisioning more than 2.2k events. No exceptions were raised so I assume the bug has got fixed with some other change.
