### ISSUE TITLE
Export to Zenodo failed, missing metadata

### ISSUE THREAD

**Issue by jen-thomas** [SwissDataScienceCenter/renku-python#618]
I added more files to an existing dataset, then  exported the dataset to Zenodo, but some of the metadata fields are missing so it failed. 

```
jen@jen:~/projects/ace_data_management/renku-projects/meteorology/data$ renku dataset export meteorology zenodo
  0%|                                                                                                                      | 0/2 [00:00<?, ?it/s]{'filename': 'README.txt'}
 50%|███████████████████████████████████████████████████████                                                       | 1/2 [00:01<00:01,  1.22s/it]{'filename': 'data_file_header.txt'}
100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [00:02<00:00,  1.13s/it]
Usage: renku dataset export [OPTIONS] ID PROVIDER

Error: Invalid value: 
"metadata.creators" failed with "Shorter than minimum length 1."
"metadata.description" failed with "Field may not be null."
```
[metadata.txt](https://github.com/SwissDataScienceCenter/renku/files/3462247/metadata.txt)

Please let me know if you need any more information.

**Comment by rokroskar** [comment]
Just adding this here for clarification - we need to:

- [ ] make export errors about missing metadata more informative
- [ ] propagate metadata where necessary
- [ ] ensure metadata can be properly adjusted from an older renku version

**Comment by Panaetius** [comment]
We will be reworking the way metadata is set (in #621 ), so I only added a more informative error message for this issue for now. Once we decide on what to do with metadata exactly, we can revisit this issue. 

You can edit metadata with the `renku dataset edit <dataset>` command. If you write some text after `description:` and add a creator to the `creator:` entry it should work. You're creator entry looks like `creator: []` right now, but it should look like this:

```
creator:
- '@type': schema:Person
  _id: mailto:<email>
  affiliation: <e.g. SDSC>
  alternate_name: null
  email: <email>
  name: <e.g. Jen Thomas>
```

And replace the `<...>` entries with appropriate values.

Then it should work.

**Comment by jen-thomas** [comment]
Hi @Panaetius. That's great thanks, it works fine.
