### ISSUE TITLE
Check export metadata before file upload to Zenodo

### ISSUE THREAD

**Issue by jen-thomas** [SwissDataScienceCenter/renku-python#625]
**Is your feature request related to a problem? Please describe.**
I've just exported a dataset to Zenodo, but the dataset had a lot of files (2822 files, size 3.7 GB). All files uploaded but after completing the upload, there was an error with the metadata (see section below). 

Before running `renku dataset export <dataset> zenodo`, I had edited the dataset metadata (`renku dataset edit <dataset>`) and added information to various fields and although I came up with a few errors at that time, they had all been corrected before the `export` was done. 

If it was a small number of files it wouldn't have mattered, but given the time it took to upload, I did not want to repeat the export. The creation of the draft DOI was successful even with the missing metadata and I was able to add in the missing metadata directly into the DOI draft. 

**Describe the solution you'd like**
- Report errors or null fields in metadata before the upload of files begins (this would particularly be helpful in the case of large datasets).

**Describe alternatives you've considered**

**Additional context**
Below is the print out of the end of the file upload and error: 

{'filename': 'README.txt'}
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2822/2822 [3:44:05<00:00,  6.70s/it]
{'metadata': {'title': 'Uncorrected inertial navigation dataset collected on board the R/V Akademik Tryoshnikov during the austral summer of 2016/2017 as part of the Antarctic Circumnavigation Expedition (ACE).', 'upload_type': 'dataset', 'description': None, 'creators': [{'name': 'Jen Thomas', 'affiliation': 'Swiss Polar Institute, Switzerland'}]}}
Usage: renku dataset export [OPTIONS] ID PROVIDER

Error: Invalid value: 
"metadata.description" failed with "Field may not be null."

**Comment by rokroskar** [comment]
Thanks for reporting this @jen-thomas - definitely something we should fix asap!
