### ISSUE TITLE
DataSet's schema:dateCreated triples not in ISO format

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#627]
It looks like `schema:dateCreated` triples generated for a dataset are NOT in the ISO format. For instance, instead of `1981-09-05T10:38:29.457Z` there's `2019-08-07 08:59:07.965069`. The problem occurs for both the dataset and the dataset's files triples.

**Comment by jsam** [comment]
Is this imported dataset or renku created/managed one?

**Comment by jachro** [comment]
That's renku created/managed dataset but I haven't checked the imported
one, yet.
