### ISSUE TITLE
Programmatically determine in- and output paths

### ISSUE THREAD

**Issue by ableuler** [SwissDataScienceCenter/renku-python#630]
After resolving #542 through #598 it will be possible to explicitly provide in- and output paths to a `renku run` command. This makes it possible to track the lineage when in- and output paths are hardcoded in a script.

What is not addressed by #598 is the use case where the paths of in- and outputs are derived from other inputs during the execution of a script. For example, when providing a date range to a script, the script might first determine which raw data files where produced during this date range and then process all those files. Renku should offer a way to record those files as inputs.

This use case could be enabled if the script was dumping the computed list of in- and outputs as a temporary file to some specified location in the `.renku/` directory. After the actual script has run to completion, `renku run` could then check for the existence of such a temporary file and add the in- and outputs to the other in- and outputs of the `renku run` command.

**Comment by mohammad-sdsc** [comment]
This looks like a rather specific use-case. The script doesn't know what input/output files it's going to access in advance and hence it is not possible for the user to pass that information to Renku. The script must be modified to pass that information to the outside world (e.g. Renku).

My suggestion is to ask user to write a pre-processing script to print (or write) the list of all such input/output files. The user then can use this information to write a proper `renku run` command with necessary `--input` and `--output` arguments. The user has to modify the script anyhow to provide that information to Renku. It might be actually easier to write a separate script for that purpose. Moreover, on our side we don't need to add any new feature to Renku and the current solution works fine.

**Comment by mohammad-sdsc** [comment]
If we decide to implement this feature anyway then the suggested solution seems quite feasible. However, instead of using a hard-coded location in `.renku/` directory, I'd prefer to have this temporary file be passed as an argument to `renku run`:
```
renku run --input-files-list inputs.txt --output-files-list outputs.txt script.sh
```

In this way, the script does not need to know about the existence of the `.renku/` directory which might make it easier for the user to implement this feature. These input and output files list can be outside the project folder (e.g. /tmp) since they are accessed temporarily by Renku. Moreover, if we want to allow parallel `renku run`s in future version this solution would work for any number of parallel executions while the other one only allow one execution at a time.

**Comment by ableuler** [comment]
It's true that this use-case is quite specific and it's hard to assess how often this feature would be used, but it doesn't seem super far-fetched to me. And it was specifically asked for by @lusamino. The absence of this feature essentially keeps him from using the renku cli in one of his projects. 

I believe that writing a separate script which creates the proper `renku run` command with all the right inputs would be more cumbersome for users mostly for two reasons:
- It could force users to duplicate a large fraction of their actual script.
- The generated `renku run` command could be rather long, potentially leading to problems with the maximum command size (see #552) that we could otherwise avoid.

I like the idea of letting users decide where they want to dump the file with the inputs. However, it might be worth considering to define one default location which is always checked. In the future this could allow for a python script like this:

```
from renku import mark_input

# Compute file of inputs given the argument passed 
# to the script
...

for file_path in input_paths:
    mark_input(file_paths)

    # Actual processing of file
    ...
```

It would be nice if something like this could be invoked simply by running `renku run script.py`, without passing any `--input-files-list` parameter. Therefore I would like to have one default location defined which is checked for inputs.

**Comment by rokroskar** [comment]
What about passing an environment variable to the shell where the command is executed? Something like `RENKU_FILELIST_PATH` - the user would then do something like:

```
with open(os.getenv('RENKU_FILELIST_PATH')) as f:
    f.write('\n'.join(filelist))
```

**Comment by mohammad-sdsc** [comment]
@ableuler I liked the idea of having `mark_input`. Let's go forward with your initial suggestion then (i.e. having temporary files in `.renku`). I would create a `.renku/tmp` directory and use `inputs.txt` and `outputs.txt` in this directory for purpose of marking indirect dependencies. 

In future, we can make the whole process easier by proving a helper package (i.e. `mark_input`). We can also add `--input-files-list` and `--output-files-list` later.

**Comment by mohammad-sdsc** [comment]
@rokroskar I would go with the predefined location solution. Using environment variable would complicate things when we have multiple projects while the other solution is isolated within a project.

**Comment by rokroskar** [comment]
The env. variable could point to a location inside a project - it would just be an easy way to keep the location flexible, e.g. in the case of parallel executions or some other more complicated patterns
