### ISSUE TITLE
`schema:creator` pointing to `mailto:None` for imported data-set

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#632]
It looks like in cases when a data-set is imported, the `schema:creator` triple points to `<mailto:None>` resource. As a consequence, I imagine all the triples from all the projects and imported data-sets will be put into one `schema:Person` `<mailto:None>` bag during triples generation process.

Reproducing:
repo: `git@dev.renku.ch:virginiafriedrich/datasets-test.git`
commit: `46a77c18a31e42d356be7e6d4eac5ad35468e881`
command: `renku log --format rdf`

**Comment by rokroskar** [comment]
How should this be handled? In some cases we get only the name from the provider - but maybe we should get away from using the email for the userid anyway. So perhaps in the case where we have no other info we can make the `id` of the `Person` be e.g. `https://renkulab.io/<firstname><lastname>`

In the case where a remote doesn't exist, we can make it remote-agnostic e.g. `https://renku.ch/<firstname><lastname>`.

**Comment by rokroskar** [comment]
Actually that won't even work because in some cases we just get `name` - we could leave the `id` blank also if we don't have enough identifying information. That might be the way to go.

**Comment by jachro** [comment]
I'd agree that should be fine for the imported datasets. As long as we don't have a strong id from the place we import the data, any attempts of linking by a person could be a bit dangerous.

**Comment by rokroskar** [comment]
ok, lets go with that then - I think it should be a simple change.

**Comment by rokroskar** [comment]
maybe as a temporary workaround we could go and replace those identifiers with blank nodes with a manual query

**Comment by jachro** [comment]
I suppose we should be fine as with a new version of `renku CLI`, triples generator will reindex automatically. There should be only one bag of leftovers for the blank nodes which is not linked to anything. I can add a simple delete query to the re-provisioner to get rid of them.
