### ISSUE TITLE
Project metadata to contain info about project name and creator

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#659]
As a Renku owner, I should be able to find `schema:name` and `schema:creator` among the project triples like follows:
```
<rdf:Description rdf:about="https://dev.renku.ch/virginiafriedrich/datasets-test">
  <rdf:type rdf:resource="http://www.w3.org/ns/prov#Location"/>
  <rdf:type rdf:resource="http://xmlns.com/foaf/0.1/Project"/>
  <schema:name>namespace/project-name</ns1:name>
  <schema:creator rdf:resource="https://orcid.org/0000-0003-4498-2870"/>
</rdf:Description>
```

**Comment by rokroskar** [comment]
Could we do JSON-LD or just n-triples instead of RDF in the descriptions? Would be easier to parse :)

**Comment by jachro** [comment]
I could expect that request :) Here you go:
```
{
  "@context": {
    "foaf": "http://xmlns.com/foaf/0.1/",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "schema": "http://schema.org/",
    "xsd": "http://www.w3.org/2001/XMLSchema#"
  },
  "@id": "https://dev.renku.ch/virginiafriedrich/datasets-test",
  "@type": [
    "http://www.w3.org/ns/prov#Location",
    "foaf:Project"
  ],
  "schema:creator": {
    "@id": "https://orcid.org/0000-0003-4498-2870"
  },
  "schema:name": "namespaceproject-name"
}
```

**Comment by rokroskar** [comment]
Ah thank you! :)

**Comment by jachro** [comment]
Actually, I'm thinking now whether the `creator` should not be swapped with an `agent`? That would maybe give some more consistency with the data-sets where a person who created a data-set is represented with the `agent` triple.

**Comment by rokroskar** [comment]
Hmm... this is maybe a bit confusing. `Agent` comes from the person who committed the dataset to the project - in the case where the dataset is imported from an external repository e.g. zenodo, then `Agent` and `Creator` are likely different. But if I create a dataset in my own project, I am both the `Agent` and `Creator. So in the context of the project it's a bit ambiguous to me which one makes more sense.

**Comment by jachro** [comment]
Yes, I see your point. So should we stick to the `creator` for a project?

**Comment by rokroskar** [comment]
That would be my tendency, but I'm willing to change my mind :)
