### ISSUE TITLE
`renku log` to generate project resource pointing the Renku projects resource

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#660]
As a Renku owner, I'd like `renku log` to generate project's resources triples pointing to the `http(s)://renku/projects/namespace/project-name` instead of `http(s)://renku/namespace/project-name`.

**Comment by rokroskar** [comment]
isn't this a duplicate of #554?

**Comment by jachro** [comment]
Yes, you're right.
