### ISSUE TITLE
`renku log` to generate dataset resource pointing the Renku dataset resource

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#661]
As a Renku owner, I'd like `renku log` to generate project's resources triples pointing to the new `GET /knowledge-graph/datasets/:id` endpoint.

**Comment by rokroskar** [comment]
So you want the identifier of the dataset node to point to e.g. `renkulab.io/knowledge-graph/datasets/:id`?

**Comment by jachro** [comment]
Either that or `renkulab.io/datasets/:id` which I'd even like more. The problem is with the `projects` resource as I think our UI already has an endpoint like `<renku>/projects/:name`. It would be nice if all of the KG based resources fall into a similar pattern.

**Comment by rokroskar** [comment]
So what data will these endpoints serve? JSON-LD? Because in that case, you could use the same endpoint but a different content type.

**Comment by jachro** [comment]
I guess it's up to us to decide about the content-type. `JSON` seems to be given for free and `JSON-LD` we can do too if needed.

When I mentioned the `<renku>/projects/:name` on the UI, what I wanted to say is that this particular endpoint is I think taken by UI so I guess it Gateway serves some HTML for it. I'd quite like if the KG based resources like `projects`, `data-sets`, `users` and so on are served from Renku like `<renku>/projects|datasets|users/:name|:id` so our Gateway would map them to relevant endpoints on the knowledge-graph. But hold on, if Gateway already serves HTML for `<renku>/projects/:name` maybe it can forward to knowledge-graph for other content-types? Is that what you meant?

**Comment by jachro** [comment]
Great! Let me then create another issue on this epic for the Gateway.
