### ISSUE TITLE
Log in to remote renku platform with the CLI

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#677]
**Is your feature request related to a problem? Please describe.**
A user should be able to log in to the hosted renku platform with the command-line client. This 

**Describe the solution you'd like**
`renku login <endpoint>`

optionally, the default endpoint could be set in the configuration, e.g. 

`renku config --set endpoint=renkulab.io`

The specific use-case is to implement a credentials helper to make pushing/pulling from git repositories and docker registries less painful. For example, one could do something like

```
renku login https://renkulab.io
> Username: abcd
> Password: 1234
```

This would store my JWT for renkulab.io and when I did
```
git push https://renkulab.io/...
```

it would swap that JWT with the gateway for a scoped oauth2 token that it could use for the git commands. A similar credentials helper could (presumably) be implemented for logging in to the docker registry, making it much easier to work locally with images produced by the CI pipelines. 

**Describe alternatives you've considered**
Writing really long documentation about ssh keys and private tokens. 

This has been partially (or almost fully?) implemented in #193 

This one is a good example of a good UX https://concourse-ci.org/fly.html#fly-login and more-or-less what was attempted in #193.

**Comment by mohammad-sdsc** [comment]
We decided to limit the scope of this story to authentication and storing the token. Logging in to gitlab will be done in a followup story: #1892.
