### ISSUE TITLE
Do not use submodules for data import

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#679]
In the current implementation, git submodules are used to handle importing data from other git repositories (including renku projects). This has the benefit of providing versioning and syncing support with upstream changes using git tooling, but submodules are hardly anyone's favorite aspect of git. It seems that a simpler solution might be to implement the synchronization part on the renku side and simply copy the data from the source repository into the desired location in the renku project. 

Some requirements: 

- store sufficient metadata to allow for easily identifying the source and repeat the download if necessary
- if the source is a renku project, the link should be made explicit in the metadata and get passed on to the KG
- provide the means to easily pull in changes to imported data from the source

**Comment by mohammad-sdsc** [comment]
One feature that we lose when moving away from using submodules is that we don't see lineage from the remote repo with `renku log`. A local renku project cannot have that information unless it has access to the full remote repository. For projects hosted on a server (e.g. renkulab.io) it would be possible to fetch remote linage information from a service hosted on the server.

**Comment by rokroskar** [comment]
We should also be careful not to break backwards compatibility here - ideally existing renku projects with data imported from other git repositories should continue to work.
