### ISSUE TITLE
renku status fails on forked project with submodules

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#680]
**Describe the bug**
A call to renku status spits out a bug message when calling `renku status` or `renku log` on a project that has/had submodules.

**To Reproduce**
1. Go to (private project; ask to be added) https://sv-renku.epfl.ch/projects/131/
2. Fork project
3. Clone locally or start notebook
4. Call `renku status`

fatal: No url found for submodule path '.renku/vendors/git@sv-renku-git.epfl.ch:lisp/bxd_dataset_renku' in .gitmodules

**Expected behavior**
Whatever renku status is supposed to return -- I'm not sure!

**Comment by Panaetius** [comment]
We don't officially support submodules anymore as the upstream git library doesn't support submodules anymore, unfortunately. Closing this as WONTFIX
