### ISSUE TITLE
Implement "update" for imported data

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#682]
After #681 renku will need to handle version information of imported data. We should provide functionality to allow the user to update the data by pulling in changes from the source repository/project e.g. 

```renku dataset update <path>```

This should default to pulling in the latest changes but optionally take a `--ref` option to specify a tag, commit, or branch. The dataset metadata should be update accordingly.

**Comment by mohammad-sdsc** [comment]
The syntax chosen for this command in https://github.com/SwissDataScienceCenter/renku-python/pull/757 was different than the one proposed here. To be in par with some other `renku dataset` commands the syntax is:
```
renku dataset update -I <include-pattern> -X <exclude-pattern> --creators <creator-name> [dataset-1-name] [dataset-2-name] ...
```
All of these are optional and are used to further filter the list of files to be updated. If not option is passed, all datasets are updated.

Caveats:
* The `--ref` option is not implemented in https://github.com/SwissDataScienceCenter/renku-python/pull/757
* Datasets that are based on the submodules are not updated by this command
