### ISSUE TITLE
bug: when renku dataset create fails, metadata still created

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#684]
**Describe the bug**
When `renku dataset create <name of dataset>` fails, there is still metadata created in `.renku` (but not a new directory under `data/`) which causes the subsequent attempt at creating a dataset with the same name to fail "mysteriously".

**To Reproduce**
1. `renku dataset create mydataset` <-- with some stuff that fails; you could try un-configuring your git config name and email, for instance.
2. `renku dataset create mydataset`

**Expected behavior**
Instead, it should be possible to create the dataset with the same name since the first time failed.

**Comment by emmjab** [comment]
Just to add to this -- if a `renku dataset add` fails (can test by trying to add data from a fake path), and you accidentally wrote the wrong name for the dataset, a `data/<dataset name>` folder gets created and metadata get added for that new dataset name. I think the folder & metadata should be removed (or never added) if no data comes through.

**Comment by mohammad-sdsc** [comment]
The issue with accidental creation of a dataset will be addressed in https://github.com/SwissDataScienceCenter/renku-python/issues/688 where we add an explicit command line argument for creation of non-existing datasets.
