### ISSUE TITLE
dataset create/add functionality

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#688]
**Is your feature request related to a problem? Please describe.**
Currently `renku dataset add <my dataset name> <data path>` will silently first create the dataset if `<my dataset>` doesn't exist (but with no creator). Then, if the provided `<data path>` is malformed/no data is retrieved, there's irrelevant files and metadata around from the dataset creation step even though the data add fails.

**Describe the solution you'd like**
Instead, `renku dataset add <my dataset name> <data path>` should return an error: `Please first create the dataset with: renku dataset create <my dataset name>`.

**Additional context**
I think it's confusing to ask users to "create a dataset" that doesn't have any data in it. When you call the "create dataset" command, you're creating an empty folder to hold the data, and adding a file in preparation to be populated with metadata about where the data comes from, etc.

**Alternative based on additional context**
Maybe it makes sense to augment the `renku dataset create` command with `--add <path to data>` so that you can create and add data at the same time, and it's from the perspective of "creating a dataset":
ex:
`renku dataset create zhbikes --add <url to data.csv>`
`renku dataset create zhbikes --add <url to data.git> --rel-data path/to/mydata.csv`
`renku dataset create zhbikes --add <local/path/in/repo>`

**Comment by rokroskar** [comment]
what about `renku dataset add --create zhbikes <url to data>`?

**Comment by mohammad-sdsc** [comment]
I've picked @rokroskar suggestion when implementing this. Users must pass `--create` when adding data to a non-existing database or the operation fails with proper error message.
Moreover, if they provide `--create` with an existing database they also receive an error.
