### ISSUE TITLE
ls-files doesn't show files outside of project root

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#689]
Currently, `renku dataset ls-files` only lists files inside the project, not files that reside outside the project.

This should be fixed to list all the files in a dataset.

**Comment by rokroskar** [comment]
hmm - don't think this is quite accurate. It doesn't work in a subdirectory of a project. 

To reproduce: 

```
renku init test-dataset-subdir
cd test-dataset-subdir/
touch file
renku dataset add mydata file
cd data/
renku dataset ls-files
```

**Comment by mohammad-sdsc** [comment]
This is not the case anymore. Also the bug Rok mentioned is fixed.
