### ISSUE TITLE
`renku log` to generate relevant triples on dataset removal

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#709]
As a Renku user, when I remove a dataset from my project, I'd like this dataset not to be visible among its datasets. However, it should still be visible on all the other projects which either forked from my project earlier when the dataset was present or imported it.

**Assumptions:**
* the issue is played after the [dataset immutability issue](https://github.com/SwissDataScienceCenter/renku-python/pull/1142).

**Acceptance criteria:**
* Renku CLI to create a new version of the removed dataset with additional `prov:invalidatedBy` link to the commit activity where the deletion happened;
* the new version of the dataset should be done in a way described in the dataset immutability issue.

**Comment by rokroskar** [comment]
What we need to specify is what this should include. The easiest seems to be something like [`invalidated`](https://www.w3.org/TR/prov-o/#invalidated) from prov-o. From that definition:

> Invalidation is the start of the destruction, cessation, or expiry of an existing entity by an activity. The entity is no longer available for use (or further invalidation) after invalidation. Any generation or usage of an entity precedes its invalidation.

There is also the inverse `invalidatedBy` which would make an outgoing edge from the entity to the commit, which may be easier in your graph query. But if you just filter on the absence of this predicate I guess it doesn't matter.

**Comment by jachro** [comment]
I quite like the idea of `invalidatedBy` as it would leave a trace of the removal operation. However, if its direction is from an entity (a dataset in this case) to a commit, the problem I can see here is if a dataset would be linked to another project (which I believe would be the case when a dataset was imported from another Renku project or whatever else). So having this kind of trace would be nice but from the other side, a more general question is appearing whether our KG should work as an audit log or rather simply be a source of truth about what's available now. I can imagine the second option could be easier to maintain, smaller in size and ... maybe good enough and what we would expect from it? Going this direction, the only thing we'd have to do for the dataset removal is just deleting the `isPartOf` triple from the dataset and eventually do a complete removal of a dataset with its parts, creators and so on, if there's no other `isPartOf` on it.

Ideas, thoughts?

**Comment by rokroskar** [comment]
Right I guess that would be similar to the git/github behavior where it eventually garbage collects objects when there are no more references to them when history gets overwritten. But in this case there was no force-push, the object was just deleted from the working tree. So if the user wanted to see the state of the project before the delete, they couldn't. Therefore I think we can only remove on a force-push.

**Comment by jachro** [comment]
Right, right. So do you mean we'd eventually like to have some API which would allow fetching project's datasets at certain commit? It seems to me to be a bit niche feature but maybe we shouldn't close the door to do it at some point.
So how do you think we should mark a dataset as invalidated by a certain commit and project? At the moment we've got, let's assume one or more, `isPartOf` on a dataset. Do you think we add `invalidatedBy` to a dataset pointing from the dataset to a dataset deleting commit? Then, still assuming we've got few `isPartOf` we could have as many `invalidatedBy` triples on a dataset as many projects the dataset is linked to. I guess the datasets finding queries could become more complicated but doable.
Is that what you think?

**Comment by rokroskar** [comment]
It's not a niche feature at all - right now we only show the tip of the master branch in the UI but we have for a long time planned to allow the user to view/browse the project history. In that case going back to a commit before the dataset deletion will mean that we need to show the dataset. It won't make the queries necessarily more complicated - we can simply pass that information to the UI and they can choose to display the dataset or not. For example, there could be a drop-down with a listing of deleted datasets that you could re-instantiate if you wanted. Of course, the datasets are a bit of a special case - we do need to do the same for other entitiees (files) that get deleted. We don't at present handle deletion very gracefully in some cases and this needs to be revisited anyway so it's a good time to have the discussion.

**Comment by jachro** [comment]
Agreed.
So should then we go for the `invalidatedBy` on a dataset? I think I can see how this could work but the relations between dataset, project(s) and commits will become a bit more complicated.

**Comment by vfried** [comment]
I think we should go for the invalidatedBy, shall we give the "owner" the option of deleting but allowing other users to still access the dataset? In case a dataset is in a project and the owner doesn't want to use it but sees that other people are using it so he will keep it available for other people?

**Comment by vfried** [comment]
Another option is that we "unlink" the dataset from a user or namespace but we allow the dataset to keep living if some other project is using it.

**Comment by jachro** [comment]
We discussed that option of `hard unlinking` but @rokroskar'd like to see the dataset on a project when you move back in history to a certain commit when they were still together :)

**Comment by vfried** [comment]
I see, and i guess that makes sense also.

**Comment by rokroskar** [comment]
This will be handled differently now that the graph metadata has been refactored.
