### ISSUE TITLE
renku dataset erroneously reports "Migration is required"

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#714]
**Describe the bug**
If a renku project has a submodule that contains data, `renku dataset` reports that the project needs to be migrated. This is incorrect.

**To Reproduce**
- Add as a submodule in the `data` folder a renku project that contains data

**Expected behavior**
Renku should not consider submodules when determining if datasets need to be migrated.

**Desktop (please complete the following information):**
- renku version: 0.6.1.dev4

**Comment by mohammad-sdsc** [comment]
This cannot be re-produced with version `1.2.1`:
```
$ git submodule add git@github.com:SwissDataScienceCenter/calamus.git data/calamus
$ git commit -m calamus
$ git submodule init # Just to make sure that the submodule contains data
$ git submodule update

$ renku dataset create my-dataset # Sample renku command
Use the name "my-dataset" to refer to this dataset.
OK
```
