### ISSUE TITLE
renku log to generate single identifier for dataset imports of the same resource

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#719]
As a Renku owner, I'd like to have a single dataset `resource` and `identifier` when importing the same dataset to different projects.

Acceptance criteria:
* When a dataset is manually created in Renku (a non-imported dataset case) then:
`@id` = `https://renku/datasets/<identifier>`
`schema: identifier` = `identifier` (a generated UUID);
* When a dataset is imported from Zenodo then:
`@id` = `https://renku/datasets/<identifier>` where `identifier` is url encoded
`schema: identifier` = the original dataset identifier as on the imported dataset (DOI)
* When a dataset is imported from Dataverse then:
`@id` = `https://renku/datasets/<identifier>` where `identifier` is url encoded
`schema: identifier` = the original dataset identifier as on the imported dataset (DOI)

Also, the `dateCreated` should not but put into triples generated by `renku log` command as it will be multiplied by a number of projects using a particular dataset.

**Comment by rokroskar** [comment]
Thanks @jachro for writing this up - It's not necessary to differentiate between zenodo/dataverse, the important part is to use the DOI as the identifier and to agree on how to escape `/`. DOI's will always be resolvable and are guaranteed to be unique.

**Comment by jachro** [comment]
@rokroskar so what do you suggest as a format for the imported datasets? Would smth common of this flavour `10.5281-imported.3266798` or simply `<DOI>` work? I'd maybe tempted to add at least some differentiator on top of the DOI to prevent eventual clashes of DOIs from different providers.

The other issue of `dateCreated`. Should `renku log` drop adding `dateCreated` to the dataset triples? I believe there's no way for `renku log` to know if a dataset was already imported in some project so it should not add another `dateCreated`. I'd also like to keep triples-generator as dumb as possible so it doesn't have to 'understand' what triples it's generating and eventually transform them before sending through to Jena. What I'm thinking about in terms of a dataset creation date, is to reach to the commit of the dataset and take either `prov:startedAtTime` or `prov:endedAtTime` as I don't think we have a `dateCreated` on the commit triples (maybe we can add one ;) ) Actually, we do that for the agent anyway and we map it to a person who created the dataset (in simple words, the dataset agent/creator, not to be mixed up with a person who published the dataset). Any thoughts?
