### ISSUE TITLE
Streamline internal references to datasets

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#721]
As @Panaetius pointed out in #690 we have a quite a few spots where we handle datasets either by name or id. This is due to legacy where name was the id in previous versions of renku. Since from version 0.3.4+ renku uses internal refs to determine unique datasets we should streamline all our references to use them (unless specified otherwise by the user).

```
def edit_dataset(client, dataset_id, transform_fn): --> dataset_id
def file_unlink(client, name, include, exclude): --> name
def dataset_remove(client, names, with_output=False): --> names
def export_dataset(client, id, provider, publish, tag, with_prompt=False): --> id
def tag_dataset(client, name, tag, description, force=False): --> name
def remove_dataset_tags(client, name, tags): --> name
def list_tags(client, name, format): --> name
```

**Comment by Panaetius** [comment]
This is consistent in current master, closing
