### ISSUE TITLE
Drop support for Python 3.5

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#722]
This discussion has arisen several times now due to the problems we have encountered in the wild with Python 3.5 and all the hacks which we had to do due to this support. I propose we drop the support for 3.5 completely and keep moving forward.

This ticket serves as a purpose to collect all the changes needed to address this change:

* Delete compat.py
* Move all abspath resolutions to Path().resolve()
* Ordered Dict changes
* Path to str casts

**Comment by mohammad-sdsc** [comment]
We still need `compat.py` (e.g. for `contextlib.nullcontext` which was introduced in `3.7`).

Also, `os.path.abspath` is not the same as `Path.resolve()`; it does not resolve symlinks which is critical for external storage to work properly.

**Comment by rokroskar** [comment]
`Path.resolve()` doesn't resolve symlinks? there's probably an option to do it?

**Comment by mohammad-sdsc** [comment]
Well, `it` referred to `os.path.abspath` ;). I've updated my comment.
