### ISSUE TITLE
Redesign the LocalClient approach

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#726]
Currently. LocalClient gets injected in many places by the `pass_local_client` decorator. This can lead to locking issues and makes it difficult to compose functionality in some cases. Plus it's some hidden magic that makes the code harder to reason about.

We should come up with a better abstraction than injecting a client, especially in light of the recent RaaS changes where the concept of client will take on a different shape anyways.

This ticket is for discussing and deciding how to handle the `LocalClient` functionality in a better way in the future.

**Comment by mohammad-sdsc** [comment]
Related: https://github.com/SwissDataScienceCenter/renku-python/issues/1349

**Comment by Panaetius** [comment]
Superseeded by https://github.com/SwissDataScienceCenter/renku-python/issues/1626
