### ISSUE TITLE
Renku as a Service

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#731]
Enable all CLI commands to be accessible via HTTP. Mapping should include all arguments and options. 

Additional, work which needs to be done is (besides exposing implementation already reachable in CLI): 
* Cloning external repositories
* Deleting cached repositories
* Uploading a file

related: #732 #734

**Comment by jsam** [comment]
First step to enable this has be done with #690, which produced followup tickets. Those tickets which touches on datasets and workflows should be addressed before moving forward with this topic.

**Comment by rokroskar** [comment]
This is done! 🚀
