### ISSUE TITLE
Add Github actions for integration/deploy etc.

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#739]
https://github.com/SwissDataScienceCenter/renku-python/pull/622 Added github actions for basic testing, but it lacks deployment, integration tests and other stages that we currently have in travis.

Since the actions have been working well in the last couple of weeks, I propose to move ahead with moving the rest of travis stuff to github actions as well.

**Comment by rokroskar** [comment]
I agree! would make things quite a bit simpler imo.
