### ISSUE TITLE
Convert a project into a template

### ISSUE THREAD

**Issue by ciyer** [SwissDataScienceCenter/renku-python#740]
# Description

Renku should offer a command to convert a project into a template. After https://github.com/swissdatasciencecenter/renku-project-template/issues/34, we will know what template was used to create the project. Any files that have template parameters should be set to the same state as in the template. Other files should be taken from the current project.

```bash
renku to-template
```

**Comment by rokroskar** [comment]
What happens when you convert the project to a template? Does it get bundled and pushed somewhere? Where? This has the potential to end up with really noisy templates. I would prefer to have a clearly documented and simple template prescription without too much magic. We could potentially offer a meta-template that could be forked or cloned and pushed.

**Comment by rokroskar** [comment]
Is this still something we want to do? Seems like forking is fine for this purpose? @Panaetius ?

**Comment by Panaetius** [comment]
I think forking works well for this use-case and that templates should be hand curated. There's too many open questions (Off the top of my head: What happens with LFS files in the project? what happens with metadata like datasets and workflows? If we want to keep it, how would we migrate it? should/how would we keep the provenance? How would we set templatable parameters in the template?)

I think forking covers the use-case of having a certain project state, whereas templates are for having an initial state of non-renku file/dependencies to get a project started.

**Comment by rokroskar** [comment]
Yes, I completely agree with this - there are just too many things we'd have to "clean" out if we wanted to make a template out of an existing project. I'd favor closing this - @ciyer?
