### ISSUE TITLE
Zenodo Rate Limiting

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#760]
Zenodo has added rate limiting for API requests that will yield an http error if too many requests are done in succession, e.g. `429 Client Error: TOO MANY REQUESTS for url: https://zenodo.org/api/files/b5a695c8-6203-47e1-a36b-089cfac61705/quantling/pyndl-v0.6.2.zip` 

This causes integration tests to fail, usually when running the `tests/cli/test_integration_datasets.py::test_dataset_import_real_http[https://zenodo.org/record/2621208] ` test on my machine (might differ depending on machine/internet connection)

Figure out how to not spam Zenodo/get integration tests to work. Also check if this could lead to other issues, e.g. when importing a dataset with many small files, and add rate limiting for download again. 

I couldn't find any information on what the actual limit is on the Zenodo side, maybe ask them?

**Comment by jirikuncar** [comment]
Consider using recording responses from external services using e.g. https://betamax.readthedocs.org.

**Comment by Panaetius** [comment]
That's a good idea, though the reasoning behind using the live api as far as I understood is that Zenodo changes their api and model somewhat regularily and this allows us to catch that. Though we should at least change it to use the Zenodo sandbox if possible.

Closing this issue for now as it was fixed in #762
