### ISSUE TITLE
RaaS: Add existing project files to datasets

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#769]
Currently, from the service there is only a possibility to add uploaded files to the dataset. We need an option to add existing project files to datasets.

**Comment by rokroskar** [comment]
There should also be the possibility to do what is currently usually done, which is to add files via a URL. This issue could be generalized to that use-case IMO.

**Comment by jsam** [comment]
There are 2 possible ways to add a data file to the project. 


**By upload**

In this scenario, we start by uploading a data file to the cache and receive a reference ID. This reference ID could be then used in the following endpoint:

```
/projects/add
```

where payload would be
```
{
    "type: 1,
    "file_id": <reference_id>,
    "project_id": <project_id>,
    "relative_path": <path from root of the repository where that files should be placed>,
    "commit_message": <commit_message>
}
```

This action could be performed in sync way and could return following response:
```
{
    "result": {
        "commit": <created commit>
    }
}
```

or error if one occurred:
```
{
    "error": {...}
}
```


**By external crawl**

In this scenario, we submit a remote URL containing the data we want to add to the project. We reuse the endpoint from 1) but with the following payload:

```
{
    "type: 2,
    "data_url": <url to be crawled>,
    "project_id": <project_id>,
    "relative_path": <path from root of the repository where that files should be placed>,
    "commit_message": <commit_message>
}
```

Since this action should be performed in an async way due to the potentially large size of `<data_url>`, we would submit the requested action as a job to the job queue and return the `<job_id>` in the response.

Response example:
```
{
    "result": {
        "job_id": <job_id>
    }
}
```

or error if one occurred,
```
{
    "error": {...}
}
```

**Comment by rokroskar** [comment]
Isn't this issue about adding a file that is already in the project to a dataset (that is also already in the project)?

**Comment by rokroskar** [comment]
This makes sense - what happens if both `file_id` and `file_path` are passed?

**Comment by jsam** [comment]
I would say you get the following response:

```
{
    "error": {
        "code": -32602,
        "reason": "invalid reference found"
    }
}
```

**Comment by rokroskar** [comment]
What about a more informative "must use either file_id or file_path but not both"?
