### ISSUE TITLE
RaaS: Add uploaded file to project

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#770]
Add a feature on renku service to add uploaded files to a cloned project.

**Comment by rokroskar** [comment]
you mean outside of a dataset?

**Comment by jsam** [comment]
There are 2 possible ways to add a data file to the project. 


**By upload**

In this scenario, we start by uploading a data file to the cache and receive a reference ID. This reference ID could be then used in the following endpoint:

```
/projects/add
```

where payload would be
```
{
    "type: 1,
    "file_id": <reference_id>,
    "project_id": <project_id>,
    "relative_path": <path from root of the repository where that files should be placed>,
    "commit_message": <commit_message>
}
```

This action could be performed in sync way and could return following response:
```
{
    "result": {
        "commit": <created commit>
    }
}
```

or error if one occurred:
```
{
    "error": {...}
}
```


**By external crawl**

In this scenario, we submit a remote URL containing the data we want to add to the project. We reuse the endpoint from 1) but with the following payload:

```
{
    "type: 2,
    "data_url": <url to be crawled>,
    "project_id": <project_id>,
    "relative_path": <path from root of the repository where that files should be placed>,
    "commit_message": <commit_message>
}
```

Since this action should be performed in an async way due to the potentially large size of `<data_url>`, we would submit the requested action as a job to the job queue and return the `<job_id>` in the response.

Response example:
```
{
    "result": {
        "job_id": <job_id>
    }
}
```

or error if one occurred,
```
{
    "error": {...}
}
```
