### ISSUE TITLE
RaaS: Create long running operation asynchronous

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#771]
To provide convenience and alleviate the burden from the clients we should create long-running operation in async way. 

One way of doing this would be using aiohttp for which we need to drop support of certain Python version which we currently support (3.5.x, 3.6.0, 3.6.1).

**Comment by rokroskar** [comment]
For the current needs celery might be more appropriate.

**Comment by jsam** [comment]
Since we rolled out with Redis as a backbone for our caching, we should add RQ for scheduling. 

As a part of this ticket, we could add an endpoint with which we can retrieve all currently en-queued jobs.

Example of `GET /jobs` would be:
```
{
    "result": {
        "jobs: []
    }
```

**Comment by jsam** [comment]
I'm closing this ticket in favor of #984 where more details could be found.
