### ISSUE TITLE
Raas: allow projects with external storage disabled

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#773]
Currently, we have no support in our core methods to work over projects with external storage disabled. Since on UI side, we have templates that create projects with external storage disabled, we need to build additional support in our core to support manipulation over such projects. 

Init method should also be refactored to support reinitialization/enabling of external storage for such projects.

**Comment by rokroskar** [comment]
I don't follow - where is external storage disabled? The LFS configuration is local to wherever the project is checked out since it is set in the git client configuration. For the CLI, there is the `-S` option that allows you to work without external storage. 

> Init method should also be refactored to support reinitialization/enabling of external storage for such projects.

This you can already do with `renku init --force`, e.g. 

```
renku init -S test-no-ext
cd test-no-ext
git config --local -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true

renku init --force
Initialized project in /private/var/folders/99/jng0jljd13db0h4jwbwtx4mh0000gn/T/tmpdnqq0ag9 (branch renku/init/199e7827a5cc88a26c7326eab2b820bb41cda44c)

git config --local -l
core.repositoryformatversion=0
core.filemode=true
core.bare=false
core.logallrefupdates=true
core.ignorecase=true
core.precomposeunicode=true
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
filter.lfs.clean=git-lfs clean -- %f
```

**Comment by rokroskar** [comment]
closing as I think this is a non-issue with the `renku clone` command handling LFS configuration.
