### ISSUE TITLE
cli: renku migrate datasets fails

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#781]
## Describe the bug
`renku migrate datasets` fails catastrophically, but maybe the better question is why there is a `DatasetFile` with a blank `path`.

## Details
Git repo URL: `git@dev.renku.ch:virginiafriedrich/zurich-bikes-2.git`

**Renku version:** 0.7.0
**OS:** Darwin (Darwin Kernel Version 18.7.0: Thu Jun 20 18:42:21 PDT 2019; root:xnu-4903.270.47~4/RELEASE_X86_64)
**Python:** 3.7.4

### Traceback

```
Traceback (most recent call last):
  File "<attrs generated init renku.core.models.datasets.DatasetFile>", line 30, in __init__
    self.filename = __attr_converter_filename(__attr_factory_filename(self))
  File "[...]/renku/core/models/datasets.py", line 266, in <lambda>
    filename = attr.ib(kw_only=True, converter=lambda x: Path(x).name)
  File "[...]/pathlib.py", line 1010, in __new__
    self = cls._from_parts(args, init=False)
  File "[...]/pathlib.py", line 665, in _from_parts
    drv, root, parts = self._parse_args(args)
  File "[...]/pathlib.py", line 649, in _parse_args
    a = os.fspath(a)
TypeError: expected str, bytes or os.PathLike object, not NoneType
```

**Comment by jsam** [comment]
It seems that other commands fail with the same errors, and not just migrate datasets. After a quick patch and successful migration that file without filename is still there. I would consider this a broken state and handle this validation at the import step. As a followup, it would be extremely helpful if I can have DOI of the imported dataset which caused this problem so we can add it to the testing suite.
