### ISSUE TITLE
enable "renku run --input <dataset-name>"

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#787]
Renku users would like to use the `Dataset` abstraction in other renku commands. The most obvious example is to provide the ability for something like:

```bash
renku run --input-dataset <dataset> <command>
```
In this case, renku should make the contents of `<dataset>` available to `<command>`. 

Similarly, it would be desirable to enable this behavior:

```bash
renku run --output-dataset <dataset> <command>
```
Here, outputs would automatically be added to `<dataset>`.

**Comment by Panaetius** [comment]
Maybe we should do a workshop since this is probably larger than the design meeting format

**Comment by Panaetius** [comment]
It makes sense to think about this after we had a chance to discuss graph building changes in https://github.com/SwissDataScienceCenter/renku-python/issues/1312

**Comment by ciyer** [comment]
This looks like a duplicate of #706. Those two should be consolidated.

**Comment by Panaetius** [comment]
closing this in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/706
