### ISSUE TITLE
feat(datasets): should not allow to created nested datasets

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#789]
## Describe the bug
`renku migrate datasets` crashes for project https://dev.renku.ch/projects/rokroskar/vom_natt:

```
Traceback (most recent call last):
  File "[...]/renku/core/commands/migrate.py", line 32, in migrate_datasets
    migration(client) is not False for migration in STRUCTURE_MIGRATIONS
  File "[...]/renku/core/commands/migrate.py", line 32, in <listcomp>
    migration(client) is not False for migration in STRUCTURE_MIGRATIONS
  File "[...]/renku/core/commands/checks/migration.py", line 148, in migrate_datasets_pre_v0_3
    ref.set_reference(new_path)
  File "[...]/renku/core/models/refs.py", line 83, in set_reference
    self.path.parent.mkdir(parents=True, exist_ok=True)
  File "[...]/pathlib.py", line 1258, in mkdir
    self._accessor.mkdir(self, mode)
FileExistsError: [Errno 17] File exists: '/Users/rok/Projects/renku-test-projects/vom_natt/.renku/refs/datasets/VOM_output/AdelaideRiver'
```

The reason is that there are nested datasets in the repository and migration tries to create a symlink with the same name as an existing directory in `refs/datasets/`. We should not allow the user to create nested datasets and fail with a useful error message if they try to do this.

**Comment by mohammad-sdsc** [comment]
I could not reproduce this error using the latest commit in your branch. This error happens if I checkout the commit on June 13th, 2019 (`e4c52edd269eb740a1783d5d0cb82fbc3d334323`). Is this where this bug happens?

**Comment by rokroskar** [comment]
ah yes, in the meantime I've fixed the project. :) If you check out 0a73a21 or earlier it should give the error.

**Comment by mohammad-sdsc** [comment]
I also noticed another weird issue with this project: if I run `renku migrate datasets` on the last commit, `c3d365224a7d5b36098d7d117bd242ea378785a6`, the migrations succeeds but the metadata file `.renku/datasets/c7fe0b80-6064-46a3-a175-71d47d1d2a86/metadata.yml` contains some invalid entries:
```
...
  - VOM_output/AdelaideRiver
...
```

**Comment by rokroskar** [comment]
yes I tried to fix it but didn't do it fully - I moved the sub-datasets into the top level `data/` directory but I didn't change the metadata. We should probably have this done as a part of `renku mv` command.

**Comment by mohammad-sdsc** [comment]
Since we've got away from submodules in https://github.com/SwissDataScienceCenter/renku-python/issues/679 should we migrate all these old project to the new style and remove the submodules?

**Comment by rokroskar** [comment]
You mean in general? Probably - but this one in particular is not using submodules.

**Comment by mohammad-sdsc** [comment]
Yes, I was thinking of a general migration solution. ATM, we keeps submodules when migrating old projects.
