### ISSUE TITLE
Atomic execution of Renku commands

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#800]
Some Renku commands create multiple commits when executing. For example, when adding a file to a dataset, it first creates a commit to add all files to the project and creates a second commit to update dataset's metadata (this is done because commit hash of the files is needed in the metadata). If a command fails at a later stage, then some changes are already committed and the project might end up in an inconsistent state.

To address this issue, Renku can create a separate branch for each command and do a merge to master at the very end if the command was successful. A fast-forward merge should be possible in most cases.

**Comment by Panaetius** [comment]
Not really relevant with new metadata
