### ISSUE TITLE
Possibility to update dataset files that are added from a Git repo to a specific commit

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#802]
`renku dataset update` command should optionally take a --ref option to specify a tag, commit, or branch and update the files to them.
The dataset metadata should be update accordingly.

**Comment by rokroskar** [comment]
Would adding the `--ref` at the time of `renku dataset add` fit into the scope of this issue?

**Comment by mohammad-sdsc** [comment]
It should be pretty straightforward to add the functionality to `renku dataset add` when we have it for `update`. I'll try to include it here.
