### ISSUE TITLE
Support DOI provider over HTTPs

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#811]
Currently, if I use the following command:

```renku dataset import https://doi.org/10.5281/zenodo.3348115```

CLI ends up in a crash. What I would expect is either a nice message that we cannot resolve the DOI (e.g. `DatasetNotFound`) or that we import the dataset if found.

**Comment by rokroskar** [comment]
I didn't wait for the 18GB to download but up to that point everything seemed ok - where does it crash for you?

**Comment by rokroskar** [comment]
Is this still an issue?

**Comment by rokroskar** [comment]
Closed by #813
