### ISSUE TITLE
Improve terminal outputs on dataset commands

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#821]
Currently, we have some inconsistencies on dataset terminal output commands which we could improve. This ticket is about improving the naming and formating issue of those commands.

1. dataset parent subcommand (which servers as a list) and dataset ls-files format format list of creators differently
2. figure out how to deal with use case when there is 30+ creators in the display list
3. show a relative path for files
4. use display name (or better reference strategy method) as dataset name everywhere (#791)
5. renku created datasets should always resolve to same name

**Comment by rokroskar** [comment]
Is 4. in the list above different from 5.?
