### ISSUE TITLE
Imported datasets use UUID instead of DOI

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#839]
**Describe the bug**
When importing a dataset from Zenodo or Dataverse, the dataset ID is a UUID instead of being DOI of the imported dataset. Similarly, the dataset directory in `.renku/datasets` is also a UUID.

**To Reproduce**
```
renku init
renku dataset import https://zenodo.org/record/3251128
ls .renku/datasets/
```

**Expected behavior**
Dataset's DOI should be used for ID and directory name.

**Additional context**
Make sure that `renku migrate datasets` works after this fix.

**Comment by mohammad-sdsc** [comment]
After discussion with @Panaetius, it came out that this is a feature and not a bug. If we use DOI as ID there will be an issue with dataverse, namely that dataverse has versions like 4.0 but doesn't change DOIs between versions, so a user might try to add the "same" dataverse dataset with different versions (with different short_names), which would fail as the DOI is the same.

Moreover, there's also the usecase of adding a dataset twice with different short_names so it ends up in different `data/` subfolders.

**Comment by rokroskar** [comment]
> After discussion with @Panaetius, it came out that this is a feature and not a bug. If we use DOI as ID

Do you mean `id` or `identifier`? I guess you mean `identifier`.

**Comment by mohammad-sdsc** [comment]
After discussion with @jachro and @rokroskar, we decided to give imported datasets unique IDs and not using DOI as ID. We rely on `sameAs` property to check if two datasets are identical or have the same origin.
