### ISSUE TITLE
Wrong file location when adding files to imported datasets

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#840]
**Describe the bug**
When adding a file to an imported datasets, the new file is added to a data directory with dataset's name instead of the dataset's directory.

**To Reproduce**
```
$ renku init
$ renku dataset import https://zenodo.org/record/3251128
$ ls data
contemporary_phenotypic_12
$ renku dataset add contemporary_phenotypic_12 https://example.com/index.htm
$ ls data
contemporary_phenotypic_12 'Contemporary phenotypic change in plant quantitative traits'
```

**Expected behavior**
Files must be added to the same folder.

**Comment by rokroskar** [comment]
related to https://github.com/swissdatasciencecenter/renku-python/issues/791
