### ISSUE TITLE
feat: show loading bar for file download from url

### ISSUE THREAD

**Issue by emmjab** [SwissDataScienceCenter/renku-python#847]
**Is your feature request related to a problem? Please describe.**
When a user calls `renku dataset add <dataset> <url>` the user does not get any feedback about how much data is being downloaded.

**Describe the solution you'd like**
1. before continuing with the download, inform the user about how much data is coming so they have some idea of how long they'll have to wait, and inform the user it's too much for the pod to handle if possible (i.e. I found out the hard way that max 20GB can be handled in the pod, and then everything is lost because you can't push to gitlab from a frozen notebook).
2. in addition, show a loading bar while the data is downloading.

I think you can get the size of the data in the following way:
```
>>> import requests
>>> response = requests.head('https://storageaccountperma8980.blob.core.windows.net/hackathon-on-permafrost/timelapse_images_fast.zip')
>>> response.headers
{'Content-Length': '7223888389', 
'Content-Type': 'application/zip',
 'Content-MD5': '5ROuO4TmjSAx6iH6gBu7eA==', 
'Last-Modified': 'Thu, 28 Nov 2019 14:02:31 GMT',
 'ETag': '0x8D7740B9C8B23EB',
'Server': 'Windows-Azure-Blob/1.0 Microsoft-HTTPAPI/2.0', 
'x-ms-request-id': 'cc747c09-a01e-00de-7e73-a790c5000000', 
'x-ms-version': '2009-09-19',
'x-ms-lease-status': 'unlocked', 
'x-ms-blob-type': 'BlockBlob', 
'Date': 'Sat, 30 Nov 2019 11:44:59 GMT'}
```

**Additional context**
I think this is pretty high priority considering how many questions users have about how much data they can use.

**Resources**
Here's an example dataset for downloading; it's between 8 and 9 GB: renku dataset add images https://storageaccountperma8980.blob.core.windows.net/hackathon-on-permafrost/timelapse_images_fast.zip

**Comment by rokroskar** [comment]
You certainly don't always know the amount of data ahead of time - but I suppose we could check the headers and present the information if it exists.

**Comment by Panaetius** [comment]
This should be fixed already with the newest changes to datasets by @mohammad-sdsc
