### ISSUE TITLE
Dataset's description and person's affiliation not to occur when blank

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#849]
It looks `renku log` produces Dataset's `description` and person's `affiliation` properties even if their values are blank. They should not be created in such cases.

**Comment by Panaetius** [comment]
I fixed description, but I couldn't reproduce affiliation being empty when creating a dataset. If I create a new dataset on my machine, affiliation is not set, and when I run `renku log`, it's not exported, so it seems to be working. @jachro can you verify that affiliation is exported empty with the newest version and that it's not just a left-over `""` value from a previous version of renku?

**Comment by jachro** [comment]
Hi Ralf,

My suspicion is that the blank affiliation could be coming from the
external sources like Zenodo or Dataverse not us directly. But I guess it
would be still nice if we can detect that and in case it's blank or empty
we can skip adding the property. Would that make sense? I do that on my
side anyway :)
