### ISSUE TITLE
RaaS: Implement a cleanup strategy

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#851]
Currently uploaded files and clone projects are cached indefinitely. This will soon become a problem in production. This proposal aims to resolve that problem.

To address the problem we will need a [scheduler](https://github.com/rq/rq-scheduler) and a [rqworker](https://python-rq.org/docs/workers/). 

On the queue `cleanups` scheduler will produce a job every minute. Worker listening on the `cleanups` queue will pick up the job and execute the following checks:

1. Find uploaded files older than 24 hours (configurable via ENV). Delete found files from file system and cache.

2. Find cache projects older than 24 hours (configurable via ENV). Delete found projects from file system and cache.

Both of the checks should ensure that cache state is valid and fix it if it's not.

**Comment by ciyer** [comment]
Is there a plan for how to handle resource pressure when a user attempts something? E.g., if a user wants to upload a file that would cause the disk to fill, could we remove the oldest files in the cache in order to make space for the request?

**Comment by rokroskar** [comment]
We should probably come up with reasonable limits here. For anything larger than the limit (e.g. 10GB?) we point the user to the instructions on how to accomplish the task via the CLI

**Comment by ciyer** [comment]
Agreed, that makes sense, and is something that should be handled in the UI, but the potential problem still remains. 

Imagine we have 20 GB of space for the cache, and 19.5 GB are currently occupied. A user wants to upload a 1 GB file -- this is a reasonable thing to want to do, but it will fail until the cache is cleaned up.

**Comment by rokroskar** [comment]
ah yes, absolutely. I wasn't suggesting that setting a limit would somehow circumvent the diskspace issue. Just pointing out that we can't satisfy arbitrarily large uploads even with cleanup in place so these need to happen together.

**Comment by jsam** [comment]
I don't think that we should try to be too smart (code wise) about this operational problem. 

If the above case happens (which I agree it might occur) it also implies that all cached objects are potentially hot, so instead, that service starts to silently push other active users out (by deleting their cached objects) just to make the space for new user it should block the new user upload until the resources (disks space in this case) has been released (or expanded from the operations perspective). This should trigger alert manager notification and we should address the problem immediately from operational perspective instead of harming user experience by pushing others out.

I think we have all the cogs in place to handle this problem from operations perspective sufficiently good. And we should definitely have alert manager set up and running for this so we can handle it from operational perspective (if need be) - same goes for insufficient memory resource which might occur due to too much upload data being materialized.

**Comment by jsam** [comment]
To answer your question, yes there is a plan to address resource pressure (both memory and disk) and the plan is to horizontally scale the service out. We plan to support this, and we are building the service with that in mind. It's just the matter of time when we full set everything up.

**Comment by ciyer** [comment]
It's not just an operational issue. Another aspect is communicating actionable information to the user.

To keep this simple, consider a scenario with two users, user 1 and 2. User 1 has uploaded a bunch of files, and user 2 would like to upload some files but cannot until user 1's files are cleaned out, and we have *timed* cache cleanup (cleanup happens at set intervals) and *active* cleanup (cleanup runs when needed)

## Scenario 1: User 1's files are cold (she doesn't care if they are deleted)

| User  | Timed Cleanup   | Active Cleanup  |
| ----- | --------------- | --------------- |
| User1 | 😄                    | 😄        |
| User2 | 😢                    | 😄        |


## Scenario 2: User 1's files are hot (she is working and needs them)

| User  | Timed Cleanup   | Active Cleanup  |
| ----- | --------------- | --------------- |
| User1 | 😄                    |  😢        |
| User2 | 😢                    | 😄          |


In the timed-cleanup world, someone is always unhappy: User 2. In the active-cleanup world, only in scenario 2 is anyone unhappy. Also consider the case that Users 1 and 2 are the same person. Then timed-cleanup is especially annoying.

Then, there is the question of error messages. In the active-cleanup solution, it is clear what we tell the user: "Sorry, you need to upload your files and try again." In the timed-cleanup solution, what should we tell the user? "There isn't enough space for you data now. Try again sometime in the future."?

**Comment by jsam** [comment]
Scenario 1: With interval cog being set to 1 second there is literally no difference between active and timed cleanup you're describing. Same effect can actually be achieved with interval cog being set to much higher intervals (e.g. 30-60 seconds). So I would not say they are unhappy, since from users perspective it will be the same thing. Therefore, it depends on how you operate the service, all of this can be extremely easily avoided (imho).

Scenario 2: I find it unacceptable that 1 user can affect the usage experience of another. 

Messaging:
I both cases you should display the message "Sorry, you need to upload your files and try again. Something went wrong.". In which back end needs to trigger auto provisioning in which it will provision needed resources and resolve the problem if the user starts again (hence, operation problem).
