### ISSUE TITLE
Renku clone should use project name by default

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#856]
**Is your feature request related to a problem? Please describe.**
If we don't provide a path when running `renku clone URL`, Renku by default uses the current directory to clone the repo. This fails if current directory is not empty. Similar to what git does, it's better to use repo's name as the target directory.

**Additional context**
Related to https://github.com/SwissDataScienceCenter/renku-python/issues/853

**Comment by jeffallen** [comment]
And/or update the help message to explain:

```
$ renku clone -h
Usage: renku clone [OPTIONS] URL [PATH]

  Clone a Renku repository.

Options:
  --pull-data  Pull data from Git-LFS.
  -h, --help   Show this message and exit.
```

It was this help message (the fact that the PATH is shown as optional) that lead me to guess it acts like git.
