### ISSUE TITLE
Dataset content preview table has wrong indentation

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#860]
**Describe the bug**

```
renku dataset import 10.5281/zenodo.3549866
CHECKSUM                          NAME              SIZE (MB)  TYPE
--------------------------------  --------------  -----------  ------
e00d2805076a00aa5515fb988fda6573  data_small.zip     4.69636   zip
8fdc30aa0546ed2b8a520c06b4b387b4  data.zip        1635.33      zip
4008ea48e3afae4d8466fdb9b9f2f65a  generation.py      0.010506  py
```

Indentation is inconsistent.

**Comment by mohammad-sdsc** [comment]
This looks pretty consistent to me. Can you add more context?

**Comment by rokroskar** [comment]
Ideally the size column would be either left or right justified, no?

**Comment by mohammad-sdsc** [comment]
It is aligned around the decimal point which to me makes it easy to read and compare the sizes. Maybe we should limit the number of digits after the decimal point to some thing smaller than 6 (e.g. 2)?
