### ISSUE TITLE
Performance improvement: Improve jsonld serialization

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#863]
As examined with @Panaetius we have determined that current speed problems are related to graph displaying (60%) and graph building (30%). This ticket is about improving run time expansion/compaction of jsonld located in: `format/graph.py`.

```
output = getattr(pyld.jsonld, format)([
        asjsonld(action) for action in graph.activities.values()
    ])
```

**Comment by Panaetius** [comment]
Not relevant anymore due to https://github.com/SwissDataScienceCenter/renku-python/issues/2110
