### ISSUE TITLE
build: automate version bumps in dependent repos

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#871]
Whenever we tag a version of renku-python we should automatically change the version in the matrix build of `renku-jupyter`.

**Comment by emmjab** [comment]
and also in `renku-project-template`

**Comment by rokroskar** [comment]
well that repo will eventually not be used anymore once we are instantiating projects via the service.

**Comment by emmjab** [comment]
But right now unless those are updated, if you make a new project you won't get the new docker image so it's like it doesn't exist to users.

**Comment by rokroskar** [comment]
yep, sure - though the tag in `renku-jupyter` should trigger that update

**Comment by rokroskar** [comment]
closing in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/2025

**Comment by Panaetius** [comment]
Closed in favor of https://github.com/SwissDataScienceCenter/renku-python/issues/2025
