### ISSUE TITLE
import fails when subjects are provided

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#885]
**Describe the bug**

```
renku dataset import 10.5281/zenodo.3490468

...

  File "<attrs generated init renku.core.commands.providers.zenodo.ZenodoRecordSerializer>", line 9, in __init__
  File "/Users/rok/Projects/renku-core/renku-python/renku/core/commands/providers/zenodo.py", line 160, in _metadata_converter
    return ZenodoMetadataSerializer(**data)
TypeError: __init__() got an unexpected keyword argument 'subjects'
```

**Proposal**

The import is calling the zenodo API to get the metadata - instead, we could simply consume the json-ld either from the embedded `<script>` tag in the dataset page HTML on zenodo or by requesting json-ld specifically. 

Additionally, we should not fail if extra metadata that we don't handle is supplied - we should perhaps show a warning to the user but proceed.

**Comment by emmjab** [comment]
I ran into a similar-looking issue here: https://github.com/SwissDataScienceCenter/renku-python/issues/937
