### ISSUE TITLE
link to zhbikes file for tutorial is not available

### ISSUE THREAD

**Issue by samuele-ceolin** [SwissDataScienceCenter/renku-python#897]
The link to the file "zhbikes" https://data.stadt-zuerich.ch/dataset/verkehrszaehlungen_werte_fussgaenger_velo/resource/d17a0a74-1073-46f0-a26e-46a403c061ec/download/2019_verkehrszaehlungen_werte_fussgaenger_velo.csv to be used in the Renku tutorial is not available anymore.

The issue arises in the second step "Adding data to your project" of the tutorial "Getting started with Renku" (https://renku.readthedocs.io/en/latest/user/firststeps.html) when the dataset is supposed to be downloaded.

**Comment by ciyer** [comment]
Thanks for filing this bug report! That data set must have been removed recently. We are working on updating the documentation to use a new data set, and that new version should be available in a few days.

**Comment by ciyer** [comment]
The tutorial has been updated to use a different dataset.

https://renku.readthedocs.io/en/latest/user/firststeps.html
