### ISSUE TITLE
renku run does not pull dataset data 

### ISSUE THREAD

**Issue by rokroskar** [SwissDataScienceCenter/renku-python#903]
**Describe the bug**

I expect `renku run` to handle LFS data for me - if I need a file that is not pulled from LFS, it should be pulled automatically. This functionality was implemented, but perhaps it only works files that are created as outputs of a `renku run` command. We should check all paths that we can reasonably interpret as being needed for the command that is being executed and pull the data first.

**Comment by Panaetius** [comment]
Can you be a bit more specific on what project/dataset/workflow was used, what happened etc.?

LFS files should be pulled on `renku run` , this code should handle it: https://github.com/SwissDataScienceCenter/renku-python/blob/master/renku/cli/run.py#L248 which looks like it should work on all input files.

**Comment by rokroskar** [comment]
[Go here](https://renkulab.io/projects/rok.roskar/flights-tutorial-demo/environments/new) and start a new environment - run `renku update`. It will fail because the LFS objects have not been fetched.
