### ISSUE TITLE
Add migration mechanism

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#922]
- Throw exception if not migrated. Prevent execution unless migrated
- new migration mechanism. Incremental numbers, no backwards migrations (git reset)
- Save current migration in project metadata
- Automated revert if migration breaks, alert user to downgrade renku version

**Comment by rokroskar** [comment]
Should step 0 be to compile a list of needed migrations to-date?

**Comment by Panaetius** [comment]
See https://github.com/swissdatasciencecenter/renku-python/issues/920
