### ISSUE TITLE
Immutable Datasets

### ISSUE THREAD

**Issue by mohammad-sdsc** [SwissDataScienceCenter/renku-python#926]
As a Renku user, I would like to be able to differentiate an imported dataset that is modified by me from its origin.

**Additional context**
When we import a dataset, we set `schema:sameAs` property of the imported dataset to point to the DOI/URL of the original dataset. If we modify this dataset locally then it is not literally the same dataset as its origin anymore.

**Acceptance criteria**
* a new dataset `schema:identifier` should be created in case of a dataset modification;
* all the original dataset properties should be kept with few exceptions:
  * the `schema:sameAs` (and I guess the `schema:url`) should be dropped if existed;
  * the `schema:dateCreated` should be set to the date of the modification;
  * the person who performed the modification should be added to `schema:creator`;
  * all the other properties like `name`, `description`, `hasPart`, and so on should be changed only if that was the part of the modification to the dataset;
* a new `prov:wasDerivedFrom` pointing to the original dataset should be added to the newly created dataset entity;

**Comment by rokroskar** [comment]
This sounds good to me - the only thing that is missing (maybe on accident?) is that `wasDerivedFrom` should point to the original dataset so the provenance path is clear. 👍

**Comment by emmjab** [comment]
I'm not sure if this is the top level issue for this, but for instance on dataverse, the DOI seems to stay the same even if you "republish" with changes, and a "V2", "V3", etc. are updated. In that case we would want to keep (DOI/URL, Version) for sameAs somehow?
