### ISSUE TITLE
schema:datePublished not set for imported datasets

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#929]
It looks like we somehow dropped the `schema:datePublished` on the Dataset entities. As far as I remember this date was set to:
* the date an imported dataset was published at the external service like Zenodo or Dataverse;
* the date of dataset creation in case of a dataset created manually for a project.

Could we get them back, please?

**Comment by Panaetius** [comment]
Is this still an issue?

**Comment by jachro** [comment]
It doesn't look like. I've just checked the failures on PROD.
