### ISSUE TITLE
feat: Improved handling of non-renku repositories

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#932]
Currently, if I execute any of the commands on the repository which is not initialized as renku repository (no .renku directory), I get the following:

```
Ahhhhhhhh! You have found a bug. 🐞

1. Open an issue by typing "open";
2. Print human-readable information by typing "print";
3. See the full traceback without submitting details (default: "ignore").

Please select an action by typing its name (open, print, ignore) [ignore]: 
```

Instead, of this message I would expect a more user friendly message, such as:

```
WARNING: This is not a renku initialized repository.

Would you like renku to manage this repository? [y/N]
```

**Comment by ciyer** [comment]
This happens also happens on commands that do not require access to the repo. Try running `renku dataset add --help` outside a repo.

Commands that access the repo should prompt to initialize a repo as above. Help commands should should just print help.

**Comment by ciyer** [comment]
Regarding the behavior in this situation, I think the behavior should be different in two situations:

## 1. In a git repository
### Option 1
```
WARNING: This is not a renku initialized repository.

Would you like renku to manage this repository? [y/N]
```

### Option 2
```
This is not a renku initialized repository. Run 'renku init .' to make it one.
```

## 2. Not in a git repository

```
fatal: not a renku repository.
```

**Comment by rokroskar** [comment]
+1 for Option 2. 

Note, however, case 2. could also be covered by Option 2. Could it not?

**Comment by ciyer** [comment]
Yes, you are right. Though in that case, the message should mention that it is not even a git repository. Reasoning: sometimes I type a renku command in a plain git repository, thinking I'm in a renku repository, but if I type a renku command in a regular directory, I'm usually not in the directory I think I'm in.
