### ISSUE TITLE
feat: moving files from git objects to LFS

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#933]
Currently, if we add a list of files where 1 of the files is already part of git history, that file will just be added to LFS. 

For example, let's imagine the following scenario:

```
cd my-awesome-renku-project
cp ~/Models/realtime_model.njson .
git add .
git commit -m "chore: added realtime model"
renku dataset add train-data ~/Models/old_model.njson realtime_model.njson
```

This is a problem now cause now we have same data being part of the git graph and object store. 

To build a better user experience we could think about that add operation should support only 1 type per transaction (either you add only internal files or you add external files). This way we can build a better messaging to the user on what's going on when things don't work as expected.

To address this problem better we should most likely: 
  1. Warn the user of this problem 
  2. Utilize `git lfs migrate` and move the file properly to the LFS

Proposed solution for above problem:

```
git lfs migrate import --include="realtime_model**" --include-ref=refs/heads/master
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```
Downside to this solution is that it will rewrite history (and will require a force push) at the cost of fixing the problem so we should definitely think about how to model the user experience of this.

**Comment by rokroskar** [comment]
With git hooks and the default sizes set for objects going to LFS (or not) I'm not sure this is an issue anymore. For example, I just tried the exact sequence you have at the top:

```
$ pipx install --force renku==0.11.1
$ renku init test-lfs
$ cp ~/Downloads/test-artifacts-11/20200612081920-MinimalFunctionalitySpec.png .
$ git add 20200612081920-MinimalFunctionalitySpec.png
$ git commit -am 'adding file'

You are trying to commit large files to Git instead of Git-LFS.

Large files:
20200612081920-MinimalFunctionalitySpec.png

To track these files in Git LFS use "git lfs track <FILENAMES>".

To commit anyway, use "git commit --no-verify".
```

So you really have to try a bit harder now to screw up your repo in the way you describe. I would vote for closing this for now or reformulating to be more specific if something is still missing.

**Comment by Panaetius** [comment]
Closed for now. It should happen very rarely and the workflow above using `git lfs` commands should be enough.
