### ISSUE TITLE
fix: improve service IT

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#936]
Current, service integration tests are executed against 1 repo and work only on master branch. This is a problem cause executing this tests often leads to a certain stress which renku cannot handle. 

Currently, we executed them for a month which lead to 6k commits at which point repository got so big that renku does not finish any of the commands being executed on it. I've tried to execute renku command on it and left it there hanging for over 3 hours and still it did not finish.

The idea of improvement is to eliminate this slowness after each run. To achieve this we should run all the integration tests on it's own branch. This would help significantly with the speed and stability of the IT.

**Comment by emmjab** [comment]
if I'm reading this correctly, this sounds like a useful QA case for improvement of renku performance for repositories with 6k commits. Where does the repo live?

**Comment by jsam** [comment]
It's [here]( https://dev.renku.ch/gitlab/contact/integration-tests).
