### ISSUE TITLE
Dataset's sameAs should be an URL no a literal

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#942]
As a Renku Graph DB user, I'd like dataset's `sameAs` no to be a literal value but an URL object.

Acceptance criteria:
*  for cases of datasets imported from external sources like Zenodo or Dataverse the `sameAs` property should become:
```
"schema:sameAs": {
  "@id": "_:smth",
  "@type": ["https://schema.org/URL"],
  "url": {
    "@value": "https://doi.org/10.5281/zenodo.3351812"
  }
}
```
*  for cases when a dataset is imported from another Renku project the `sameAs` property should become:
```
"schema:sameAs": {
  "@id": "_:smthElse"
  "@type": ["https://schema.org/URL"],
  "url": {
    "@id": "https://renkulab.io/datasets/3429032"
  }
}
```
No so sure what should be the values of the `@id` property

**Comment by rokroskar** [comment]
I don't follow here - doesn't `sameAs` have to point to a specific node by its id? Why create a new entity for the URL?

**Comment by jachro** [comment]
It's due to the `schema.org`'s `sameAs` property which supposed to have a value of `schema:URL`.

**Comment by Panaetius** [comment]
sameAs has to be https://schema.org/URL as opposed to https://schema.org/url which is one of URL's properties. just highlighting as this might cause confusion

**Comment by rokroskar** [comment]
I see! Thanks for clarifying.
