### ISSUE TITLE
A new datasets identifiers should be generated on project forking

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#955]
It looks that currently when we fork a project with some datasets inside, we do not touch their datasets identifiers. That's not consistent with the changes done as part of [626 feat: Dataverse import](https://github.com/SwissDataScienceCenter/renku-python/pull/626) which did an effort of making datasets identifiers unique even for the same datasets on different projects and effectively causing the `schema:isPartOf` on a dataset having no or single value.

Acceptance criteria:
* When a project has a dataset(s) created in that project, the fork project should have the same dataset(s) but with a different identifier and `schema:sameAs` pointing to the source project dataset resource id (as it happens when you import a dataset from another Renku project);
* When a project has a dataset(s) imported to that project, the fork project should have the same dataset(s) but with a different identifier and `schema:sameAs` pointing to the source project dataset resource id (as it happens when you import a dataset from another Renku project - we assume here that the imported dataset could be already modified in the source project so we cannot say it's the same as the imported that anymore);

**Comment by rokroskar** [comment]
I'm not sure this is a bug. What it means is that we need to have a webhook on the gitlab fork event and potentially rewrite the project's history. Why is this needed? It sounds like a mess and it's non-standard behavior. I'm not sure it's necessary - what might be necessary is to generate a new dataset identifier when the dataset is modified. Wouldn't that be sufficient?

**Comment by jachro** [comment]
Right, I think I see your point.

Let's start from, I believe, the simpler case. So let's assume a dataset was created in a source project, then it was forked and at the end, the dataset got modified in the forked project. As you suggested, a new identifier (and probably the `sameAs` pointing to the source project's dataset id) should do the job. Isn't that actually smth to be addressed as part of https://github.com/SwissDataScienceCenter/renku-python/issues/926.

Now the misty case :) Let me first explain the background of my reasoning. With the change/fix Mohammad did as part of https://github.com/SwissDataScienceCenter/renku-python/pull/626, we effectively started making dataset entities immutable which means we shouldn't have cases when a dataset is pointing to two projects. To link projects pointing to the same dataset, we use the 'sameAs' property. I started tweaking the Graph Services' queries and I have to say everything started to build up some nice picture. At least there was a single way of reasoning. The last case which does escape from that is the forks. Yes, I agree, rewriting the history is definitely a no go and I wasn't thinking about that but got wondering if maybe some new dataset identifier can be generated in-flight when executing the `renku log` command and not persisted in the metadata? I'm guessing we have to be doing smth similar when we generate all the other entities which in the metadata of the old commits points to the source project but we generate them pointing to the fork. I deeply believe keeping things consistent here could be a lifesaver for us. What do you think? As far as I remember the idea of putting yet another `isPartOf` on the datasets was a bit of a hack anyway when we were fighting to push through the dataset release.

**Comment by jachro** [comment]
As discussed, the behaviour of adding a forked project link to a dataset entity while keeping the entity unchanged makes sense and will keep it. The obvious assumption here is that the dataset belongs to the source project.
