### ISSUE TITLE
feat: output prov:wasInvalidatedBy for Dataset and DatasetFile

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#959]
https://github.com/SwissDataScienceCenter/renku-python/pull/894 added `renku log` output for deleted files by generating `prov:wasInvalidatedBy` triples.

We should also generate `prov:wasInvalidatedBy` when a `Dataset` was removed or a `DatasetFile` was removed from a `Dataset`, with `prov:wasInvalidatedBy` pointing to the respective `Dataset` or `DatasetFile` node in the KG.

**Comment by rokroskar** [comment]
possible duplicate of #709

**Comment by jachro** [comment]
Indeed, it is a duplicate of #709. Closing according to what was decided on a meeting on 6/05/2020.
