### ISSUE TITLE
Load KG from disk for renku log

### ISSUE THREAD

**Issue by Panaetius** [SwissDataScienceCenter/renku-python#967]
Use the persisted KG ( #966 ) to generate `renku log` output. This should be done with the new JSON-LD library

**Comment by rokroskar** [comment]
It doesn't need to be done with the new JSON-LD library, does it?

**Comment by Panaetius** [comment]
Not necessarily, but since it would be new functionality (I don't see how we could use our current implementation easily without major changes for this), it makes sense to make it with the new library already so we don't have to do the work twice.
