### ISSUE TITLE
Renku to keep the value of sameAs when importing dataset to a project

### ISSUE THREAD

**Issue by jachro** [SwissDataScienceCenter/renku-python#979]
The problem here is that currently when a user imports a dataset from one Renku project to another Renku project, we put the original dataset id to the new dataset's `sameAs` property. Although that seems like a wise thing to do, it has some challenging consequence as grouping the same datasets becomes pretty difficult and expensive and requires recursive tree traversals. What do you think if we would change that behaviour so it works like follows:
* when we import a dataset from external storage (e.g. Zenodo) and then we import that dataset to another project, we'd keep the `sameAs` pointing to Zenodo DOI on the new project's dataset (assuming this dataset wasn't changed on the source project);
* when we create a dataset in some Renku project and then we import that dataset to another project, the `sameAs` on that another project would be pointing to the source project's dataset id;
* when we import a dataset from one Renku project to another project and the original dataset already has some `sameAs`, we'd preserve that value on the new project's dataset (assuming this dataset wasn't changed on the source project);
* when a dataset got modified, the `sameAs` value would be dropped and a new `prov:wasDerivedFrom` put instead as described in #926.

**Comment by rokroskar** [comment]
> The problem here is that currently when a user imports a dataset from one Renku project to another Renku project, we put the original dataset id to the new dataset's sameAs property.

This has not been merged to master yet - are you thinking about project forking? The implementation of importing renku datasets is being done in #838. 

I'm not sure I follow the request above though - it seems to me that the current implementation does everything apart from the last point?

**Comment by mohammad-sdsc** [comment]
It's true. This issue is just created to make a discussion about this decision. The current implementation in https://github.com/SwissDataScienceCenter/renku-python/pull/838 uses the link from the last dataset as the `sameAs` property (in case of chained imports). We wanted to change it and we wanted to make sure that this change is clear.
Do you see any problem with this change?

**Comment by jachro** [comment]
Cool! Thanks!

**Comment by rokroskar** [comment]
Just so we are on the same page. This is the current set-up if I understand correctly:

```
<https://renku/datasets/9012> <http://www.w3.org/TR/prov-o/sameAs> <https://renku/datasets/5678> .
<https://renku/datasets/5678> <http://www.w3.org/TR/prov-o/sameAs> <https://renku/datasets/1234> .
```

![image](https://user-images.githubusercontent.com/3353586/73659733-20a65880-4697-11ea-8f3d-6a078537adbe.png)

and what you propose is this:

```
<https://renku/datasets/5678> <http://schema.org/sameAs> <https://renku/datasets/1234> .
<https://renku/datasets/9012> <http://schema.org/sameAs> <https://renku/datasets/1234> .
```

![image](https://user-images.githubusercontent.com/3353586/73659763-2e5bde00-4697-11ea-89c4-012ab0336519.png)

**Comment by jachro** [comment]
Yes, that's what I was thinking about.

**Comment by rokroskar** [comment]
I think this makes sense semantically. what happens if the user wants to check for changes to a dataset? Which one gets checked? The one they imported from directly - lets say for the case of dataset `9012` above, that would be `5678`, or the one they ultimately depend on? It's possible that dataset `1234` is updated but `5678` hasn't pulled in the changes yet. In that case, what should happen?

**Comment by jachro** [comment]
I believe the modification issue (#926) is going to deal with that properly. What will happens is that when a DS is modified we replace the `sameAs` with `wasDerivedFrom` which simply says that these two DSs are not the same any more. Having the `sameAs` unchanged on few DSs means all of them are the same.

**Comment by jachro** [comment]
@rokroskar sorry but I didn't catch the last case you brought in. We discussed it with Mohammad a bit and we agreed that it's probably better to leave things as they are now which means **not** to keep the same `sameAs` when importing datasets to another Renku project but simply use the dataset's id.

**Comment by rokroskar** [comment]
But I though this was unworkable for querying the KG?

**Comment by jachro** [comment]
I think I have no option other than to craft a query that works for such cases :)
