### ISSUE TITLE
docs: improve readme

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#991]
Our current readme, seems to be a little bit outdated. This project has evolved significantly and it's no longer just "CLI & SDK" like we describe it in readme. I think we should restructure the readme to cover all different components of this project and different aspects of usage:

* renku-project
    1. [core] library and how to use it from Python as SDK
    2. [cli] This is covered mostly in our docs, so providing the link to those onboarding tutorials
    3. [svc] Service documentation is covered through OpenAPI spec and we should put a link to it (either swagger UI from the dev deployment or just link to a json file)

I propose we think about how we can restructure our readme so it provides better on boarding experience for new users and cover different types of users in a better way.

**Comment by rokroskar** [comment]
Totally agree, I was just thinking about this a few days ago!
