### ISSUE TITLE
chore: codestyle improvements

### ISSUE THREAD

**Issue by jsam** [SwissDataScienceCenter/renku-python#994]
There are a few coding style improvements which I see we could make.

1. I find 79 characters PEP8 rule quite outdated. It has been decades since that proposal has been written and average monitor size is significantly larger than at the time of writing that proposal. I've checked other open source projects and it seems that they had same pain, so they moved it to 119 chars per line. I propose we do the same to better utilize screen real estate.

2. With the silent drop of Python 3.5 we gain the possibility to move the project to be fully typed. This can help us to deal with all class of problems which plague us from time to time and also has nice options to specify module public interfaces through `.pyi` files. I've played a little bit with Instagrams [Monkeytype](https://github.com/Instagram/MonkeyType) and successfully migrated our repository with it and noticed quite a significant powerup in my IDE when I've added this typing.

3. Move standard way of formatting of string to f-strings instead of current `.format`. I think this one is self explanatory.

4. I've noticed that we are deviating from standard recommended way of writing assertions which was ```assert expected == received```. Let's settle and commit to one style and use it, instead of mixing it.

**Comment by rokroskar** [comment]
re: point 1, see also #870

**Comment by Panaetius** [comment]
All points sound good. fstring and assertions change can be done separately, black and type annotations should be done together I think

**Comment by Panaetius** [comment]
This is pretty much done and the rest will be done as we encounter issues
